#### BOW,TFIDF,Machine Learning Algorithms

1. Preprocessing And Cleaning
2. Train Test Split
3. BOW And TF-IDF (Sentences--->vectors) {Preventing Data Leakage}
4. Trained Our Models

In [1]:
import pandas as pd
messages=pd.read_csv('Data/SMSSpamCollection.txt',
                    sep='\t',names=["label","message"])

In [2]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
## Data Cleaning And Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [5]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub('[^a-zA-z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [8]:
corpus[:10]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free']

In [9]:
messages.shape

(5572, 2)

## Create Bag Of Words

In [ ]:
# X indepdent
# y denpendent

In [11]:
pd.get_dummies(messages['label'],dtype=int)

      ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [12]:
## Output Features
y=pd.get_dummies(messages['label'],dtype=int)
y=y.iloc[:,0].values

In [13]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [14]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [15]:
## Create the Bag OF Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [16]:
len(X_train),len(y_train)

(4457, 4457)

In [17]:
## independent features
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [19]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X_train[:5]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
cv.vocabulary_

{'would': np.int64(2443),
 'good': np.int64(814),
 'phone': np.int64(1538),
 'tomo': np.int64(2138),
 'shall': np.int64(1827),
 'someth': np.int64(1905),
 'sleep': np.int64(1875),
 'nt': np.int64(1433),
 'feel': np.int64(657),
 'well': np.int64(2375),
 'ye': np.int64(2478),
 'possibl': np.int64(1601),
 'dint': np.int64(524),
 'tri': np.int64(2163),
 'pl': np.int64(1556),
 'dont': np.int64(540),
 'tell': np.int64(2050),
 'one': np.int64(1474),
 'hey': np.int64(904),
 'sat': np.int64(1765),
 'go': np.int64(787),
 'intro': np.int64(1006),
 'pilat': np.int64(1551),
 'need': np.int64(1387),
 'lar': np.int64(1083),
 'co': np.int64(353),
 'si': np.int64(1845),
 'art': np.int64(93),
 'today': np.int64(2130),
 'lt': np.int64(1198),
 'gt': np.int64(847),
 'great': np.int64(839),
 'xma': np.int64(2466),
 'burn': np.int64(226),
 'updat': np.int64(2227),
 'total': np.int64(2152),
 'see': np.int64(1787),
 'star': np.int64(1955),
 'lt gt': np.int64(1200),
 'select': np.int64(1793),
 'stay': np.int64(1960),
 'top': np.int64(2149),
 'hotel': np.int64(950),
 'noth': np.int64(1431),
 'holiday': np.int64(930),
 'worth': np.int64(2440),
 'claim': np.int64(338),
 'call': np.int64(239),
 'london': np.int64(1165),
 'bx': np.int64(230),
 'sw': np.int64(2022),
 'ss': np.int64(1948),
 'claim call': np.int64(339),
 'sw ss': np.int64(2023),
 'reach': np.int64(1665),
 'alreadi': np.int64(51),
 'campu': np.int64(281),
 'librari': np.int64(1128),
 'babe': np.int64(124),
 'lost': np.int64(1179),
 'yo': np.int64(2493),
 'carlo': np.int64(297),
 'friend': np.int64(729),
 'ask': np.int64(95),
 'work': np.int64(2433),
 'weekend': np.int64(2367),
 'congratul': np.int64(396),
 'week': np.int64(2361),
 'draw': np.int64(550),
 'prize': np.int64(1626),
 'cs': np.int64(444),
 'stop': np.int64(1967),
 'sm': np.int64(1881),
 'ppm': np.int64(1607),
 'prize claim': np.int64(1628),
 'stop sm': np.int64(1975),
 'beauti': np.int64(146),
 'life': np.int64(1130),
 'next': np.int64(1403),
 'second': np.int64(1782),
 'hide': np.int64(912),
 'secret': np.int64(1783),
 'wish': np.int64(2408),
 'everi': np.int64(612),
 'wonder': np.int64(2427),
 'ur': np.int64(2233),
 'gud': np.int64(862),
 'ur life': np.int64(2243),
 'valu': np.int64(2282),
 'custom': np.int64(457),
 'pleas': np.int64(1571),
 'follow': np.int64(695),
 'recent': np.int64(1683),
 'mob': np.int64(1304),
 'award': np.int64(115),
 'bonu': np.int64(186),
 'award bonu': np.int64(116),
 'prize call': np.int64(1627),
 'student': np.int64(1989),
 'solv': np.int64(1899),
 'question': np.int64(1648),
 'answer': np.int64(64),
 'brilliant': np.int64(210),
 'thing': np.int64(2087),
 'got': np.int64(826),
 'gt lt': np.int64(852),
 'get': np.int64(763),
 'ticket': np.int64(2108),
 'th': np.int64(2072),
 'march': np.int64(1233),
 'mate': np.int64(1239),
 'ill': np.int64(979),
 'pay': np.int64(1517),
 'treat': np.int64(2162),
 'want': np.int64(2327),
 'txt': np.int64(2190),
 'bak': np.int64(132),
 'want go': np.int64(2329),
 'yar': np.int64(2475),
 'lor': np.int64(1174),
 'wait': np.int64(2312),
 'mum': np.int64(1359),
 'finish': np.int64(681),
 'sch': np.int64(1775),
 'lunch': np.int64(1208),
 'whole': np.int64(2389),
 'morn': np.int64(1334),
 'home': np.int64(935),
 'clean': np.int64(347),
 'room': np.int64(1740),
 'quit': np.int64(1650),
 'hee': np.int64(899),
 'yar lor': np.int64(2476),
 'thank': np.int64(2076),
 'repli': np.int64(1706),
 'come': np.int64(374),
 'still': np.int64(1964),
 'buy': np.int64(228),
 'bag': np.int64(130),
 'sister': np.int64(1863),
 'easi': np.int64(573),
 'uncl': np.int64(2216),
 'john': np.int64(1035),
 'also': np.int64(54),
 'bill': np.int64(164),
 'realli': np.int64(1675),
 'think': np.int64(2088),
 'make': np.int64(1218),
 'money': np.int64(1327),
 'later': np.int64(1090),
 'realli need': np.int64(1676),
 'oh': np.int64(1455),
 'watch': np.int64(2341),
 'say': np.int64(1773),
 'order': np.int64(1491),
 'gram': np.int64(835),
 'got lt': np.int64(829),
 'day': np.int64(478),
 'good day': np.int64(816),
 'ok': np.int64(1459),
 'plan': np.int64(1564),
 'chennai': np.int64(327),
 'reward': np.int64(1727),
 'hour': np.int64(951),
 'talk': np.int64(2036),
 'time': np.int64(2113),
 'use': np.int64(2271),
 'subscrib': np.int64(1998),
 'gbp': np.int64(758),
 'mnth': np.int64(1301),
 'inc': np.int64(989),
 'hr': np.int64(958),
 'www': np.int64(2455),
 'tv': np.int64(2185),
 'txt call': np.int64(2191),
 'call claim': np.int64(244),
 'time use': np.int64(2121),
 'dear': np.int64(489),
 'read': np.int64(1668),
 'exam': np.int64(622),
 'flirt': np.int64(692),
 'girl': np.int64(780),
 'name': np.int64(1372),
 'age': np.int64(31),
 'eg': np.int64(579),
 'join': np.int64(1037),
 'chat': np.int64(322),
 'name age': np.int64(1373),
 'ago': np.int64(32),
 'fantasi': np.int64(644),
 'back': np.int64(127),
 'sky': np.int64(1872),
 'activ': np.int64(14),
 'play': np.int64(1566),
 'dream': np.int64(554),
 'team': np.int64(2046),
 'start': np.int64(1956),
 'saturday': np.int64(1767),
 'regist': np.int64(1693),
 'opt': np.int64(1485),
 'wot': np.int64(2442),
 'discount': np.int64(526),
 'book': np.int64(189),
 'even': np.int64(609),
 'fill': np.int64(670),
 'worri': np.int64(2438),
 'head': np.int64(893),
 'throat': np.int64(2099),
 'six': np.int64(1867),
 'seem': np.int64(1791),
 'happi': np.int64(883),
 'birthday': np.int64(167),
 'may': np.int64(1250),
 'find': np.int64(674),
 'soon': np.int64(1914),
 'dun': np.int64(563),
 'hard': np.int64(888),
 'happi birthday': np.int64(884),
 'sad': np.int64(1753),
 'part': np.int64(1509),
 'keep': np.int64(1050),
 'touch': np.int64(2153),
 'skype': np.int64(1873),
 'keep touch': np.int64(1051),
 'freemsg': np.int64(724),
 'video': np.int64(2287),
 'pic': np.int64(1546),
 'fone': np.int64(696),
 'send': np.int64(1799),
 'hurri': np.int64(967),
 'im': np.int64(980),
 'bore': np.int64(191),
 'xxx': np.int64(2468),
 'rcvd': np.int64(1662),
 'stop stop': np.int64(1976),
 'princess': np.int64(1621),
 'good morn': np.int64(820),
 'morn princess': np.int64(1337),
 'great day': np.int64(840),
 'free': np.int64(709),
 'st': np.int64(1949),
 'nokia': np.int64(1416),
 'tone': np.int64(2140),
 'mobil': np.int64(1306),
 'txting': np.int64(2204),
 'getz': np.int64(775),
 'uk': np.int64(2210),
 'pobox': np.int64(1585),
 'wq': np.int64(2446),
 'norm': np.int64(1428),
 'free st': np.int64(722),
 'st week': np.int64(1951),
 'week nokia': np.int64(2364),
 'nokia tone': np.int64(1422),
 'tone ur': np.int64(2145),
 'ur mobil': np.int64(2249),
 'everi week': np.int64(614),
 'week txt': np.int64(2366),
 'txt nokia': np.int64(2195),
 'nokia get': np.int64(1417),
 'get txting': np.int64(772),
 'txting tell': np.int64(2205),
 'tell ur': np.int64(2052),
 'ur mate': np.int64(2247),
 'mate www': np.int64(1241),
 'www getz': np.int64(2457),
 'getz co': np.int64(776),
 'co uk': np.int64(355),
 'uk pobox': np.int64(2211),
 'pobox wq': np.int64(1588),
 'wq norm': np.int64(2447),
 'norm tone': np.int64(1429),
 'surf': np.int64(2019),
 'onlin': np.int64(1476),
 'store': np.int64(1980),
 'offer': np.int64(1448),
 'prabha': np.int64(1610),
 'reali': np.int64(1673),
 'frm': np.int64(735),
 'heart': np.int64(896),
 'lol': np.int64(1163),
 'know': np.int64(1066),
 'someon': np.int64(1901),
 'love': np.int64(1184),
 'rose': np.int64(1742),
 'frndship': np.int64(737),
 'give': np.int64(782),
 'amp': np.int64(56),
 'mani': np.int64(1228),
 'miss': np.int64(1294),
 'marri': np.int64(1235),
 'lover': np.int64(1194),
 'send ur': np.int64(1807),
 'miss call': np.int64(1296),
 'call get': np.int64(248),
 'ave': np.int64(111),
 'forgot': np.int64(702),
 'much': np.int64(1358),
 'torch': np.int64(2150),
 'new': np.int64(1396),
 'year': np.int64(2485),
 'eve': np.int64(608),
 'went': np.int64(2379),
 'parti': np.int64(1511),
 'new year': np.int64(1401),
 'teacher': np.int64(2045),
 'bcoz': np.int64(143),
 'teach': np.int64(2044),
 'lesson': np.int64(1122),
 'first': np.int64(683),
 'chikku': np.int64(329),
 'il': np.int64(978),
 'aftr': np.int64(30),
 'min': np.int64(1281),
 'gt min': np.int64(853),
 'right': np.int64(1728),
 'winner': np.int64(2406),
 'special': np.int64(1931),
 'receiv': np.int64(1680),
 'cash': np.int64(300),
 'flight': np.int64(690),
 'speak': np.int64(1928),
 'live': np.int64(1150),
 'oper': np.int64(1481),
 'winner special': np.int64(2407),
 'special select': np.int64(1934),
 'select receiv': np.int64(1794),
 'receiv cash': np.int64(1682),
 'cash holiday': np.int64(305),
 'holiday flight': np.int64(933),
 'flight inc': np.int64(691),
 'inc speak': np.int64(990),
 'speak live': np.int64(1929),
 'live oper': np.int64(1152),
 'oper claim': np.int64(1482),
 'came': np.int64(274),
 'hostel': np.int64(947),
 'plz': np.int64(1577),
 'class': np.int64(346),
 'go sleep': np.int64(801),
 'plz call': np.int64(1578),
 'half': np.int64(876),
 'prepar': np.int64(1614),
 'road': np.int64(1735),
 'bank': np.int64(135),
 'tomorrow': np.int64(2139),
 'tough': np.int64(2154),
 'decis': np.int64(495),
 'us': np.int64(2270),
 'peopl': np.int64(1522),
 'think go': np.int64(2089),
 'number': np.int64(1438),
 'gonna': np.int64(812),
 'pain': np.int64(1503),
 'ass': np.int64(99),
 'rather': np.int64(1661),
 'urgent': np.int64(2262),
 'guarante': np.int64(857),
 'land': np.int64(1076),
 'line': np.int64(1141),
 'valid': np.int64(2280),
 'urgent mobil': np.int64(2264),
 'mobil number': np.int64(1314),
 'number award': np.int64(1439),
 'award prize': np.int64(120),
 'prize guarante': np.int64(1629),
 'guarante call': np.int64(859),
 'call land': np.int64(251),
 'land line': np.int64(1077),
 'line claim': np.int64(1142),
 'claim valid': np.int64(345),
 'valid hr': np.int64(2281),
 'hr ppm': np.int64(959),
 'either': np.int64(582),
 'cd': np.int64(311),
 'gift': np.int64(777),
 'voucher': np.int64(2304),
 'entri': np.int64(600),
 'weekli': np.int64(2369),
 'music': np.int64(1364),
 'tnc': np.int64(2126),
 'ldew': np.int64(1104),
 'com': np.int64(371),
 'win': np.int64(2399),
 'ppmx': np.int64(1608),
 'congratul ur': np.int64(397),
 'ur award': np.int64(2234),
 'award either': np.int64(119),
 'gift voucher': np.int64(779),
 'free entri': np.int64(716),
 'entri weekli': np.int64(601),
 'weekli draw': np.int64(2371),
 'draw txt': np.int64(553),
 'txt music': np.int64(2194),
 'music tnc': np.int64(1366),
 'tnc www': np.int64(2127),
 'www ldew': np.int64(2458),
 'ldew com': np.int64(1105),
 'com win': np.int64(373),
 'win ppmx': np.int64(2402),
 'ppmx age': np.int64(1609),
 'dress': np.int64(555),
 'lay': np.int64(1102),
 'around': np.int64(87),
 'bout': np.int64(197),
 'stuff': np.int64(1991),
 'ard': np.int64(83),
 'like': np.int64(1135),
 'dat': np.int64(475),
 'juz': np.int64(1045),
 'meet': np.int64(1259),
 'mrt': np.int64(1348),
 'haf': np.int64(872),
 'like dat': np.int64(1136),
 'lor juz': np.int64(1176),
 'dun haf': np.int64(565),
 'gave': np.int64(754),
 'hi': np.int64(908),
 'wat': np.int64(2336),
 'de': np.int64(486),
 'dem': np.int64(507),
 'wat make': np.int64(2338),
 'yep': np.int64(2486),
 'hous': np.int64(952),
 'sunday': np.int64(2009),
 'problem': np.int64(1635),
 'listen': np.int64(1148),
 'voic': np.int64(2301),
 'call later': np.int64(253),
 'better': np.int64(160),
 'made': np.int64(1214),
 'friday': np.int64(728),
 'pig': np.int64(1550),
 'yesterday': np.int64(2489),
 'least': np.int64(1109),
 'kind': np.int64(1061),
 'yup': np.int64(2498),
 'comin': np.int64(380),
 'guess': np.int64(867),
 'pub': np.int64(1639),
 'whatev': np.int64(2384),
 'minut': np.int64(1290),
 'goin': np.int64(810),
 'somethin': np.int64(1907),
 'unless': np.int64(2219),
 'meetin': np.int64(1262),
 'dinner': np.int64(523),
 'haha': np.int64(873),
 'ti': np.int64(2105),
 'guy': np.int64(869),
 'sell': np.int64(1796),
 'sinc': np.int64(1856),
 'break': np.int64(207),
 'fuck': np.int64(740),
 'without': np.int64(2416),
 'til': np.int64(2111),
 'late': np.int64(1089),
 'tonight': np.int64(2146),
 'know one': np.int64(1067),
 'hope': np.int64(940),
 'night': np.int64(1409),
 'hope good': np.int64(942),
 'puriti': np.int64(1641),
 'friendship': np.int64(732),
 'two': np.int64(2188),
 'smile': np.int64(1887),
 'forward': np.int64(704),
 'messag': np.int64(1272),
 'evng': np.int64(619),
 'puriti friendship': np.int64(1642),
 'friendship two': np.int64(734),
 'two smile': np.int64(2189),
 'smile read': np.int64(1888),
 'read forward': np.int64(1670),
 'forward messag': np.int64(705),
 'messag smile': np.int64(1274),
 'smile see': np.int64(1889),
 'see name': np.int64(1788),
 'name gud': np.int64(1374),
 'gud evng': np.int64(863),
 'yr': np.int64(2495),
 'servic': np.int64(1816),
 'repres': np.int64(1714),
 'pm': np.int64(1579),
 'cost': np.int64(419),
 'guarante cash': np.int64(860),
 'cash prize': np.int64(306),
 'call custom': np.int64(245),
 'custom servic': np.int64(460),
 'servic repres': np.int64(1819),
 'repres pm': np.int64(1715),
 'pm cost': np.int64(1580),
 'sorri': np.int64(1917),
 'troubl': np.int64(2170),
 'dad': np.int64(468),
 'big': np.int64(162),
 'small': np.int64(1885),
 'sun': np.int64(2008),
 'thanx': np.int64(2081),
 'rite': np.int64(1734),
 'go home': np.int64(794),
 'lor dun': np.int64(1175),
 'feel like': np.int64(661),
 'leav': np.int64(1110),
 'shit': np.int64(1834),
 'yet': np.int64(2490),
 'coffe': np.int64(359),
 'run': np.int64(1751),
 'believ': np.int64(155),
 'mood': np.int64(1330),
 'cant': np.int64(285),
 'drive': np.int64(557),
 'brother': np.int64(214),
 'bath': np.int64(139),
 'fine': np.int64(679),
 'msg': np.int64(1350),
 'crazi': np.int64(435),
 'rington': np.int64(1731),
 'free msg': np.int64(718),
 'free repli': np.int64(720),
 'hmmm': np.int64(923),
 'imagin': np.int64(981),
 'feet': np.int64(662),
 'help': np.int64(902),
 'readi': np.int64(1671),
 'date': np.int64(476),
 'sure': np.int64(2017),
 'come home': np.int64(377),
 'get readi': np.int64(770),
 'cash award': np.int64(302),
 'card': np.int64(291),
 'travel': np.int64(2161),
 'gone': np.int64(811),
 'buck': np.int64(221),
 'dont think': np.int64(543),
 'think need': np.int64(2091),
 'gt buck': np.int64(848),
 'pick': np.int64(1547),
 'cant pick': np.int64(287),
 'pick phone': np.int64(1548),
 'phone right': np.int64(1544),
 'right pl': np.int64(1729),
 'pl send': np.int64(1562),
 'send messag': np.int64(1804),
 'oop': np.int64(1479),
 'check': np.int64(325),
 'mind': np.int64(1287),
 'price': np.int64(1619),
 'oz': np.int64(1497),
 'let': np.int64(1123),
 'let know': np.int64(1125),
 'download': np.int64(549),
 'type': np.int64(2207),
 'googl': np.int64(825),
 'search': np.int64(1779),
 'mayb': np.int64(1251),
 'told': np.int64(2137),
 'direct': np.int64(525),
 'link': np.int64(1145),
 'car': np.int64(290),
 'bid': np.int64(161),
 'arrang': np.int64(89),
 'ship': np.int64(1832),
 'cut': np.int64(461),
 'take': np.int64(2031),
 'care': np.int64(292),
 'rest': np.int64(1721),
 'self': np.int64(1795),
 'dnt': np.int64(531),
 'get back': np.int64(764),
 'take care': np.int64(2032),
 'sexi': np.int64(1824),
 'nd': np.int64(1381),
 'attempt': np.int64(103),
 'contract': np.int64(408),
 'nd attempt': np.int64(1382),
 'guarante award': np.int64(858),
 'claim ur': np.int64(344),
 'award call': np.int64(117),
 'call free': np.int64(246),
 'hungri': np.int64(965),
 'almost': np.int64(48),
 'ya': np.int64(2471),
 'happi day': np.int64(885),
 'babe love': np.int64(125),
 'love ya': np.int64(1193),
 'hello': np.int64(901),
 'cake': np.int64(236),
 'that': np.int64(2082),
 'fall': np.int64(640),
 'forc': np.int64(699),
 'hold': np.int64(927),
 'bslvyl': np.int64(215),
 'fall love': np.int64(641),
 'hmm': np.int64(922),
 'obvious': np.int64(1447),
 'hot': np.int64(948),
 'kinda': np.int64(1062),
 'fun': np.int64(744),
 'tho': np.int64(2096),
 'trip': np.int64(2169),
 'india': np.int64(995),
 'bring': np.int64(211),
 'light': np.int64(1132),
 'everyon': np.int64(617),
 'project': np.int64(1637),
 'lucki': np.int64(1205),
 'bye': np.int64(232),
 'abiola': np.int64(1),
 'nokia phone': np.int64(1421),
 'done': np.int64(539),
 'ten': np.int64(2053),
 'jay': np.int64(1027),
 'cool': np.int64(414),
 'sometim': np.int64(1908),
 'slow': np.int64(1879),
 'that cool': np.int64(2083),
 'awesom': np.int64(123),
 'rememb': np.int64(1699),
 'last': np.int64(1084),
 'somebodi': np.int64(1900),
 'high': np.int64(913),
 'first time': np.int64(684),
 'suppos': np.int64(2015),
 'discuss': np.int64(528),
 'abt': np.int64(3),
 'thought': np.int64(2098),
 'afternoon': np.int64(29),
 'moment': np.int64(1324),
 'spend': np.int64(1937),
 'togeth': np.int64(2136),
 'cri': np.int64(440),
 'happen': np.int64(882),
 'everyth': np.int64(618),
 'els': np.int64(583),
 'push': np.int64(1643),
 'often': np.int64(1454),
 'colleg': np.int64(367),
 'alright': np.int64(52),
 'make sure': np.int64(1221),
 'horni': np.int64(945),
 'turn': np.int64(2184),
 'cancel': np.int64(282),
 'send stop': np.int64(1806),
 'dunno': np.int64(567),
 'insid': np.int64(1001),
 'ate': np.int64(101),
 'gal': np.int64(749),
 'laugh': np.int64(1100),
 'address': np.int64(18),
 'bit': np.int64(171),
 'alway': np.int64(55),
 'pleas call': np.int64(1572),
 'wnt': np.int64(2424),
 'wid': np.int64(2390),
 'allow': np.int64(47),
 'anytim': np.int64(70),
 'network': np.int64(1392),
 'inclus': np.int64(993),
 'per': np.int64(1523),
 'want new': np.int64(2331),
 'new video': np.int64(1400),
 'video phone': np.int64(2289),
 'phone anytim': np.int64(1539),
 'anytim network': np.int64(71),
 'network min': np.int64(1393),
 'per week': np.int64(1529),
 'week free': np.int64(2363),
 'call repli': np.int64(259),
 'ring': np.int64(1730),
 'scream': np.int64(1777),
 'hair': np.int64(875),
 'wana': np.int64(2325),
 'shop': np.int64(1835),
 'paid': np.int64(1502),
 'ok take': np.int64(1467),
 'place': np.int64(1563),
 'custom place': np.int64(459),
 'end': np.int64(588),
 'wanna': np.int64(2326),
 'could': np.int64(424),
 'roommat': np.int64(1741),
 'look': np.int64(1170),
 'like hour': np.int64(1137),
 'key': np.int64(1056),
 'put': np.int64(1645),
 'someth like': np.int64(1906),
 'tm': np.int64(2124),
 'charg': np.int64(318),
 'shortli': np.int64(1838),
 'last night': np.int64(1085),
 'howz': np.int64(955),
 'person': np.int64(1532),
 'stori': np.int64(1982),
 'person stori': np.int64(1535),
 'good even': np.int64(817),
 'real': np.int64(1672),
 'valentin': np.int64(2278),
 'never': np.int64(1395),
 'decim': np.int64(493),
 'feb': np.int64(655),
 'april': np.int64(80),
 'season': np.int64(1780),
 'lt decim': np.int64(1199),
 'decim gt': np.int64(494),
 'blank': np.int64(177),
 'hand': np.int64(880),
 'rain': np.int64(1654),
 'doctor': np.int64(534),
 'cancer': np.int64(283),
 'fat': np.int64(651),
 'cup': np.int64(452),
 'mom': np.int64(1323),
 'want know': np.int64(2330),
 'fact': np.int64(638),
 'build': np.int64(224),
 'consid': np.int64(399),
 'smoke': np.int64(1891),
 'hit': np.int64(917),
 'avail': np.int64(110),
 'drop': np.int64(559),
 'door': np.int64(546),
 'step': np.int64(1963),
 'eatin': np.int64(576),
 'show': np.int64(1839),
 'huh': np.int64(963),
 'liao': np.int64(1127),
 'nice': np.int64(1406),
 'ahead': np.int64(35),
 'daddi': np.int64(469),
 'fetch': np.int64(665),
 'mah': np.int64(1215),
 'wat time': np.int64(2339),
 'ju': np.int64(1044),
 'said': np.int64(1759),
 'respect': np.int64(1718),
 'ref': np.int64(1688),
 'arriv': np.int64(91),
 'thank rington': np.int64(2080),
 'rington order': np.int64(1733),
 'number mobil': np.int64(1441),
 'mobil charg': np.int64(1308),
 'charg tone': np.int64(320),
 'tone arriv': np.int64(2141),
 'arriv pleas': np.int64(92),
 'wa': np.int64(2310),
 'anyway': np.int64(72),
 'tt': np.int64(2180),
 'weight': np.int64(2372),
 'long': np.int64(1166),
 'accid': np.int64(7),
 'via': np.int64(2286),
 'lot': np.int64(1180),
 'speak soon': np.int64(1930),
 'way': np.int64(2346),
 'sooner': np.int64(1915),
 'sub': np.int64(1997),
 'man': np.int64(1223),
 'appreci': np.int64(78),
 'safe': np.int64(1758),
 'day send': np.int64(484),
 'bb': np.int64(141),
 'longer': np.int64(1169),

In [21]:
from sklearn.naive_bayes import MultinomialNB

In [22]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [23]:
y_pred=spam_detect_model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score,classification_report

In [25]:
# 77 - 95
accuracy_score(y_test,y_pred)

0.9901345291479821

In [26]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.93      0.96       137
           1       0.99      1.00      0.99       978

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

### Creating The TF-IDF Model

In [27]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train=tv.fit_transform(X_train).toarray()
X_test=tv.transform(X_test).toarray()

In [30]:
X_train[:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
# tv.vocabulary_

In [33]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [34]:
#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [35]:
score=accuracy_score(y_test,y_pred)
print(score)

0.97847533632287

In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.83      0.99      0.90       114
           1       1.00      0.98      0.99      1001

    accuracy                           0.98      1115
   macro avg       0.91      0.98      0.95      1115
weighted avg       0.98      0.98      0.98      1115