In [1]:
# !pip install gensim

### 1. Import Libraries

In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

### 2. To Download and Save gensim "word2vec" Model

In [2]:
# import gensim.downloader as api

# # Load the model
# wv = api.load('word2vec-google-news-300')

# # Save the model to the local machine
# wv.save("word2vec-google-news-300.model")
# print("Model saved successfully!")

#### Load the Model

In [3]:
from gensim.models import KeyedVectors

# Load the saved model
wv = KeyedVectors.load("word2vec-google-news-300.model")
print("Model loaded successfully!")

# Example usage
vec_king = wv['king']

Model loaded successfully!

In [4]:
vec_king[:5]

array([ 0.12597656,  0.02978516,  0.00860596,  0.13964844, -0.02563477],
      dtype=float32)

#### Dataset Load

In [5]:
import pandas as pd
messages=pd.read_csv('Data/SMSSpamCollection.txt',
                    sep='\t',names=["label","message"])

In [6]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [7]:
messages.isnull().sum()

label      0
message    0
dtype: int64

In [9]:
messages.shape

(5572, 2)

In [8]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [9]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [11]:
corpus[:10]

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co free on']

In [13]:
# [[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

In [14]:
corpus[:10]

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile update co free on']

### 3. Data Preprocess

In [15]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [16]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [17]:
words[:5]

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though']]

#### Train Word2vec from scratch

In [18]:
## Lets train Word2vec from scratch
model=gensim.models.Word2Vec(words)

In [19]:
## To Get All the Vocabulary
len(model.wv.index_to_key)

1721

In [20]:
model.wv.index_to_key[:10]

['to', 'you', 'the', 'and', 'it', 'in', 'is', 'me', 'my', 'for']

In [22]:
messages.shape

(5572, 2)

In [21]:
model.corpus_count

5569

In [28]:
model.epochs

5

In [23]:
model.wv.similar_by_word('good')

[('my', 0.998694121837616),
 ('all', 0.9985784888267517),
 ('morning', 0.9984778761863708),
 ('about', 0.998471736907959),
 ('hey', 0.9984624981880188),
 ('great', 0.9984227418899536),
 ('happy', 0.9984222650527954),
 ('dear', 0.9984212517738342),
 ('where', 0.9984158277511597),
 ('day', 0.9983440637588501)]

In [24]:
model.wv['good'].shape

(100,)

In [25]:
words[:1]

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat']]

---

### Word2vec --> Model

---

5569

In [27]:
def avg_word2vec(doc):
    vectors = [model.wv[w] for w in doc if w in model.wv.key_to_index]
    if len(vectors) == 0:
        return np.zeros(model.vector_size, dtype=np.float32)
    return np.mean(vectors, axis=0).astype(np.float32)

In [29]:
# !pip install tqdm

In [28]:
from tqdm import tqdm

In [29]:
words[:1]

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat']]

In [30]:
#apply for the entire sentences
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|███████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 23759.64it/s]

In [31]:
len(X)

5569

In [32]:
X[:1]

[array([-1.76959977e-01,  2.61677176e-01,  6.56860322e-02,  1.07378207e-01,
         6.95795566e-02, -5.35292923e-01,  1.35344297e-01,  4.95224029e-01,
        -2.84329146e-01, -8.75626802e-02, -1.78196833e-01, -4.26886439e-01,
        -1.60698015e-02,  8.91906172e-02,  2.03275397e-01, -1.41190544e-01,
         1.41097277e-01, -2.80458510e-01, -5.12780957e-02, -5.96055329e-01,
         2.03695804e-01,  2.31634647e-01,  8.57525021e-02, -1.97031528e-01,
        -8.21043104e-02,  3.21459062e-02, -3.96873862e-01, -2.09394321e-01,
        -2.43180275e-01,  2.76599322e-02,  2.95562625e-01,  3.01587256e-03,
         1.05661221e-01, -2.18052223e-01, -1.36000305e-01,  4.22995001e-01,
         1.47994217e-02, -1.54859275e-01, -1.37633771e-01, -3.70043367e-01,
         1.63959920e-01, -2.84118146e-01, -1.77156299e-01,  4.84315231e-02,
         2.67189890e-01,  3.45796230e-04, -2.17058390e-01, -6.65080398e-02,
         1.46750614e-01,  1.55039743e-01,  1.71040758e-01, -2.12788641e-01,
        -6.48519620e-02,  7.21393824e-02, -1.06090106e-01,  1.77618936e-01,
         1.86377063e-01,  8.58349726e-02, -2.98906028e-01,  1.38947353e-01,
        -2.22258233e-02,  1.38996691e-01, -6.10857159e-02, -1.31420717e-01,
        -3.47192377e-01,  2.65863508e-01,  7.99043030e-02,  1.84715092e-01,
        -3.53393257e-01,  3.13352406e-01, -2.11556911e-01,  1.21921875e-01,
         3.13186347e-01, -1.82778135e-01,  2.94161171e-01,  1.27013057e-01,
         2.58775465e-02, -1.38824835e-01, -1.64121181e-01,  4.25221287e-02,
        -1.25403881e-01, -1.27278911e-02, -2.23692700e-01,  4.12147403e-01,
        -1.41477644e-01,  2.48299558e-02,  7.52469301e-02,  2.08883584e-01,
         3.79389107e-01, -1.22405393e-02,  2.70227253e-01,  1.33563384e-01,
         5.03916256e-02,  1.50912195e-01,  3.58810753e-01,  3.32929552e-01,
         1.04194246e-01, -1.96142673e-01,  1.42992318e-01, -7.48168603e-02],
       dtype=float32)]

#### Independent Features

In [33]:
X_new = np.vstack([avg_word2vec(doc) for doc in words])
X_new[:1]

array([[-1.76959977e-01,  2.61677176e-01,  6.56860322e-02,
         1.07378207e-01,  6.95795566e-02, -5.35292923e-01,
         1.35344297e-01,  4.95224029e-01, -2.84329146e-01,
        -8.75626802e-02, -1.78196833e-01, -4.26886439e-01,
        -1.60698015e-02,  8.91906172e-02,  2.03275397e-01,
        -1.41190544e-01,  1.41097277e-01, -2.80458510e-01,
        -5.12780957e-02, -5.96055329e-01,  2.03695804e-01,
         2.31634647e-01,  8.57525021e-02, -1.97031528e-01,
        -8.21043104e-02,  3.21459062e-02, -3.96873862e-01,
        -2.09394321e-01, -2.43180275e-01,  2.76599322e-02,
         2.95562625e-01,  3.01587256e-03,  1.05661221e-01,
        -2.18052223e-01, -1.36000305e-01,  4.22995001e-01,
         1.47994217e-02, -1.54859275e-01, -1.37633771e-01,
        -3.70043367e-01,  1.63959920e-01, -2.84118146e-01,
        -1.77156299e-01,  4.84315231e-02,  2.67189890e-01,
         3.45796230e-04, -2.17058390e-01, -6.65080398e-02,
         1.46750614e-01,  1.55039743e-01,  1.71040758e-01,
        -2.12788641e-01, -6.48519620e-02,  7.21393824e-02,
        -1.06090106e-01,  1.77618936e-01,  1.86377063e-01,
         8.58349726e-02, -2.98906028e-01,  1.38947353e-01,
        -2.22258233e-02,  1.38996691e-01, -6.10857159e-02,
        -1.31420717e-01, -3.47192377e-01,  2.65863508e-01,
         7.99043030e-02,  1.84715092e-01, -3.53393257e-01,
         3.13352406e-01, -2.11556911e-01,  1.21921875e-01,
         3.13186347e-01, -1.82778135e-01,  2.94161171e-01,
         1.27013057e-01,  2.58775465e-02, -1.38824835e-01,
        -1.64121181e-01,  4.25221287e-02, -1.25403881e-01,
        -1.27278911e-02, -2.23692700e-01,  4.12147403e-01,
        -1.41477644e-01,  2.48299558e-02,  7.52469301e-02,
         2.08883584e-01,  3.79389107e-01, -1.22405393e-02,
         2.70227253e-01,  1.33563384e-01,  5.03916256e-02,
         1.50912195e-01,  3.58810753e-01,  3.32929552e-01,
         1.04194246e-01, -1.96142673e-01,  1.42992318e-01,
        -7.48168603e-02]], dtype=float32)

In [34]:
messages.shape

(5572, 2)

In [35]:
len(X)

5569

In [37]:
X_new.shape

(5569, 100)

In [38]:
X_new[0].shape

(100,)

In [40]:
X_new[:2]

array([[-1.76959977e-01,  2.61677176e-01,  6.56860322e-02,
         1.07378207e-01,  6.95795566e-02, -5.35292923e-01,
         1.35344297e-01,  4.95224029e-01, -2.84329146e-01,
        -8.75626802e-02, -1.78196833e-01, -4.26886439e-01,
        -1.60698015e-02,  8.91906172e-02,  2.03275397e-01,
        -1.41190544e-01,  1.41097277e-01, -2.80458510e-01,
        -5.12780957e-02, -5.96055329e-01,  2.03695804e-01,
         2.31634647e-01,  8.57525021e-02, -1.97031528e-01,
        -8.21043104e-02,  3.21459062e-02, -3.96873862e-01,
        -2.09394321e-01, -2.43180275e-01,  2.76599322e-02,
         2.95562625e-01,  3.01587256e-03,  1.05661221e-01,
        -2.18052223e-01, -1.36000305e-01,  4.22995001e-01,
         1.47994217e-02, -1.54859275e-01, -1.37633771e-01,
        -3.70043367e-01,  1.63959920e-01, -2.84118146e-01,
        -1.77156299e-01,  4.84315231e-02,  2.67189890e-01,
         3.45796230e-04, -2.17058390e-01, -6.65080398e-02,
         1.46750614e-01,  1.55039743e-01,  1.71040758e-01,
        -2.12788641e-01, -6.48519620e-02,  7.21393824e-02,
        -1.06090106e-01,  1.77618936e-01,  1.86377063e-01,
         8.58349726e-02, -2.98906028e-01,  1.38947353e-01,
        -2.22258233e-02,  1.38996691e-01, -6.10857159e-02,
        -1.31420717e-01, -3.47192377e-01,  2.65863508e-01,
         7.99043030e-02,  1.84715092e-01, -3.53393257e-01,
         3.13352406e-01, -2.11556911e-01,  1.21921875e-01,
         3.13186347e-01, -1.82778135e-01,  2.94161171e-01,
         1.27013057e-01,  2.58775465e-02, -1.38824835e-01,
        -1.64121181e-01,  4.25221287e-02, -1.25403881e-01,
        -1.27278911e-02, -2.23692700e-01,  4.12147403e-01,
        -1.41477644e-01,  2.48299558e-02,  7.52469301e-02,
         2.08883584e-01,  3.79389107e-01, -1.22405393e-02,
         2.70227253e-01,  1.33563384e-01,  5.03916256e-02,
         1.50912195e-01,  3.58810753e-01,  3.32929552e-01,
         1.04194246e-01, -1.96142673e-01,  1.42992318e-01,
        -7.48168603e-02],
       [-1.56425327e-01,  2.30484441e-01,  5.47105297e-02,
         9.70989391e-02,  5.81630841e-02, -4.80839729e-01,
         1.11573644e-01,  4.43653345e-01, -2.44977325e-01,
        -6.50134832e-02, -1.58423245e-01, -3.73921096e-01,
        -1.81478299e-02,  6.97411224e-02,  1.81736529e-01,
        -1.33403286e-01,  1.30093306e-01, -2.52981365e-01,
        -4.30534557e-02, -5.21380246e-01,  1.81944817e-01,
         2.00172126e-01,  7.21579343e-02, -1.74262226e-01,
        -7.04236999e-02,  2.32523493e-02, -3.53437334e-01,
        -1.91419393e-01, -2.14430869e-01,  2.16518082e-02,
         2.61014998e-01,  3.56979994e-03,  9.33858082e-02,
        -1.86363578e-01, -1.17845729e-01,  3.67239743e-01,
         1.73541368e-03, -1.37802094e-01, -1.17565580e-01,
        -3.34548891e-01,  1.48018718e-01, -2.54244596e-01,
        -1.60154685e-01,  4.28853109e-02,  2.29975566e-01,
        -8.36635067e-04, -2.03505665e-01, -5.97741380e-02,
         1.32179409e-01,  1.43300951e-01,  1.46914020e-01,
        -1.80784702e-01, -5.90584092e-02,  7.32928291e-02,
        -9.72414762e-02,  1.67639539e-01,  1.67759418e-01,
         7.74082765e-02, -2.63788909e-01,  1.27128124e-01,
        -1.35265607e-02,  1.26025483e-01, -5.24312407e-02,
        -1.07498825e-01, -3.08183014e-01,  2.34852180e-01,
         6.59057349e-02,  1.64332718e-01, -3.11467379e-01,
         2.85520852e-01, -1.83849096e-01,  1.06285661e-01,
         2.77002007e-01, -1.64966047e-01,  2.61742890e-01,
         1.03761375e-01,  1.73284356e-02, -1.20695844e-01,
        -1.44878775e-01,  2.89123580e-02, -1.04067549e-01,
        -6.04285300e-03, -1.97347805e-01,  3.64421397e-01,
        -1.29426166e-01,  2.42278557e-02,  7.12966993e-02,
         1.86930150e-01,  3.30253690e-01, -1.43857803e-02,
         2.39260465e-01,  1.15331739e-01,  4.18426730e-02,
         1.30982742e-01,  3.11736465e-01,  2.85381258e-01,
         8.85209739e-02, -1.82879686e-01,  1.20307237e-01,
        -6.42304942e-02]], dtype=float32)

#### Dependent Features

In [44]:
messages.head(5)

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [45]:
## Output Features
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['label'],dtype=np.int32)
y=y.iloc[:,0].values

In [46]:
y

array([1, 1, 0, ..., 1, 1, 1], shape=(5569,), dtype=int32)

In [47]:
y.shape

(5569,)

In [48]:
df = pd.DataFrame(
    X_new,
    columns=[f"w2v_{i+1}" for i in range(X_new.shape[1])]
)

In [49]:
df.head()

,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,...,w2v_91,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99,w2v_100
0,-0.176960,0.261677,0.065686,0.107378,0.069580,-0.535293,0.135344,0.495224,-0.284329,-0.087563,...,0.270227,0.133563,0.050392,0.150912,0.358811,0.332930,0.104194,-0.196143,0.142992,-0.074817
1,-0.156425,0.230484,0.054711,0.097099,0.058163,-0.480840,0.111574,0.443653,-0.244977,-0.065013,...,0.239260,0.115332,0.041843,0.130983,0.311736,0.285381,0.088521,-0.182880,0.120307,-0.064230
2,-0.168438,0.276042,0.090694,0.136178,0.082060,-0.591949,0.137827,0.501963,-0.302348,-0.098873,...,0.267517,0.141710,0.038446,0.159102,0.369245,0.328841,0.083209,-0.232665,0.173731,-0.084974
3,-0.243601,0.350190,0.080471,0.142544,0.089024,-0.707355,0.177468,0.670924,-0.383819,-0.107872,...,0.365432,0.174683,0.062773,0.204522,0.466702,0.445976,0.139404,-0.271238,0.181367,-0.087577
4,-0.207147,0.295898,0.074522,0.118098,0.089268,-0.599278,0.146162,0.570309,-0.324817,-0.098036,...,0.316269,0.144629,0.055936,0.171712,0.395593,0.379003,0.114831,-0.232267,0.154596,-0.088316

In [50]:
df['Output']=y

In [51]:
df.head()

,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,...,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99,w2v_100,Output
0,-0.176960,0.261677,0.065686,0.107378,0.069580,-0.535293,0.135344,0.495224,-0.284329,-0.087563,...,0.133563,0.050392,0.150912,0.358811,0.332930,0.104194,-0.196143,0.142992,-0.074817,1
1,-0.156425,0.230484,0.054711,0.097099,0.058163,-0.480840,0.111574,0.443653,-0.244977,-0.065013,...,0.115332,0.041843,0.130983,0.311736,0.285381,0.088521,-0.182880,0.120307,-0.064230,1
2,-0.168438,0.276042,0.090694,0.136178,0.082060,-0.591949,0.137827,0.501963,-0.302348,-0.098873,...,0.141710,0.038446,0.159102,0.369245,0.328841,0.083209,-0.232665,0.173731,-0.084974,0
3,-0.243601,0.350190,0.080471,0.142544,0.089024,-0.707355,0.177468,0.670924,-0.383819,-0.107872,...,0.174683,0.062773,0.204522,0.466702,0.445976,0.139404,-0.271238,0.181367,-0.087577,1
4,-0.207147,0.295898,0.074522,0.118098,0.089268,-0.599278,0.146162,0.570309,-0.324817,-0.098036,...,0.144629,0.055936,0.171712,0.395593,0.379003,0.114831,-0.232267,0.154596,-0.088316,1

In [52]:
df.isnull().sum().sum()

np.int64(0)

In [53]:
df.dropna(inplace=True)

In [69]:
df.isnull().sum().sum()

w2v_0     0
w2v_1     0
w2v_2     0
w2v_3     0
w2v_4     0
         ..
w2v_96    0
w2v_97    0
w2v_98    0
w2v_99    0
Output    0
Length: 101, dtype: int64

In [54]:
## Independent Feature
X=df.drop('Output',axis=1)
X.head()

,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,...,w2v_91,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99,w2v_100
0,-0.176960,0.261677,0.065686,0.107378,0.069580,-0.535293,0.135344,0.495224,-0.284329,-0.087563,...,0.270227,0.133563,0.050392,0.150912,0.358811,0.332930,0.104194,-0.196143,0.142992,-0.074817
1,-0.156425,0.230484,0.054711,0.097099,0.058163,-0.480840,0.111574,0.443653,-0.244977,-0.065013,...,0.239260,0.115332,0.041843,0.130983,0.311736,0.285381,0.088521,-0.182880,0.120307,-0.064230
2,-0.168438,0.276042,0.090694,0.136178,0.082060,-0.591949,0.137827,0.501963,-0.302348,-0.098873,...,0.267517,0.141710,0.038446,0.159102,0.369245,0.328841,0.083209,-0.232665,0.173731,-0.084974
3,-0.243601,0.350190,0.080471,0.142544,0.089024,-0.707355,0.177468,0.670924,-0.383819,-0.107872,...,0.365432,0.174683,0.062773,0.204522,0.466702,0.445976,0.139404,-0.271238,0.181367,-0.087577
4,-0.207147,0.295898,0.074522,0.118098,0.089268,-0.599278,0.146162,0.570309,-0.324817,-0.098036,...,0.316269,0.144629,0.055936,0.171712,0.395593,0.379003,0.114831,-0.232267,0.154596,-0.088316

In [56]:
y=df['Output']

In [57]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [58]:
X_train.head()

,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,...,w2v_91,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99,w2v_100
2396,-0.196333,0.266225,0.060693,0.092972,0.086253,-0.520141,0.120691,0.509367,-0.283866,-0.092207,...,0.291836,0.123174,0.055371,0.130147,0.335828,0.342509,0.104403,-0.199283,0.124663,-0.070918
4784,-0.170893,0.296700,0.100320,0.142909,0.083174,-0.622187,0.146913,0.520741,-0.306924,-0.113765,...,0.284374,0.149542,0.027077,0.164298,0.400362,0.329074,0.082027,-0.245785,0.184766,-0.089220
2876,-0.172809,0.239919,0.054394,0.096558,0.066885,-0.488100,0.115143,0.467415,-0.261812,-0.076703,...,0.253648,0.123899,0.046433,0.137393,0.327239,0.303849,0.096522,-0.182030,0.130006,-0.070243
1732,-0.198846,0.279305,0.054538,0.108066,0.082196,-0.572187,0.135220,0.550668,-0.312113,-0.102082,...,0.318880,0.135644,0.061651,0.159098,0.378020,0.370595,0.117594,-0.210580,0.145005,-0.078228
3741,-0.227025,0.311085,0.079400,0.120375,0.096238,-0.627464,0.152207,0.602006,-0.340297,-0.101127,...,0.340122,0.155447,0.060576,0.179274,0.411923,0.403578,0.120353,-0.238983,0.166783,-0.078986

In [96]:
y_train

770     1
1828    1
3501    1
4781    1
3025    1
       ..
3514    1
4747    1
5267    1
1864    1
2323    1
Name: Output, Length: 4455, dtype: int32

In [59]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state=42)

In [60]:
classifier.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [61]:
y_pred = classifier.predict(X_test)

In [62]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9631956912028725

### yes > no (data imbalance)

In [65]:
messages['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

In [66]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.84      0.86       155
           1       0.97      0.98      0.98       959

    accuracy                           0.96      1114
   macro avg       0.93      0.91      0.92      1114
weighted avg       0.96      0.96      0.96      1114

In [67]:
df

,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,...,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99,w2v_100,Output
0,-0.176960,0.261677,0.065686,0.107378,0.069580,-0.535293,0.135344,0.495224,-0.284329,-0.087563,...,0.133563,0.050392,0.150912,0.358811,0.332930,0.104194,-0.196143,0.142992,-0.074817,1
1,-0.156425,0.230484,0.054711,0.097099,0.058163,-0.480840,0.111574,0.443653,-0.244977,-0.065013,...,0.115332,0.041843,0.130983,0.311736,0.285381,0.088521,-0.182880,0.120307,-0.064230,1
2,-0.168438,0.276042,0.090694,0.136178,0.082060,-0.591949,0.137827,0.501963,-0.302348,-0.098873,...,0.141710,0.038446,0.159102,0.369245,0.328841,0.083209,-0.232665,0.173731,-0.084974,0
3,-0.243601,0.350190,0.080471,0.142544,0.089024,-0.707355,0.177468,0.670924,-0.383819,-0.107872,...,0.174683,0.062773,0.204522,0.466702,0.445976,0.139404,-0.271238,0.181367,-0.087577,1
4,-0.207147,0.295898,0.074522,0.118098,0.089268,-0.599278,0.146162,0.570309,-0.324817,-0.098036,...,0.144629,0.055936,0.171712,0.395593,0.379003,0.114831,-0.232267,0.154596,-0.088316,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5564,-0.197914,0.318062,0.103267,0.143581,0.092842,-0.659972,0.167451,0.573035,-0.339848,-0.119597,...,0.158970,0.048975,0.170894,0.433596,0.379334,0.104905,-0.252367,0.193880,-0.085887,0
5565,-0.218836,0.304059,0.083151,0.133671,0.102400,-0.646564,0.153088,0.599793,-0.350252,-0.100394,...,0.161652,0.047689,0.183033,0.424892,0.398986,0.112212,-0.254334,0.172775,-0.089140,1
5566,-0.239761,0.355215,0.083191,0.138380,0.086888,-0.705949,0.176743,0.660600,-0.374872,-0.116877,...,0.179979,0.068991,0.201617,0.475912,0.445576,0.143161,-0.250265,0.193309,-0.099791,1
5567,-0.215204,0.317735,0.080856,0.131825,0.087764,-0.645789,0.156044,0.595992,-0.342099,-0.107575,...,0.159164,0.064994,0.180020,0.430422,0.400040,0.118622,-0.239807,0.174567,-0.094050,1
5568,-0.238772,0.335664,0.077094,0.137430,0.094402,-0.686176,0.166635,0.646642,-0.371925,-0.115271,...,0.162790,0.071938,0.186596,0.454289,0.429056,0.131230,-0.256572,0.188447,-0.089012,1

In [68]:
import random
from gensim.utils import simple_preprocess

def random_pred():
    idx = random.randrange(len(corpus))
    sent = corpus[idx]

    x = avg_word2vec(simple_preprocess(sent)).reshape(1, -1)
    pred = classifier.predict(x)[0]

    print("Index:", idx)
    print("Sentence:", sent)
    print("Prediction:", pred)

random_pred()

Index: 3028
Sentence: you still at the game
Prediction: 1

C:\ProgramData\anaconda3\envs\tf_nlp\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [69]:
messages.iloc[4287,:].values[1]

"Congrats. That's great. I wanted to tell you not to tell me your score cos it might make me relax. But its motivating me so thanks for sharing"

In [70]:
corpus[4287]

'congrats that s great i wanted to tell you not to tell me your score co it might make me relax but it motivating me so thanks for sharing'