| Strategy | Logic | Best For |
| :--- | :--- | :--- |
| **Grid Search** | Exhaustive search through every possible combination. | Very small search spaces. |
| **Random Search** | Samples randomly from the distribution. | Surprisingly effective for high-dimensional spaces. |
| **Bayesian (TPE/GP)** | Uses past results to predict which parameters will perform better. | Expensive-to-train models (Deep Learning). |

Optuna Paper - https://arxiv.org/pdf/1907.10902

Bayesian Optimization (TPE) Paper - https://arxiv.org/pdf/2304.11127

In [1]:
# !pip install optuna

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [4]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.median(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [7]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-05-06 15:56:49,344] A new study created in memory with name: no-name-e66349a8-9d0d-4a15-9f55-b20e629b5318
[I 2026-05-06 15:56:50,059] Trial 0 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 137, 'max_depth': 3}. Best is trial 0 with value: 0.7579143389199254.
[I 2026-05-06 15:56:50,737] Trial 1 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 138, 'max_depth': 7}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:50,997] Trial 2 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 60, 'max_depth': 11}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:51,674] Trial 3 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 198, 'max_depth': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:51,906] Trial 4 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 82, 'max_depth': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:52,241] Trial 5 finished with value: 0.756052141527002 and parameters: {'n_estimators': 127, 'max_depth': 3}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:52,877] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 183, 'max_depth': 11}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:53,130] Trial 7 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 53, 'max_depth': 18}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:53,404] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 60, 'max_depth': 10}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:53,864] Trial 9 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 104, 'max_depth': 4}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:54,381] Trial 10 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 152, 'max_depth': 16}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:54,744] Trial 11 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 101, 'max_depth': 13}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:55,324] Trial 12 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 161, 'max_depth': 8}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:55,698] Trial 13 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 106, 'max_depth': 13}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:56,063] Trial 14 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 79, 'max_depth': 9}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:56,711] Trial 15 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 156, 'max_depth': 15}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-05-06 15:56:57,211] Trial 16 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 122, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:56:57,703] Trial 17 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 138, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:56:58,325] Trial 18 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 170, 'max_depth': 5}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:56:58,764] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 119, 'max_depth': 8}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:56:59,131] Trial 20 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 124, 'max_depth': 9}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:56:59,652] Trial 21 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:56:59,620] Trial 22 finished with value: 0.756052141527002 and parameters: {'n_estimators': 115, 'max_depth': 6}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:00,121] Trial 23 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 138, 'max_depth': 5}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:00,765] Trial 24 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 172, 'max_depth': 8}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:01,095] Trial 25 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 92, 'max_depth': 12}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:03,579] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 144, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:03,991] Trial 27 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 130, 'max_depth': 9}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:04,377] Trial 28 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 113, 'max_depth': 4}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:04,753] Trial 29 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 134, 'max_depth': 3}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:05,363] Trial 30 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 152, 'max_depth': 10}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:05,599] Trial 31 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 71, 'max_depth': 11}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:06,282] Trial 32 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 196, 'max_depth': 20}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:06,578] Trial 33 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 95, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:06,898] Trial 34 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 93, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:07,224] Trial 35 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 90, 'max_depth': 5}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:07,584] Trial 36 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 91, 'max_depth': 6}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:07,832] Trial 37 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 76, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:08,249] Trial 38 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 111, 'max_depth': 10}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:08,583] Trial 39 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 4}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:08,835] Trial 40 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 69, 'max_depth': 6}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:09,220] Trial 41 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 123, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:09,616] Trial 42 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 125, 'max_depth': 8}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:09,879] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 85, 'max_depth': 5}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:10,224] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 9}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:10,666] Trial 45 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 122, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:11,043] Trial 46 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 109, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:11,437] Trial 47 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 123, 'max_depth': 3}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:11,807] Trial 48 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 116, 'max_depth': 8}. Best is trial 16 with value: 0.7802607076350094.
[I 2026-05-06 15:57:12,184] Trial 49 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 103, 'max_depth': 10}. Best is trial 16 with value: 0.7802607076350094.

In [8]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350094
Best hyperparameters: {'n_estimators': 122, 'max_depth': 7}

In [9]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

## Samplers in Optuna

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [11]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-05-06 15:57:12,377] A new study created in memory with name: no-name-9f1a3b06-a002-4d9e-8e75-75cb24227f25
[I 2026-05-06 15:57:12,936] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 184, 'max_depth': 4}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-05-06 15:57:13,497] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 188, 'max_depth': 17}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:13,924] Trial 2 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 137, 'max_depth': 13}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:14,259] Trial 3 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 107, 'max_depth': 15}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:14,605] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 99, 'max_depth': 11}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:15,075] Trial 5 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 141, 'max_depth': 13}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:15,374] Trial 6 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 89, 'max_depth': 15}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:15,990] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 177, 'max_depth': 15}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:16,778] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 152, 'max_depth': 8}. Best is trial 1 with value: 0.7672253258845437.
[I 2026-05-06 15:57:17,350] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 139, 'max_depth': 9}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:17,988] Trial 10 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 177, 'max_depth': 3}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:18,366] Trial 11 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 113, 'max_depth': 3}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:18,878] Trial 12 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 151, 'max_depth': 6}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:19,050] Trial 13 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 56, 'max_depth': 9}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:19,494] Trial 14 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 146, 'max_depth': 4}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:20,155] Trial 15 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 197, 'max_depth': 19}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:20,364] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 58, 'max_depth': 5}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:20,811] Trial 17 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 136, 'max_depth': 6}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:21,047] Trial 18 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 65, 'max_depth': 15}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:21,237] Trial 19 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 51, 'max_depth': 12}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:21,570] Trial 20 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 88, 'max_depth': 11}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:21,934] Trial 21 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 106, 'max_depth': 12}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:22,457] Trial 22 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 164, 'max_depth': 4}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:22,844] Trial 23 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 117, 'max_depth': 12}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:23,313] Trial 24 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 160, 'max_depth': 6}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:23,618] Trial 25 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 101, 'max_depth': 6}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:24,077] Trial 26 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 141, 'max_depth': 8}. Best is trial 9 with value: 0.7709497206703911.
[I 2026-05-06 15:57:24,364] Trial 27 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 99, 'max_depth': 7}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:24,594] Trial 28 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 78, 'max_depth': 10}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:24,808] Trial 29 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 68, 'max_depth': 3}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:25,096] Trial 30 finished with value: 0.7504655493482307 and parameters: {'n_estimators': 86, 'max_depth': 15}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:25,255] Trial 31 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 54, 'max_depth': 3}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:25,816] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 180, 'max_depth': 16}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:26,133] Trial 33 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 113, 'max_depth': 3}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:26,322] Trial 34 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 61, 'max_depth': 17}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:26,664] Trial 35 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 99, 'max_depth': 15}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:26,857] Trial 36 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 63, 'max_depth': 3}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:27,452] Trial 37 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 199, 'max_depth': 6}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:27,820] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 117, 'max_depth': 11}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:28,432] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 197, 'max_depth': 4}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:28,935] Trial 40 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 159, 'max_depth': 16}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:29,648] Trial 41 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 188, 'max_depth': 18}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:29,978] Trial 42 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 99, 'max_depth': 7}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:30,331] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 114, 'max_depth': 10}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:30,564] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 71, 'max_depth': 5}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:30,891] Trial 45 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 110, 'max_depth': 14}. Best is trial 27 with value: 0.7746741154562384.
[I 2026-05-06 15:57:31,177] Trial 46 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 91, 'max_depth': 7}. Best is trial 46 with value: 0.7802607076350094.
[I 2026-05-06 15:57:31,506] Trial 47 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 110, 'max_depth': 20}. Best is trial 46 with value: 0.7802607076350094.
[I 2026-05-06 15:57:31,695] Trial 48 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 52, 'max_depth': 8}. Best is trial 46 with value: 0.7802607076350094.
[I 2026-05-06 15:57:31,893] Trial 49 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 199, 'max_depth': 11}. Best is trial 46 with value: 0.7802607076350094.

In [12]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350094
Best hyperparameters: {'n_estimators': 91, 'max_depth': 7}

In [13]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.75

In [14]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [15]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-05-06 15:57:32,030] A new study created in memory with name: no-name-8e6f251b-9ddb-4661-86df-8a3f98f393ab
[I 2026-05-06 15:57:32,367] Trial 0 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-05-06 15:57:32,860] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-05-06 15:57:33,035] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-05-06 15:57:33,363] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-05-06 15:57:33,670] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-05-06 15:57:33,830] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:34,312] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:34,758] Trial 7 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:35,302] Trial 8 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:35,972] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:36,596] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:37,293] Trial 11 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:37,884] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:38,058] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:38,386] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-05-06 15:57:38,573] Trial 15 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 5 with value: 0.7746741154562384.

In [16]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 10}

In [17]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

## Optuna Visualizations

In [18]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [19]:
# 1. Optimization History
fig = optuna.visualization.plot_optimization_history(study)
fig.write_html("optimization_history.html")

In [20]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).write_html("Parallel Coordinates Plot.html")

In [21]:
# 3. Slice Plot
plot_slice(study).write_html("Slice Plot.html")

In [22]:
# 4. Contour Plot
plot_contour(study).write_html("Contour Plot.html")

In [23]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [24]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [25]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [26]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-05-06 15:57:41,499] A new study created in memory with name: no-name-828df93a-24a0-4a12-a2ac-4d2c457381f4
[I 2026-05-06 15:57:43,359] Trial 0 finished with value: 0.7690875232774674 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 256, 'learning_rate': 0.016682240878155473, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:44,503] Trial 1 finished with value: 0.7057728119180634 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 112, 'learning_rate': 0.021456716878045304, 'max_depth': 19, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:46,949] Trial 2 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 202, 'learning_rate': 0.02636382206842232, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:47,603] Trial 3 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 198, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:48,503] Trial 4 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 121, 'learning_rate': 0.010006586974755921, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 4}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:49,410] Trial 5 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 99, 'learning_rate': 0.1684434646614419, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:49,981] Trial 6 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 67, 'learning_rate': 0.014699445021631168, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 3}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:50,665] Trial 7 finished with value: 0.7579143389199255 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 144, 'learning_rate': 0.09231196247236198, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:52,565] Trial 8 finished with value: 0.7560521415270017 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 277, 'learning_rate': 0.05961834837111897, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:53,114] Trial 9 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 76, 'learning_rate': 0.15829401947237862, 'max_depth': 16, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:53,143] Trial 10 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.8318939270332116, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:53,923] Trial 11 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 228, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:54,731] Trial 12 finished with value: 0.7560521415270017 and parameters: {'classifier': 'RandomForest', 'n_estimators': 263, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:55,386] Trial 13 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 233, 'max_depth': 14, 'min_samples_split': 10, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-05-06 15:57:55,697] Trial 14 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 98.3707807915681, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:55,873] Trial 15 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 67.40598065117325, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,086] Trial 16 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 82.58769761374236, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,293] Trial 17 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 96.01215258145187, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,339] Trial 18 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 14.0590284796089, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,364] Trial 19 finished with value: 0.7057728119180634 and parameters: {'classifier': 'SVM', 'C': 8.839848273919944, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,387] Trial 20 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.15578128138740532, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,626] Trial 21 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 98.50128544312108, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,738] Trial 22 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 40.325503614431646, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:56,834] Trial 23 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 28.273536704696067, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,045] Trial 24 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 83.73431941760121, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,076] Trial 25 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 2.8293805700207737, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,112] Trial 26 finished with value: 0.6983240223463687 and parameters: {'classifier': 'SVM', 'C': 25.968276612111502, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,142] Trial 27 finished with value: 0.702048417132216 and parameters: {'classifier': 'SVM', 'C': 6.184268585064355, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,184] Trial 28 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 43.65252111002904, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,319] Trial 29 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 43.11942444218163, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,347] Trial 30 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 2.3526082496382803, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,574] Trial 31 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 88.70554871965646, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,793] Trial 32 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 90.53947418436256, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,859] Trial 33 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 19.84147899915784, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:57,987] Trial 34 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 52.28887282063392, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:58,123] Trial 35 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 53.01547206314881, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:58,853] Trial 36 finished with value: 0.7430167597765364 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:58,878] Trial 37 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 14.81071946985444, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:58,972] Trial 38 finished with value: 0.6852886405959032 and parameters: {'classifier': 'SVM', 'C': 58.24383617739442, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:58,996] Trial 39 finished with value: 0.7057728119180634 and parameters: {'classifier': 'SVM', 'C': 99.55828588437504, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:59,373] Trial 40 finished with value: 0.750465549348231 and parameters: {'classifier': 'RandomForest', 'n_estimators': 158, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:59,414] Trial 41 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 10.56507136343646, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:57:59,484] Trial 42 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 29.67136255390933, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:00,367] Trial 43 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 179, 'learning_rate': 0.2840854471903797, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 4}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:00,535] Trial 44 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 59.22808286084245, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:00,596] Trial 45 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 18.275079773008482, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:01,568] Trial 46 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 141, 'learning_rate': 0.040203637666103215, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:01,609] Trial 47 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 4.968346518381829, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:01,851] Trial 48 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 61, 'max_depth': 16, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:01,878] Trial 49 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 0.6493638672459057, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:02,485] Trial 50 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 91, 'learning_rate': 0.06757315510636386, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 2}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:02,679] Trial 51 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 95.14370331791946, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:02,839] Trial 52 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 64.27687094619436, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:02,934] Trial 53 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 32.4400894251976, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:03,097] Trial 54 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 62.54879081460218, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:03,117] Trial 55 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 1.6660574011018268, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:03,347] Trial 56 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 99.29565033603475, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:03,381] Trial 57 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 37.9548161641416, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:03,615] Trial 58 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 68.07001721196467, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:04,532] Trial 59 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 14 with value: 0.7746741154562384.
[I 2026-05-06 15:58:04,550] Trial 60 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.12946429535115375, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 60 with value: 0.7821229050279329.
[I 2026-05-06 15:58:04,571] Trial 61 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.1689995823636689, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 60 with value: 0.7821229050279329.
[I 2026-05-06 15:58:04,591] Trial 62 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.1448953990543626, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 62 with value: 0.7839851024208566.
[I 2026-05-06 15:58:04,610] Trial 63 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.11001193121165713, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:04,631] Trial 64 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.1150871595518482, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:04,651] Trial 65 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.10024629743636199, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:04,672] Trial 66 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.12034550705392151, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:04,695] Trial 67 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.10050347650375764, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,418] Trial 68 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 187, 'learning_rate': 0.03166139994929309, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,437] Trial 69 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.22053063130450562, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,458] Trial 70 finished with value: 0.7802607076350093 and parameters: {'classifier': 'SVM', 'C': 0.24021247297583698, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,505] Trial 71 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.10144350888159911, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,535] Trial 72 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.10079848806720866, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,557] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10296403971707042, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,579] Trial 74 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10464930095692583, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,609] Trial 75 finished with value: 0.756052141527002 and parameters: {'classifier': 'SVM', 'C': 0.35350759238293683, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,629] Trial 76 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.17582330509906677, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,647] Trial 77 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.10119994387301474, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:05,670] Trial 78 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 0.3487375683028141, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:06,279] Trial 79 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 228, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 63 with value: 0.7858472998137803.
[I 2026-05-06 15:58:06,298] Trial 80 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.1354221908604844, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 63 with value: 0.7858472998137803.

In [27]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.11001193121165713, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7858472998137803

In [28]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.769088,2026-05-06 15:57:41.500462,2026-05-06 15:57:43.359536,0 days 00:00:01.859074,NaN,NaN,GradientBoosting,NaN,NaN,0.016682,17.0,7.0,6.0,256.0,COMPLETE
1,1,0.705773,2026-05-06 15:57:43.360674,2026-05-06 15:57:44.503525,0 days 00:00:01.142851,NaN,NaN,GradientBoosting,NaN,NaN,0.021457,19.0,1.0,3.0,112.0,COMPLETE
2,2,0.729981,2026-05-06 15:57:44.504323,2026-05-06 15:57:46.949061,0 days 00:00:02.444738,NaN,NaN,GradientBoosting,NaN,NaN,0.026364,10.0,2.0,4.0,202.0,COMPLETE
3,3,0.759777,2026-05-06 15:57:46.949861,2026-05-06 15:57:47.603003,0 days 00:00:00.653142,NaN,True,RandomForest,NaN,NaN,NaN,11.0,7.0,7.0,198.0,COMPLETE
4,4,0.739292,2026-05-06 15:57:47.604045,2026-05-06 15:57:48.503205,0 days 00:00:00.899160,NaN,NaN,GradientBoosting,NaN,NaN,0.010007,8.0,4.0,2.0,121.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.782123,2026-05-06 15:58:07.040344,2026-05-06 15:58:07.060678,0 days 00:00:00.020334,0.136420,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.767225,2026-05-06 15:58:07.061496,2026-05-06 15:58:07.088362,0 days 00:00:00.026866,0.119526,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.780261,2026-05-06 15:58:07.089247,2026-05-06 15:58:07.107840,0 days 00:00:00.018593,0.278319,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.757914,2026-05-06 15:58:07.109005,2026-05-06 15:58:07.544501,0 days 00:00:00.435496,NaN,True,RandomForest,NaN,NaN,NaN,17.0,9.0,3.0,129.0,COMPLETE
99,99,0.744879,2026-05-06 15:58:07.545421,2026-05-06 15:58:07.569482,0 days 00:00:00.024061,0.452311,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [29]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 76
GradientBoosting    14
RandomForest        10
Name: count, dtype: int64

In [30]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.743815
RandomForest        0.761080
SVM                 0.768058
Name: value, dtype: float64

In [31]:
# 1. Optimization History
plot_optimization_history(study).write_html('data2/Optimization History.html')

In [32]:
# 3. Slice Plot
plot_slice(study).write_html('data2/Slice Plot.html')

In [33]:
# 5. Hyperparameter Importance
plot_param_importances(study).write_html('data2/Hyperparameter Importance.html')

In [36]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-05-06 16:08:38,399] A new study created in memory with name: no-name-c8937418-23dc-4557-aba2-c3a030d84eb5

[0]	train-mlogloss:0.99754	eval-mlogloss:0.99411
[1]	train-mlogloss:0.78284	eval-mlogloss:0.76826
[2]	train-mlogloss:0.63049	eval-mlogloss:0.60956
[3]	train-mlogloss:0.54405	eval-mlogloss:0.51168
[4]	train-mlogloss:0.47797	eval-mlogloss:0.43481
[5]	train-mlogloss:0.40372	eval-mlogloss:0.35277
[6]	train-mlogloss:0.36165	eval-mlogloss:0.30710
[7]	train-mlogloss:0.34349	eval-mlogloss:0.29028
[8]	train-mlogloss:0.30744	eval-mlogloss:0.24905
[9]	train-mlogloss:0.28055	eval-mlogloss:0.22117
[10]	train-mlogloss:0.26885	eval-mlogloss:0.20788
[11]	train-mlogloss:0.26039	eval-mlogloss:0.19926
[12]	train-mlogloss:0.25829	eval-mlogloss:0.19630
[13]	train-mlogloss:0.25171	eval-mlogloss:0.18853
[14]	train-mlogloss:0.25133	eval-mlogloss:0.18701
[15]	train-mlogloss:0.25081	eval-mlogloss:0.18626
[16]	train-mlogloss:0.25037	eval-mlogloss:0.18377
[17]	train-mlogloss:0.25013	eval-mlogloss:0.18306
[18]	train-mlogloss:0.24997	eval-mlogloss:0.18369
[19]	train-mlogloss:0.24946	eval-mlogloss:0.18379
[20]	train-mlogloss:0.24927	eval-mlogloss:0.18306
[21]	train-mlogloss:0.24910	eval-mlogloss:0.18292
[22]	train-mlogloss:0.24248	eval-mlogloss:0.17302
[23]	train-mlogloss:0.24243	eval-mlogloss:0.17281
[24]	train-mlogloss:0.24119	eval-mlogloss:0.17197
[25]	train-mlogloss:0.23997	eval-mlogloss:0.17120
[26]	train-mlogloss:0.23987	eval-mlogloss:0.17086
[27]	train-mlogloss:0.23914	eval-mlogloss:0.17032
[28]	train-mlogloss:0.23913	eval-mlogloss:0.17055
[29]	train-mlogloss:0.23912	eval-mlogloss:0.17057
[30]	train-mlogloss:0.23914	eval-mlogloss:0.17076
[31]	train-mlogloss:0.23893	eval-mlogloss:0.16984
[32]	train-mlogloss:0.23891	eval-mlogloss:0.16975
[33]	train-mlogloss:0.23870	eval-mlogloss:0.16748
[34]	train-mlogloss:0.23857	eval-mlogloss:0.16774
[35]	train-mlogloss:0.23806	eval-mlogloss:0.16731
[36]	train-mlogloss:0.23739	eval-mlogloss:0.16688
[37]	train-mlogloss:0.23670	eval-mlogloss:0.16642
[38]	train-mlogloss:0.23651	eval-mlogloss:0.16592
[39]	train-mlogloss:0.23605	eval-mlogloss:0.16593
[40]	train-mlogloss:0.23598	eval-mlogloss:0.16526
[41]	train-mlogloss:0.23520	eval-mlogloss:0.16492
[42]	train-mlogloss:0.23508	eval-mlogloss:0.16430
[43]	train-mlogloss:0.23482	eval-mlogloss:0.16425
[44]	train-mlogloss:0.23483	eval-mlogloss:0.16417
[45]	train-mlogloss:0.23389	eval-mlogloss:0.16332
[46]	train-mlogloss:0.23390	eval-mlogloss:0.16294
[47]	train-mlogloss:0.23388	eval-mlogloss:0.16294
[48]	train-mlogloss:0.23380	eval-mlogloss:0.16313
[49]	train-mlogloss:0.23370	eval-mlogloss:0.16339
[50]	train-mlogloss:0.23372	eval-mlogloss:0.16334
[51]	train-mlogloss:0.23375	eval-mlogloss:0.16334
[52]	train-mlogloss:0.23345	eval-mlogloss:0.16307
[53]	train-mlogloss:0.23334	eval-mlogloss:0.16295
[54]	train-mlogloss:0.23316	eval-mlogloss:0.16252
[55]	train-mlogloss:0.23313	eval-mlogloss:0.16234
[56]	train-mlogloss:0.23304	eval-mlogloss:0.16234
[57]	train-mlogloss:0.23311	eval-mlogloss:0.16226
[58]	train-mlogloss:0.23318	eval-mlogloss:0.16268
[59]	train-mlogloss:0.23228	eval-mlogloss:0.16185
[60]	train-mlogloss:0.23179	eval-mlogloss:0.16183
[61]	train-mlogloss:0.23179	eval-mlogloss:0.16195
[62]	train-mlogloss:0.23143	eval-mlogloss:0.16185
[63]	train-mlogloss:0.23130	eval-mlogloss:0.16004
[64]	train-mlogloss:0.23129	eval-mlogloss:0.15968
[65]	train-mlogloss:0.23130	eval-mlogloss:0.15980
[66]	train-mlogloss:0.23120	eval-mlogloss:0.16006
[67]	train-mlogloss:0.23121	eval-mlogloss:0.16020
[68]	train-mlogloss:0.23043	eval-mlogloss:0.15978
[69]	train-mlogloss:0.23036	eval-mlogloss:0.15969
[70]	train-mlogloss:0.23035	eval-mlogloss:0.15952
[71]	train-mlogloss:0.23029	eval-mlogloss:0.15992
[72]	train-mlogloss:0.23029	eval-mlogloss:0.15984
[73]	train-mlogloss:0.23025	eval-mlogloss:0.15975
[74]	train-mlogloss:0.23023	eval-mlogloss:0.15974
[75]	train-mlogloss:0.23023	eval-mlogloss:0.15985
[76]	train-mlogloss:0.23027	eval-mlogloss:0.15955
[77]	train-mlogloss:0.23024	eval-mlogloss:0.15975
[78]	train-mlogloss:0.23031	eval-mlogloss:0.15996
[79]	train-mlogloss:0.23029	eval-mlogloss:0.16000
[80]	train-mlogloss:0.23010	eval-mlogloss:0.16005
[81]	train-mlogloss:0.23011	eval-mlogloss:0.16008
[82]	train-mlogloss:0.22986	eval-mlogloss:0.15958
[83]	train-mlogloss:0.22987	eval-mlogloss:0.15952
[84]	train-mlogloss:0.22983	eval-mlogloss:0.15932
[85]	train-mlogloss:0.22974	eval-mlogloss:0.15909
[86]	train-mlogloss:0.22965	eval-mlogloss:0.15870
[87]	train-mlogloss:0.22965	eval-mlogloss:0.15865
[88]	train-mlogloss:0.22915	eval-mlogloss:0.15787
[89]	train-mlogloss:0.22866	eval-mlogloss:0.15776
[90]	train-mlogloss:0.22831	eval-mlogloss:0.15757
[91]	train-mlogloss:0.22833	eval-mlogloss:0.15755
[92]	train-mlogloss:0.22794	eval-mlogloss:0.15759
[93]	train-mlogloss:0.22793	eval-mlogloss:0.15732
[94]	train-mlogloss:0.22795	eval-mlogloss:0.15748
[95]	train-mlogloss:0.22793	eval-mlogloss:0.15733
[96]	train-mlogloss:0.22792	eval-mlogloss:0.15706
[97]	train-mlogloss:0.22789	eval-mlogloss:0.15707
[98]	train-mlogloss:0.22791	eval-mlogloss:0.15709
[99]	train-mlogloss:0.22784	eval-mlogloss:0.15619
[100]	train-mlogloss:0.22783	eval-mlogloss:0.15629
[101]	train-mlogloss:0.22743	eval-mlogloss:0.15617
[102]	train-mlogloss:0.22742	eval-mlogloss:0.15614
[103]	train-mlogloss:0.22732	eval-mlogloss:0.15586
[104]	train-mlogloss:0.22727	eval-mlogloss:0.15576
[105]	train-mlogloss:0.22726	eval-mlogloss:0.15556
[106]	train-mlogloss:0.22694	eval-mlogloss:0.15539
[107]	train-mlogloss:0.22696	eval-mlogloss:0.15559
[108]	train-mlogloss:0.22671	eval-mlogloss:0.15538
[109]	train-mlogloss:0.22670	eval-mlogloss:0.15540
[110]	train-mlogloss:0.22650	eval-mlogloss:0.15532
[111]	train-mlogloss:0.22652	eval-mlogloss:0.15525
[112]	train-mlogloss:0.22641	eval-mlogloss:0.15530
[113]	train-mlogloss:0.22646	eval-mlogloss:0.15553
[114]	train-mlogloss:0.22646	eval-mlogloss:0.15544
[115]	train-mlogloss:0.22644	eval-mlogloss:0.15536
[116]	train-mlogloss:0.22632	eval-mlogloss:0.15528
[117]	train-mlogloss:0.22631	eval-mlogloss:0.15497
[118]	train-mlogloss:0.22630	eval-mlogloss:0.15507
[119]	train-mlogloss:0.22630	eval-mlogloss:0.15507
[120]	train-mlogloss:0.22630	eval-mlogloss:0.15505
[121]	train-mlogloss:0.22624	eval-mlogloss:0.15517
[122]	train-mlogloss:0.22625	eval-mlogloss:0.15533
[123]	train-mlogloss:0.22628	eval-mlogloss:0.15545
[124]	train-mlogloss:0.22621	eval-mlogloss:0.15528
[125]	train-mlogloss:0.22620	eval-mlogloss:0.15522
[126]	train-mlogloss:0.22618	eval-mlogloss:0.15519
[127]	train-mlogloss:0.22581	eval-mlogloss:0.15474
[128]	train-mlogloss:0.22583	eval-mlogloss:0.15511
[129]	train-mlogloss:0.22556	eval-mlogloss:0.15485
[130]	train-mlogloss:0.22556	eval-mlogloss:0.15456
[131]	train-mlogloss:0.22556	eval-mlogloss:0.15472
[132]	train-mlogloss:0.22554	eval-mlogloss:0.15439
[133]	train-mlogloss:0.22555	eval-mlogloss:0.15436
[134]	train-mlogloss:0.22554	eval-mlogloss:0.15454
[135]	train-mlogloss:0.22555	eval-mlogloss:0.15449
[136]	train-mlogloss:0.22558	eval-mlogloss:0.15460
[137]	train-mlogloss:0.22527	eval-mlogloss:0.15443
[138]	train-mlogloss:0.22528	eval-mlogloss:0.15451
[139]	train-mlogloss:0.22515	eval-mlogloss:0.15437
[140]	train-mlogloss:0.22514	eval-mlogloss:0.15452
[141]	train-mlogloss:0.22506	eval-mlogloss:0.15451
[142]	train-mlogloss:0.22514	eval-mlogloss:0.15455
[143]	train-mlogloss:0.22512	eval-mlogloss:0.15446
[144]	train-mlogloss:0.22511	eval-mlogloss:0.15472
[145]	train-mlogloss:0.22512	eval-mlogloss:0.15472
[146]	train-mlogloss:0.22502	eval-mlogloss:0.15440
[147]	train-mlogloss:0.22495	eval-mlogloss:0.15406
[148]	train-mlogloss:0.22494	eval-mlogloss:0.15409
[149]	train-mlogloss:0.22498	eval-mlogloss:0.15425
[150]	train-mlogloss:0.22496	eval-mlogloss:0.15404
[151]	train-mlogloss:0.22495	eval-mlogloss:0.15372
[152]	train-mlogloss:0.22464	eval-mlogloss:0.15362
[153]	train-mlogloss:0.22461	eval-mlogloss:0.15381
[154]	train-mlogloss:0.22459	eval-mlogloss:0.15351
[155]	train-mlogloss:0.22458	eval-mlogloss:0.15348
[156]	train-mlogloss:0.22459	eval-mlogloss:0.15347
[157]	train-mlogloss:0.22458	eval-mlogloss:0.15349
[158]	train-mlogloss:0.22457	eval-mlogloss:0.15356
[159]	train-mlogloss:0.22431	eval-mlogloss:0.15342
[160]	train-mlogloss:0.22432	eval-mlogloss:0.15352
[161]	train-mlogloss:0.22428	eval-mlogloss:0.15350
[162]	train-mlogloss:0.22424	eval-mlogloss:0.15354
[163]	train-mlogloss:0.22423	eval-mlogloss:0.15361
[164]	train-mlogloss:0.22433	eval-mlogloss:0.15376
[165]	train-mlogloss:0.22416	eval-mlogloss:0.15341
[166]	train-mlogloss:0.22393	eval-mlogloss:0.15325
[167]	train-mlogloss:0.22389	eval-mlogloss:0.15305
[168]	train-mlogloss:0.22389	eval-mlogloss:0.15295
[169]	train-mlogloss:0.22370	eval-mlogloss:0.15263
[170]	train-mlogloss:0.22367	eval-mlogloss:0.15260
[171]	train-mlogloss:0.22357	eval-mlogloss:0.15279
[172]	train-mlogloss:0.22359	eval-mlogloss:0.15273
[173]	train-mlogloss:0.22356	eval-mlogloss:0.15270
[174]	train-mlogloss:0.22358	eval-mlogloss:0.15287
[175]	train-mlogloss:0.22366	eval-mlogloss:0.15280
[176]	train-mlogloss:0.22365	eval-mlogloss:0.15242
[177]	train-mlogloss:0.22364	eval-mlogloss:0.15198
[178]	train-mlogloss:0.22363	eval-mlogloss:0.15206
[179]	train-mlogloss:0.22363	eval-mlogloss:0.15207
[180]	train-mlogloss:0.22364	eval-mlogloss:0.15199
[181]	train-mlogloss:0.22361	eval-mlogloss:0.15200
[182]	train-mlogloss:0.22350	eval-mlogloss:0.15185
[183]	train-mlogloss:0.22350	eval-mlogloss:0.15202
[184]	train-mlogloss:0.22349	eval-mlogloss:0.15144
[185]	train-mlogloss:0.22337	eval-mlogloss:0.15163
[186]	train-mlogloss:0.22326	eval-mlogloss:0.15154
[187]	train-mlogloss:0.22315	eval-mlogloss:0.15174
[188]	train-mlogloss:0.22316	eval-mlogloss:0.15173
[189]	train-mlogloss:0.22318	eval-mlogloss:0.15176
[190]	train-mlogloss:0.22316	eval-mlogloss:0.15198
[191]	train-mlogloss:0.22315	eval-mlogloss:0.15195
[192]	train-mlogloss:0.22319	eval-mlogloss:0.15187
[193]	train-mlogloss:0.22318	eval-mlogloss:0.15178
[194]	train-mlogloss:0.22322	eval-mlogloss:0.15192
[195]	train-mlogloss:0.22318	eval-mlogloss:0.15198
[196]	train-mlogloss:0.22314	eval-mlogloss:0.15206
[197]	train-mlogloss:0.22306	eval-mlogloss:0.15211
[198]	train-mlogloss:0.22301	eval-mlogloss:0.15199
[199]	train-mlogloss:0.22302	eval-mlogloss:0.15207
[200]	train-mlogloss:0.22303	eval-mlogloss:0.15194
[201]	train-mlogloss:0.22306	eval-mlogloss:0.15071
[202]	train-mlogloss:0.22305	eval-mlogloss:0.15069
[203]	train-mlogloss:0.22300	eval-mlogloss:0.15098
[204]	train-mlogloss:0.22289	eval-mlogloss:0.15101
[205]	train-mlogloss:0.22285	eval-mlogloss:0.15111
[206]	train-mlogloss:0.22285	eval-mlogloss:0.15133
[207]	train-mlogloss:0.22276	eval-mlogloss:0.15119
[208]	train-mlogloss:0.22276	eval-mlogloss:0.15149
[209]	train-mlogloss:0.22273	eval-mlogloss:0.15117
[210]	train-mlogloss:0.22278	eval-mlogloss:0.15005
[211]	train-mlogloss:0.22276	eval-mlogloss:0.15000
[212]	train-mlogloss:0.22261	eval-mlogloss:0.14994
[213]	train-mlogloss:0.22255	eval-mlogloss:0.15000
[214]	train-mlogloss:0.22254	eval-mlogloss:0.15000
[215]	train-mlogloss:0.22254	eval-mlogloss:0.15000
[216]	train-mlogloss:0.22253	eval-mlogloss:0.15018
[217]	train-mlogloss:0.22253	eval-mlogloss:0.15011
[218]	train-mlogloss:0.22254	eval-mlogloss:0.15008
[219]	train-mlogloss:0.22255	eval-mlogloss:0.14995
[220]	train-mlogloss:0.22254	eval-mlogloss:0.14991
[221]	train-mlogloss:0.22251	eval-mlogloss:0.14997
[222]	train-mlogloss:0.22248	eval-mlogloss:0.15011
[223]	train-mlogloss:0.22249	eval-mlogloss:0.14995
[224]	train-mlogloss:0.22246	eval-mlogloss:0.15011
[225]	train-mlogloss:0.22247	eval-mlogloss:0.15024
[226]	train-mlogloss:0.22249	eval-mlogloss:0.15008
[227]	train-mlogloss:0.22248	eval-mlogloss:0.15009
[228]	train-mlogloss:0.22251	eval-mlogloss:0.15003
[229]	train-mlogloss:0.22233	eval-mlogloss:0.14995
[230]	train-mlogloss:0.22233	eval-mlogloss:0.15000
[231]	train-mlogloss:0.22233	eval-mlogloss:0.15012
[232]	train-mlogloss:0.22227	eval-mlogloss:0.15015
[233]	train-mlogloss:0.22220	eval-mlogloss:0.15000
[234]	train-mlogloss:0.22222	eval-mlogloss:0.15024
[235]	train-mlogloss:0.22221	eval-mlogloss:0.15018
[236]	train-mlogloss:0.22224	eval-mlogloss:0.15035
[237]	train-mlogloss:0.22184	eval-mlogloss:0.15000
[238]	train-mlogloss:0.22185	eval-mlogloss:0.15007
[239]	train-mlogloss:0.22184	eval-mlogloss:0.14991
[240]	train-mlogloss:0.22185	eval-mlogloss:0.15009
[241]	train-mlogloss:0.22184	eval-mlogloss:0.14996
[242]	train-mlogloss:0.22184	eval-mlogloss:0.15005
[243]	train-mlogloss:0.22183	eval-mlogloss:0.14997
[244]	train-mlogloss:0.22183	eval-mlogloss:0.15000
[245]	train-mlogloss:0.22181	eval-mlogloss:0.14980
[246]	train-mlogloss:0.22187	eval-mlogloss:0.14957
[247]	train-mlogloss:0.22178	eval-mlogloss:0.14958
[248]	train-mlogloss:0.22178	eval-mlogloss:0.14959
[249]	train-mlogloss:0.22179	eval-mlogloss:0.14956
[250]	train-mlogloss:0.22175	eval-mlogloss:0.14951
[251]	train-mlogloss:0.22174	eval-mlogloss:0.14970
[252]	train-mlogloss:0.22172	eval-mlogloss:0.14953
[253]	train-mlogloss:0.22172	eval-mlogloss:0.14947
[254]	train-mlogloss:0.22172	eval-mlogloss:0.14953
[255]	train-mlogloss:0.22172	eval-mlogloss:0.14943
[256]	train-mlogloss:0.22170	eval-mlogloss:0.14935
[257]	train-mlogloss:0.22171	eval-mlogloss:0.14926
[258]	train-mlogloss:0.22162	eval-mlogloss:0.14937
[259]	train-mlogloss:0.22163	eval-mlogloss:0.14939
[260]	train-mlogloss:0.22163	eval-mlogloss:0.14949
[261]	train-mlogloss:0.22167	eval-mlogloss:0.14981
[262]	train-mlogloss:0.22169	eval-mlogloss:0.15004
[263]	train-mlogloss:0.22154	eval-mlogloss:0.15012
[264]	train-mlogloss:0.22147	eval-mlogloss:0.14998
[265]	train-mlogloss:0.22155	eval-mlogloss:0.14977
[266]	train-mlogloss:0.22159	eval-mlogloss:0.14965
[267]	train-mlogloss:0.22148	eval-mlogloss:0.14941
[268]	train-mlogloss:0.22139	eval-mlogloss:0.14962
[269]	train-mlogloss:0.22141	eval-mlogloss:0.14978
[270]	train-mlogloss:0.22139	eval-mlogloss:0.14961
[271]	train-mlogloss:0.22137	eval-mlogloss:0.14944
[272]	train-mlogloss:0.22137	eval-mlogloss:0.14945
[273]	train-mlogloss:0.22135	eval-mlogloss:0.14929
[274]	train-mlogloss:0.22137	eval-mlogloss:0.14943
[275]	train-mlogloss:0.22143	eval-mlogloss:0.14968
[276]	train-mlogloss:0.22145	eval-mlogloss:0.14974
[277]	train-mlogloss:0.22143	eval-mlogloss:0.14968
[278]	train-mlogloss:0.22138	eval-mlogloss:0.14940
[279]	train-mlogloss:0.22137	eval-mlogloss:0.14947
[280]	train-mlogloss:0.22134	eval-mlogloss:0.14913
[281]	train-mlogloss:0.22134	eval-mlogloss:0.14927
[282]	train-mlogloss:0.22133	eval-mlogloss:0.14929
[283]	train-mlogloss:0.22133	eval-mlogloss:0.14927
[284]	train-mlogloss:0.22134	eval-mlogloss:0.14944
[285]	train-mlogloss:0.22134	eval-mlogloss:0.14954
[286]	train-mlogloss:0.22135	eval-mlogloss:0.14960
[287]	train-mlogloss:0.22134	eval-mlogloss:0.14948
[288]	train-mlogloss:0.22136	eval-mlogloss:0.14966
[289]	train-mlogloss:0.22133	eval-mlogloss:0.14945
[290]	train-mlogloss:0.22135	eval-mlogloss:0.14936
[291]	train-mlogloss:0.22134	eval-mlogloss:0.14953
[292]	train-mlogloss:0.22133	eval-mlogloss:0.14952
[293]	train-mlogloss:0.22109	eval-mlogloss:0.14954
[294]	train-mlogloss:0.22109	eval-mlogloss:0.14938
[295]	train-mlogloss:0.22104	eval-mlogloss:0.14916
[296]	train-mlogloss:0.22103	eval-mlogloss:0.14926
[297]	train-mlogloss:0.22115	eval-mlogloss:0.14982
[298]	train-mlogloss:0.22108	eval-mlogloss:0.14947
[299]	train-mlogloss:0.22099	eval-mlogloss:0.14912

[I 2026-05-06 16:08:47,222] Trial 0 finished with value: 1.0 and parameters: {'lambda': 3.3040973683415064e-06, 'alpha': 3.9530011973898634e-05, 'eta': 0.2098190616012191, 'gamma': 0.003439146899030436, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8516066499538626, 'colsample_bytree': 0.49771044637713563}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.02166	eval-mlogloss:1.03172
[1]	train-mlogloss:0.85909	eval-mlogloss:0.86165
[2]	train-mlogloss:0.73217	eval-mlogloss:0.72359
[3]	train-mlogloss:0.65465	eval-mlogloss:0.63761
[4]	train-mlogloss:0.58139	eval-mlogloss:0.56366
[5]	train-mlogloss:0.50349	eval-mlogloss:0.47983
[6]	train-mlogloss:0.45785	eval-mlogloss:0.43388
[7]	train-mlogloss:0.42639	eval-mlogloss:0.39961
[8]	train-mlogloss:0.37788	eval-mlogloss:0.34638
[9]	train-mlogloss:0.34854	eval-mlogloss:0.31745
[10]	train-mlogloss:0.31431	eval-mlogloss:0.27902
[11]	train-mlogloss:0.28806	eval-mlogloss:0.24757
[12]	train-mlogloss:0.28053	eval-mlogloss:0.24192
[13]	train-mlogloss:0.25472	eval-mlogloss:0.21265
[14]	train-mlogloss:0.24875	eval-mlogloss:0.20802
[15]	train-mlogloss:0.23691	eval-mlogloss:0.19505
[16]	train-mlogloss:0.22610	eval-mlogloss:0.18316
[17]	train-mlogloss:0.21318	eval-mlogloss:0.17057
[18]	train-mlogloss:0.20547	eval-mlogloss:0.16272
[19]	train-mlogloss:0.19795	eval-mlogloss:0.15542
[20]	train-mlogloss:0.18449	eval-mlogloss:0.14014
[21]	train-mlogloss:0.17498	eval-mlogloss:0.12939
[22]	train-mlogloss:0.17003	eval-mlogloss:0.12456
[23]	train-mlogloss:0.15900	eval-mlogloss:0.11158
[24]	train-mlogloss:0.15444	eval-mlogloss:0.10785
[25]	train-mlogloss:0.14793	eval-mlogloss:0.10052
[26]	train-mlogloss:0.14368	eval-mlogloss:0.09639
[27]	train-mlogloss:0.14129	eval-mlogloss:0.09687
[28]	train-mlogloss:0.13930	eval-mlogloss:0.09796
[29]	train-mlogloss:0.13273	eval-mlogloss:0.08920
[30]	train-mlogloss:0.12840	eval-mlogloss:0.08536
[31]	train-mlogloss:0.12757	eval-mlogloss:0.08552
[32]	train-mlogloss:0.12505	eval-mlogloss:0.08342
[33]	train-mlogloss:0.12414	eval-mlogloss:0.08276
[34]	train-mlogloss:0.12050	eval-mlogloss:0.07880
[35]	train-mlogloss:0.11766	eval-mlogloss:0.07545
[36]	train-mlogloss:0.11570	eval-mlogloss:0.07483
[37]	train-mlogloss:0.11282	eval-mlogloss:0.07273
[38]	train-mlogloss:0.11133	eval-mlogloss:0.07190
[39]	train-mlogloss:0.11000	eval-mlogloss:0.06967
[40]	train-mlogloss:0.10954	eval-mlogloss:0.06978
[41]	train-mlogloss:0.10663	eval-mlogloss:0.06724
[42]	train-mlogloss:0.10642	eval-mlogloss:0.06719
[43]	train-mlogloss:0.10516	eval-mlogloss:0.06523
[44]	train-mlogloss:0.10297	eval-mlogloss:0.06159
[45]	train-mlogloss:0.10186	eval-mlogloss:0.06172
[46]	train-mlogloss:0.09980	eval-mlogloss:0.05923
[47]	train-mlogloss:0.09910	eval-mlogloss:0.05904
[48]	train-mlogloss:0.09786	eval-mlogloss:0.05766
[49]	train-mlogloss:0.09660	eval-mlogloss:0.05754
[50]	train-mlogloss:0.09522	eval-mlogloss:0.05535
[51]	train-mlogloss:0.09372	eval-mlogloss:0.05428
[52]	train-mlogloss:0.09230	eval-mlogloss:0.05471
[53]	train-mlogloss:0.09050	eval-mlogloss:0.05168
[54]	train-mlogloss:0.08937	eval-mlogloss:0.05113
[55]	train-mlogloss:0.08809	eval-mlogloss:0.04963
[56]	train-mlogloss:0.08724	eval-mlogloss:0.04810
[57]	train-mlogloss:0.08594	eval-mlogloss:0.04572
[58]	train-mlogloss:0.08561	eval-mlogloss:0.04552
[59]	train-mlogloss:0.08448	eval-mlogloss:0.04545
[60]	train-mlogloss:0.08373	eval-mlogloss:0.04493
[61]	train-mlogloss:0.08368	eval-mlogloss:0.04497
[62]	train-mlogloss:0.08286	eval-mlogloss:0.04366
[63]	train-mlogloss:0.08244	eval-mlogloss:0.04348
[64]	train-mlogloss:0.08184	eval-mlogloss:0.04411
[65]	train-mlogloss:0.08202	eval-mlogloss:0.04313
[66]	train-mlogloss:0.08139	eval-mlogloss:0.04219
[67]	train-mlogloss:0.08113	eval-mlogloss:0.04179
[68]	train-mlogloss:0.08071	eval-mlogloss:0.04195
[69]	train-mlogloss:0.08037	eval-mlogloss:0.04161
[70]	train-mlogloss:0.08002	eval-mlogloss:0.04055
[71]	train-mlogloss:0.07951	eval-mlogloss:0.03884
[72]	train-mlogloss:0.07940	eval-mlogloss:0.03794
[73]	train-mlogloss:0.07927	eval-mlogloss:0.03784
[74]	train-mlogloss:0.07789	eval-mlogloss:0.03649
[75]	train-mlogloss:0.07753	eval-mlogloss:0.03572
[76]	train-mlogloss:0.07730	eval-mlogloss:0.03588
[77]	train-mlogloss:0.07683	eval-mlogloss:0.03642
[78]	train-mlogloss:0.07601	eval-mlogloss:0.03564
[79]	train-mlogloss:0.07597	eval-mlogloss:0.03569
[80]	train-mlogloss:0.07562	eval-mlogloss:0.03566
[81]	train-mlogloss:0.07544	eval-mlogloss:0.03478
[82]	train-mlogloss:0.07438	eval-mlogloss:0.03523
[83]	train-mlogloss:0.07385	eval-mlogloss:0.03483
[84]	train-mlogloss:0.07353	eval-mlogloss:0.03475
[85]	train-mlogloss:0.07247	eval-mlogloss:0.03314
[86]	train-mlogloss:0.07196	eval-mlogloss:0.03292
[87]	train-mlogloss:0.07181	eval-mlogloss:0.03259
[88]	train-mlogloss:0.07130	eval-mlogloss:0.03158
[89]	train-mlogloss:0.07126	eval-mlogloss:0.03141
[90]	train-mlogloss:0.07084	eval-mlogloss:0.03084
[91]	train-mlogloss:0.07100	eval-mlogloss:0.03117
[92]	train-mlogloss:0.07073	eval-mlogloss:0.03073
[93]	train-mlogloss:0.07056	eval-mlogloss:0.03063
[94]	train-mlogloss:0.07049	eval-mlogloss:0.03091
[95]	train-mlogloss:0.07023	eval-mlogloss:0.03035
[96]	train-mlogloss:0.06996	eval-mlogloss:0.03040
[97]	train-mlogloss:0.06973	eval-mlogloss:0.03026
[98]	train-mlogloss:0.06941	eval-mlogloss:0.02969
[99]	train-mlogloss:0.06895	eval-mlogloss:0.03005
[100]	train-mlogloss:0.06859	eval-mlogloss:0.03020
[101]	train-mlogloss:0.06795	eval-mlogloss:0.02930
[102]	train-mlogloss:0.06762	eval-mlogloss:0.02879
[103]	train-mlogloss:0.06739	eval-mlogloss:0.02874
[104]	train-mlogloss:0.06731	eval-mlogloss:0.02865
[105]	train-mlogloss:0.06715	eval-mlogloss:0.02845
[106]	train-mlogloss:0.06709	eval-mlogloss:0.02848
[107]	train-mlogloss:0.06696	eval-mlogloss:0.02787
[108]	train-mlogloss:0.06660	eval-mlogloss:0.02748
[109]	train-mlogloss:0.06642	eval-mlogloss:0.02752
[110]	train-mlogloss:0.06633	eval-mlogloss:0.02752
[111]	train-mlogloss:0.06646	eval-mlogloss:0.02803
[112]	train-mlogloss:0.06615	eval-mlogloss:0.02813
[113]	train-mlogloss:0.06593	eval-mlogloss:0.02757
[114]	train-mlogloss:0.06575	eval-mlogloss:0.02748
[115]	train-mlogloss:0.06560	eval-mlogloss:0.02787
[116]	train-mlogloss:0.06537	eval-mlogloss:0.02738
[117]	train-mlogloss:0.06517	eval-mlogloss:0.02698
[118]	train-mlogloss:0.06480	eval-mlogloss:0.02629
[119]	train-mlogloss:0.06465	eval-mlogloss:0.02648
[120]	train-mlogloss:0.06476	eval-mlogloss:0.02685
[121]	train-mlogloss:0.06447	eval-mlogloss:0.02625
[122]	train-mlogloss:0.06420	eval-mlogloss:0.02549
[123]	train-mlogloss:0.06407	eval-mlogloss:0.02510
[124]	train-mlogloss:0.06372	eval-mlogloss:0.02470
[125]	train-mlogloss:0.06342	eval-mlogloss:0.02413
[126]	train-mlogloss:0.06336	eval-mlogloss:0.02411
[127]	train-mlogloss:0.06330	eval-mlogloss:0.02406
[128]	train-mlogloss:0.06326	eval-mlogloss:0.02397
[129]	train-mlogloss:0.06311	eval-mlogloss:0.02391
[130]	train-mlogloss:0.06308	eval-mlogloss:0.02414
[131]	train-mlogloss:0.06267	eval-mlogloss:0.02382
[132]	train-mlogloss:0.06251	eval-mlogloss:0.02316
[133]	train-mlogloss:0.06223	eval-mlogloss:0.02296
[134]	train-mlogloss:0.06232	eval-mlogloss:0.02297
[135]	train-mlogloss:0.06216	eval-mlogloss:0.02272
[136]	train-mlogloss:0.06217	eval-mlogloss:0.02272
[137]	train-mlogloss:0.06182	eval-mlogloss:0.02290
[138]	train-mlogloss:0.06148	eval-mlogloss:0.02288
[139]	train-mlogloss:0.06110	eval-mlogloss:0.02320
[140]	train-mlogloss:0.06108	eval-mlogloss:0.02318
[141]	train-mlogloss:0.06102	eval-mlogloss:0.02324
[142]	train-mlogloss:0.06120	eval-mlogloss:0.02308
[143]	train-mlogloss:0.06129	eval-mlogloss:0.02326
[144]	train-mlogloss:0.06090	eval-mlogloss:0.02278
[145]	train-mlogloss:0.06079	eval-mlogloss:0.02252
[146]	train-mlogloss:0.06072	eval-mlogloss:0.02262
[147]	train-mlogloss:0.06046	eval-mlogloss:0.02278
[148]	train-mlogloss:0.06009	eval-mlogloss:0.02256
[149]	train-mlogloss:0.05994	eval-mlogloss:0.02257
[150]	train-mlogloss:0.05985	eval-mlogloss:0.02284
[151]	train-mlogloss:0.05973	eval-mlogloss:0.02302
[152]	train-mlogloss:0.05966	eval-mlogloss:0.02303
[153]	train-mlogloss:0.05960	eval-mlogloss:0.02313
[154]	train-mlogloss:0.05915	eval-mlogloss:0.02274
[155]	train-mlogloss:0.05903	eval-mlogloss:0.02310
[156]	train-mlogloss:0.05894	eval-mlogloss:0.02266
[157]	train-mlogloss:0.05882	eval-mlogloss:0.02257
[158]	train-mlogloss:0.05872	eval-mlogloss:0.02218
[159]	train-mlogloss:0.05862	eval-mlogloss:0.02196
[160]	train-mlogloss:0.05864	eval-mlogloss:0.02217
[161]	train-mlogloss:0.05857	eval-mlogloss:0.02216
[162]	train-mlogloss:0.05843	eval-mlogloss:0.02236
[163]	train-mlogloss:0.05837	eval-mlogloss:0.02233
[164]	train-mlogloss:0.05835	eval-mlogloss:0.02225
[165]	train-mlogloss:0.05834	eval-mlogloss:0.02229
[166]	train-mlogloss:0.05827	eval-mlogloss:0.02260
[167]	train-mlogloss:0.05814	eval-mlogloss:0.02189
[168]	train-mlogloss:0.05811	eval-mlogloss:0.02187
[169]	train-mlogloss:0.05795	eval-mlogloss:0.02205
[170]	train-mlogloss:0.05790	eval-mlogloss:0.02209
[171]	train-mlogloss:0.05757	eval-mlogloss:0.02208
[172]	train-mlogloss:0.05740	eval-mlogloss:0.02236
[173]	train-mlogloss:0.05743	eval-mlogloss:0.02226
[174]	train-mlogloss:0.05736	eval-mlogloss:0.02177
[175]	train-mlogloss:0.05738	eval-mlogloss:0.02169
[176]	train-mlogloss:0.05726	eval-mlogloss:0.02194
[177]	train-mlogloss:0.05720	eval-mlogloss:0.02196
[178]	train-mlogloss:0.05697	eval-mlogloss:0.02221
[179]	train-mlogloss:0.05684	eval-mlogloss:0.02232
[180]	train-mlogloss:0.05675	eval-mlogloss:0.02192
[181]	train-mlogloss:0.05669	eval-mlogloss:0.02182
[182]	train-mlogloss:0.05653	eval-mlogloss:0.02183
[183]	train-mlogloss:0.05654	eval-mlogloss:0.02188
[184]	train-mlogloss:0.05645	eval-mlogloss:0.02169
[185]	train-mlogloss:0.05645	eval-mlogloss:0.02169
[186]	train-mlogloss:0.05634	eval-mlogloss:0.02161
[187]	train-mlogloss:0.05634	eval-mlogloss:0.02162
[188]	train-mlogloss:0.05626	eval-mlogloss:0.02178
[189]	train-mlogloss:0.05620	eval-mlogloss:0.02170
[190]	train-mlogloss:0.05624	eval-mlogloss:0.02142
[191]	train-mlogloss:0.05605	eval-mlogloss:0.02151
[192]	train-mlogloss:0.05575	eval-mlogloss:0.02132
[193]	train-mlogloss:0.05555	eval-mlogloss:0.02129
[194]	train-mlogloss:0.05539	eval-mlogloss:0.02125
[195]	train-mlogloss:0.05532	eval-mlogloss:0.02135
[196]	train-mlogloss:0.05528	eval-mlogloss:0.02150
[197]	train-mlogloss:0.05514	eval-mlogloss:0.02068
[198]	train-mlogloss:0.05513	eval-mlogloss:0.02060
[199]	train-mlogloss:0.05505	eval-mlogloss:0.02070
[200]	train-mlogloss:0.05496	eval-mlogloss:0.02102
[201]	train-mlogloss:0.05494	eval-mlogloss:0.02121
[202]	train-mlogloss:0.05475	eval-mlogloss:0.02123
[203]	train-mlogloss:0.05473	eval-mlogloss:0.02126
[204]	train-mlogloss:0.05458	eval-mlogloss:0.02119
[205]	train-mlogloss:0.05431	eval-mlogloss:0.02160
[206]	train-mlogloss:0.05420	eval-mlogloss:0.02117
[207]	train-mlogloss:0.05414	eval-mlogloss:0.02131
[208]	train-mlogloss:0.05413	eval-mlogloss:0.02128
[209]	train-mlogloss:0.05413	eval-mlogloss:0.02093
[210]	train-mlogloss:0.05403	eval-mlogloss:0.02076
[211]	train-mlogloss:0.05400	eval-mlogloss:0.02073
[212]	train-mlogloss:0.05388	eval-mlogloss:0.02088
[213]	train-mlogloss:0.05385	eval-mlogloss:0.02093
[214]	train-mlogloss:0.05379	eval-mlogloss:0.02113
[215]	train-mlogloss:0.05368	eval-mlogloss:0.02071
[216]	train-mlogloss:0.05347	eval-mlogloss:0.02101
[217]	train-mlogloss:0.05345	eval-mlogloss:0.02092
[218]	train-mlogloss:0.05350	eval-mlogloss:0.02120
[219]	train-mlogloss:0.05348	eval-mlogloss:0.02115
[220]	train-mlogloss:0.05342	eval-mlogloss:0.02123
[221]	train-mlogloss:0.05341	eval-mlogloss:0.02122
[222]	train-mlogloss:0.05334	eval-mlogloss:0.02112
[223]	train-mlogloss:0.05320	eval-mlogloss:0.02110
[224]	train-mlogloss:0.05306	eval-mlogloss:0.02094
[225]	train-mlogloss:0.05302	eval-mlogloss:0.02095
[226]	train-mlogloss:0.05292	eval-mlogloss:0.02119
[227]	train-mlogloss:0.05286	eval-mlogloss:0.02137
[228]	train-mlogloss:0.05261	eval-mlogloss:0.02134

[I 2026-05-06 16:08:54,005] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.24341885909454716, 'alpha': 0.3294730773240702, 'eta': 0.15450634511136713, 'gamma': 4.677876118487861e-07, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.6165517486065253, 'colsample_bytree': 0.46897161669517784}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.04145	eval-mlogloss:1.04123
[1]	train-mlogloss:0.96113	eval-mlogloss:0.95670
[2]	train-mlogloss:0.88907	eval-mlogloss:0.88132
[3]	train-mlogloss:0.82262	eval-mlogloss:0.81069
[4]	train-mlogloss:0.76419	eval-mlogloss:0.75044
[5]	train-mlogloss:0.70994	eval-mlogloss:0.69226
[6]	train-mlogloss:0.66270	eval-mlogloss:0.64382
[7]	train-mlogloss:0.62065	eval-mlogloss:0.60053
[8]	train-mlogloss:0.58167	eval-mlogloss:0.55902
[9]	train-mlogloss:0.54474	eval-mlogloss:0.51974
[10]	train-mlogloss:0.51222	eval-mlogloss:0.48426
[11]	train-mlogloss:0.48252	eval-mlogloss:0.45161
[12]	train-mlogloss:0.46559	eval-mlogloss:0.43514
[13]	train-mlogloss:0.43891	eval-mlogloss:0.40579
[14]	train-mlogloss:0.42493	eval-mlogloss:0.39136
[15]	train-mlogloss:0.40374	eval-mlogloss:0.36792
[16]	train-mlogloss:0.38431	eval-mlogloss:0.34653
[17]	train-mlogloss:0.36886	eval-mlogloss:0.32981
[18]	train-mlogloss:0.34993	eval-mlogloss:0.30990
[19]	train-mlogloss:0.33607	eval-mlogloss:0.29552
[20]	train-mlogloss:0.32244	eval-mlogloss:0.27953
[21]	train-mlogloss:0.30835	eval-mlogloss:0.26346
[22]	train-mlogloss:0.29843	eval-mlogloss:0.25209
[23]	train-mlogloss:0.28569	eval-mlogloss:0.23747
[24]	train-mlogloss:0.27437	eval-mlogloss:0.22401
[25]	train-mlogloss:0.26580	eval-mlogloss:0.21425
[26]	train-mlogloss:0.25911	eval-mlogloss:0.20662
[27]	train-mlogloss:0.25082	eval-mlogloss:0.19700
[28]	train-mlogloss:0.24451	eval-mlogloss:0.18979
[29]	train-mlogloss:0.23705	eval-mlogloss:0.18026
[30]	train-mlogloss:0.23062	eval-mlogloss:0.17417
[31]	train-mlogloss:0.22442	eval-mlogloss:0.16750
[32]	train-mlogloss:0.22179	eval-mlogloss:0.16398
[33]	train-mlogloss:0.21795	eval-mlogloss:0.15923
[34]	train-mlogloss:0.21498	eval-mlogloss:0.15579
[35]	train-mlogloss:0.21336	eval-mlogloss:0.15389
[36]	train-mlogloss:0.20765	eval-mlogloss:0.14746
[37]	train-mlogloss:0.20550	eval-mlogloss:0.14490
[38]	train-mlogloss:0.20377	eval-mlogloss:0.14297
[39]	train-mlogloss:0.20304	eval-mlogloss:0.14187
[40]	train-mlogloss:0.20157	eval-mlogloss:0.14034
[41]	train-mlogloss:0.20101	eval-mlogloss:0.14044
[42]	train-mlogloss:0.20085	eval-mlogloss:0.13970
[43]	train-mlogloss:0.19741	eval-mlogloss:0.13595
[44]	train-mlogloss:0.19559	eval-mlogloss:0.13264
[45]	train-mlogloss:0.19534	eval-mlogloss:0.13229
[46]	train-mlogloss:0.19524	eval-mlogloss:0.13209
[47]	train-mlogloss:0.19521	eval-mlogloss:0.13180
[48]	train-mlogloss:0.19502	eval-mlogloss:0.13157
[49]	train-mlogloss:0.19301	eval-mlogloss:0.12930
[50]	train-mlogloss:0.19169	eval-mlogloss:0.12756
[51]	train-mlogloss:0.18976	eval-mlogloss:0.12472
[52]	train-mlogloss:0.18953	eval-mlogloss:0.12462
[53]	train-mlogloss:0.18890	eval-mlogloss:0.12366
[54]	train-mlogloss:0.18843	eval-mlogloss:0.12374
[55]	train-mlogloss:0.18824	eval-mlogloss:0.12352
[56]	train-mlogloss:0.18784	eval-mlogloss:0.12297
[57]	train-mlogloss:0.18779	eval-mlogloss:0.12280
[58]	train-mlogloss:0.18778	eval-mlogloss:0.12272
[59]	train-mlogloss:0.18746	eval-mlogloss:0.12257
[60]	train-mlogloss:0.18705	eval-mlogloss:0.12223
[61]	train-mlogloss:0.18681	eval-mlogloss:0.12203
[62]	train-mlogloss:0.18651	eval-mlogloss:0.12190
[63]	train-mlogloss:0.18642	eval-mlogloss:0.12127
[64]	train-mlogloss:0.18630	eval-mlogloss:0.12060
[65]	train-mlogloss:0.18632	eval-mlogloss:0.12054
[66]	train-mlogloss:0.18610	eval-mlogloss:0.12039
[67]	train-mlogloss:0.18603	eval-mlogloss:0.12004
[68]	train-mlogloss:0.18587	eval-mlogloss:0.11989
[69]	train-mlogloss:0.18479	eval-mlogloss:0.11831
[70]	train-mlogloss:0.18471	eval-mlogloss:0.11826
[71]	train-mlogloss:0.18465	eval-mlogloss:0.11847
[72]	train-mlogloss:0.18462	eval-mlogloss:0.11832
[73]	train-mlogloss:0.18456	eval-mlogloss:0.11824
[74]	train-mlogloss:0.18452	eval-mlogloss:0.11809
[75]	train-mlogloss:0.18453	eval-mlogloss:0.11820
[76]	train-mlogloss:0.18450	eval-mlogloss:0.11832
[77]	train-mlogloss:0.18437	eval-mlogloss:0.11826
[78]	train-mlogloss:0.18407	eval-mlogloss:0.11818
[79]	train-mlogloss:0.18406	eval-mlogloss:0.11816
[80]	train-mlogloss:0.18408	eval-mlogloss:0.11822
[81]	train-mlogloss:0.18410	eval-mlogloss:0.11818
[82]	train-mlogloss:0.18412	eval-mlogloss:0.11826
[83]	train-mlogloss:0.18418	eval-mlogloss:0.11847
[84]	train-mlogloss:0.18303	eval-mlogloss:0.11713
[85]	train-mlogloss:0.18274	eval-mlogloss:0.11695
[86]	train-mlogloss:0.18273	eval-mlogloss:0.11669
[87]	train-mlogloss:0.18268	eval-mlogloss:0.11658
[88]	train-mlogloss:0.18249	eval-mlogloss:0.11647
[89]	train-mlogloss:0.18182	eval-mlogloss:0.11547
[90]	train-mlogloss:0.18171	eval-mlogloss:0.11544
[91]	train-mlogloss:0.18167	eval-mlogloss:0.11502
[92]	train-mlogloss:0.18146	eval-mlogloss:0.11490
[93]	train-mlogloss:0.18138	eval-mlogloss:0.11453
[94]	train-mlogloss:0.18139	eval-mlogloss:0.11441
[95]	train-mlogloss:0.18120	eval-mlogloss:0.11434
[96]	train-mlogloss:0.18112	eval-mlogloss:0.11429
[97]	train-mlogloss:0.18108	eval-mlogloss:0.11421
[98]	train-mlogloss:0.18088	eval-mlogloss:0.11413
[99]	train-mlogloss:0.18064	eval-mlogloss:0.11378
[100]	train-mlogloss:0.18053	eval-mlogloss:0.11364
[101]	train-mlogloss:0.17919	eval-mlogloss:0.11227
[102]	train-mlogloss:0.17907	eval-mlogloss:0.11209
[103]	train-mlogloss:0.17907	eval-mlogloss:0.11207
[104]	train-mlogloss:0.17900	eval-mlogloss:0.11204
[105]	train-mlogloss:0.17887	eval-mlogloss:0.11146
[106]	train-mlogloss:0.17868	eval-mlogloss:0.11124
[107]	train-mlogloss:0.17871	eval-mlogloss:0.11136
[108]	train-mlogloss:0.17855	eval-mlogloss:0.11119
[109]	train-mlogloss:0.17850	eval-mlogloss:0.11104
[110]	train-mlogloss:0.17841	eval-mlogloss:0.11107
[111]	train-mlogloss:0.17836	eval-mlogloss:0.11111
[112]	train-mlogloss:0.17831	eval-mlogloss:0.11109
[113]	train-mlogloss:0.17823	eval-mlogloss:0.11017
[114]	train-mlogloss:0.17822	eval-mlogloss:0.10969
[115]	train-mlogloss:0.17815	eval-mlogloss:0.10951
[116]	train-mlogloss:0.17818	eval-mlogloss:0.10963
[117]	train-mlogloss:0.17804	eval-mlogloss:0.10949
[118]	train-mlogloss:0.17803	eval-mlogloss:0.10959
[119]	train-mlogloss:0.17787	eval-mlogloss:0.10936
[120]	train-mlogloss:0.17775	eval-mlogloss:0.10929
[121]	train-mlogloss:0.17780	eval-mlogloss:0.10942
[122]	train-mlogloss:0.17766	eval-mlogloss:0.10940
[123]	train-mlogloss:0.17767	eval-mlogloss:0.10940
[124]	train-mlogloss:0.17669	eval-mlogloss:0.10821
[125]	train-mlogloss:0.17657	eval-mlogloss:0.10815
[126]	train-mlogloss:0.17612	eval-mlogloss:0.10847
[127]	train-mlogloss:0.17607	eval-mlogloss:0.10836
[128]	train-mlogloss:0.17611	eval-mlogloss:0.10846
[129]	train-mlogloss:0.17596	eval-mlogloss:0.10842
[130]	train-mlogloss:0.17602	eval-mlogloss:0.10850
[131]	train-mlogloss:0.17602	eval-mlogloss:0.10852
[132]	train-mlogloss:0.17469	eval-mlogloss:0.10681
[133]	train-mlogloss:0.17466	eval-mlogloss:0.10677
[134]	train-mlogloss:0.17465	eval-mlogloss:0.10680
[135]	train-mlogloss:0.17468	eval-mlogloss:0.10682
[136]	train-mlogloss:0.17470	eval-mlogloss:0.10688
[137]	train-mlogloss:0.17459	eval-mlogloss:0.10675
[138]	train-mlogloss:0.17449	eval-mlogloss:0.10654
[139]	train-mlogloss:0.17432	eval-mlogloss:0.10635
[140]	train-mlogloss:0.17434	eval-mlogloss:0.10671
[141]	train-mlogloss:0.17431	eval-mlogloss:0.10625
[142]	train-mlogloss:0.17437	eval-mlogloss:0.10629
[143]	train-mlogloss:0.17424	eval-mlogloss:0.10625
[144]	train-mlogloss:0.17409	eval-mlogloss:0.10623
[145]	train-mlogloss:0.17411	eval-mlogloss:0.10597
[146]	train-mlogloss:0.17410	eval-mlogloss:0.10592
[147]	train-mlogloss:0.17337	eval-mlogloss:0.10469
[148]	train-mlogloss:0.17334	eval-mlogloss:0.10470
[149]	train-mlogloss:0.17333	eval-mlogloss:0.10468
[150]	train-mlogloss:0.17329	eval-mlogloss:0.10459
[151]	train-mlogloss:0.17327	eval-mlogloss:0.10450
[152]	train-mlogloss:0.17316	eval-mlogloss:0.10440
[153]	train-mlogloss:0.17311	eval-mlogloss:0.10446
[154]	train-mlogloss:0.17296	eval-mlogloss:0.10410
[155]	train-mlogloss:0.17291	eval-mlogloss:0.10415
[156]	train-mlogloss:0.17280	eval-mlogloss:0.10398
[157]	train-mlogloss:0.17279	eval-mlogloss:0.10397
[158]	train-mlogloss:0.17275	eval-mlogloss:0.10394
[159]	train-mlogloss:0.17256	eval-mlogloss:0.10392
[160]	train-mlogloss:0.17239	eval-mlogloss:0.10387
[161]	train-mlogloss:0.17229	eval-mlogloss:0.10370
[162]	train-mlogloss:0.17228	eval-mlogloss:0.10377
[163]	train-mlogloss:0.17229	eval-mlogloss:0.10395
[164]	train-mlogloss:0.17230	eval-mlogloss:0.10369
[165]	train-mlogloss:0.17225	eval-mlogloss:0.10371
[166]	train-mlogloss:0.17209	eval-mlogloss:0.10341
[167]	train-mlogloss:0.17210	eval-mlogloss:0.10344
[168]	train-mlogloss:0.17211	eval-mlogloss:0.10343
[169]	train-mlogloss:0.17195	eval-mlogloss:0.10329
[170]	train-mlogloss:0.17191	eval-mlogloss:0.10310
[171]	train-mlogloss:0.17181	eval-mlogloss:0.10303
[172]	train-mlogloss:0.17181	eval-mlogloss:0.10299
[173]	train-mlogloss:0.17170	eval-mlogloss:0.10299
[174]	train-mlogloss:0.17173	eval-mlogloss:0.10317
[175]	train-mlogloss:0.17175	eval-mlogloss:0.10317
[176]	train-mlogloss:0.17172	eval-mlogloss:0.10297
[177]	train-mlogloss:0.17169	eval-mlogloss:0.10285
[178]	train-mlogloss:0.17168	eval-mlogloss:0.10292
[179]	train-mlogloss:0.17168	eval-mlogloss:0.10288
[180]	train-mlogloss:0.17167	eval-mlogloss:0.10220
[181]	train-mlogloss:0.17160	eval-mlogloss:0.10216
[182]	train-mlogloss:0.17163	eval-mlogloss:0.10207
[183]	train-mlogloss:0.17161	eval-mlogloss:0.10219
[184]	train-mlogloss:0.17149	eval-mlogloss:0.10198
[185]	train-mlogloss:0.17150	eval-mlogloss:0.10205
[186]	train-mlogloss:0.17142	eval-mlogloss:0.10189
[187]	train-mlogloss:0.17143	eval-mlogloss:0.10186
[188]	train-mlogloss:0.17143	eval-mlogloss:0.10196
[189]	train-mlogloss:0.17142	eval-mlogloss:0.10203
[190]	train-mlogloss:0.17134	eval-mlogloss:0.10211
[191]	train-mlogloss:0.17131	eval-mlogloss:0.10213
[192]	train-mlogloss:0.17130	eval-mlogloss:0.10221
[193]	train-mlogloss:0.17122	eval-mlogloss:0.10212
[194]	train-mlogloss:0.17109	eval-mlogloss:0.10210
[195]	train-mlogloss:0.17109	eval-mlogloss:0.10203
[196]	train-mlogloss:0.17102	eval-mlogloss:0.10200
[197]	train-mlogloss:0.17102	eval-mlogloss:0.10194
[198]	train-mlogloss:0.17103	eval-mlogloss:0.10185
[199]	train-mlogloss:0.17102	eval-mlogloss:0.10175
[200]	train-mlogloss:0.17098	eval-mlogloss:0.10171
[201]	train-mlogloss:0.17101	eval-mlogloss:0.10163
[202]	train-mlogloss:0.17100	eval-mlogloss:0.10172
[203]	train-mlogloss:0.17098	eval-mlogloss:0.10152
[204]	train-mlogloss:0.17089	eval-mlogloss:0.10148
[205]	train-mlogloss:0.17082	eval-mlogloss:0.10142
[206]	train-mlogloss:0.17072	eval-mlogloss:0.10142
[207]	train-mlogloss:0.17060	eval-mlogloss:0.10122
[208]	train-mlogloss:0.17061	eval-mlogloss:0.10128
[209]	train-mlogloss:0.17063	eval-mlogloss:0.10113
[210]	train-mlogloss:0.17062	eval-mlogloss:0.10084
[211]	train-mlogloss:0.17062	eval-mlogloss:0.10086
[212]	train-mlogloss:0.17048	eval-mlogloss:0.10078
[213]	train-mlogloss:0.17049	eval-mlogloss:0.10058
[214]	train-mlogloss:0.17049	eval-mlogloss:0.10057
[215]	train-mlogloss:0.17047	eval-mlogloss:0.10063
[216]	train-mlogloss:0.17048	eval-mlogloss:0.10059
[217]	train-mlogloss:0.17048	eval-mlogloss:0.10071
[218]	train-mlogloss:0.17018	eval-mlogloss:0.10029
[219]	train-mlogloss:0.17018	eval-mlogloss:0.10024
[220]	train-mlogloss:0.17017	eval-mlogloss:0.10029
[221]	train-mlogloss:0.17018	eval-mlogloss:0.10041
[222]	train-mlogloss:0.17018	eval-mlogloss:0.10035
[223]	train-mlogloss:0.17019	eval-mlogloss:0.10037
[224]	train-mlogloss:0.17019	eval-mlogloss:0.10015
[225]	train-mlogloss:0.17019	eval-mlogloss:0.10015
[226]	train-mlogloss:0.17019	eval-mlogloss:0.10013
[227]	train-mlogloss:0.17019	eval-mlogloss:0.10017
[228]	train-mlogloss:0.17014	eval-mlogloss:0.10016
[229]	train-mlogloss:0.17017	eval-mlogloss:0.10031
[230]	train-mlogloss:0.17018	eval-mlogloss:0.10032
[231]	train-mlogloss:0.17018	eval-mlogloss:0.10025
[232]	train-mlogloss:0.17019	eval-mlogloss:0.10032
[233]	train-mlogloss:0.17018	eval-mlogloss:0.10053
[234]	train-mlogloss:0.17023	eval-mlogloss:0.10075
[235]	train-mlogloss:0.17019	eval-mlogloss:0.10058
[236]	train-mlogloss:0.17020	eval-mlogloss:0.10066
[237]	train-mlogloss:0.17023	eval-mlogloss:0.10073
[238]	train-mlogloss:0.17011	eval-mlogloss:0.10068
[239]	train-mlogloss:0.17008	eval-mlogloss:0.10062
[240]	train-mlogloss:0.17010	eval-mlogloss:0.10071
[241]	train-mlogloss:0.17008	eval-mlogloss:0.10088
[242]	train-mlogloss:0.17011	eval-mlogloss:0.10099
[243]	train-mlogloss:0.17009	eval-mlogloss:0.10090
[244]	train-mlogloss:0.17008	eval-mlogloss:0.10088
[245]	train-mlogloss:0.17007	eval-mlogloss:0.10084
[246]	train-mlogloss:0.17005	eval-mlogloss:0.10090
[247]	train-mlogloss:0.17006	eval-mlogloss:0.10090
[248]	train-mlogloss:0.17007	eval-mlogloss:0.10094
[249]	train-mlogloss:0.17005	eval-mlogloss:0.10082
[250]	train-mlogloss:0.17000	eval-mlogloss:0.10078
[251]	train-mlogloss:0.16995	eval-mlogloss:0.10082
[252]	train-mlogloss:0.16989	eval-mlogloss:0.10066
[253]	train-mlogloss:0.16989	eval-mlogloss:0.10068
[254]	train-mlogloss:0.16986	eval-mlogloss:0.10075
[255]	train-mlogloss:0.16978	eval-mlogloss:0.10072
[256]	train-mlogloss:0.16978	eval-mlogloss:0.10068

[I 2026-05-06 16:09:00,630] Trial 2 finished with value: 1.0 and parameters: {'lambda': 0.07508798115648893, 'alpha': 1.3108001028331477e-06, 'eta': 0.06906797909433395, 'gamma': 1.7363612274690087e-07, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.66037008378852, 'colsample_bytree': 0.5162394334632195}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.93103	eval-mlogloss:0.92488
[1]	train-mlogloss:0.73271	eval-mlogloss:0.71767

[I 2026-05-06 16:09:00,765] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.89609	eval-mlogloss:0.91811
[1]	train-mlogloss:0.69793	eval-mlogloss:0.69563

[I 2026-05-06 16:09:00,898] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95565	eval-mlogloss:0.96178
[1]	train-mlogloss:0.80712	eval-mlogloss:0.80695

[I 2026-05-06 16:09:01,029] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03437	eval-mlogloss:1.04717
[1]	train-mlogloss:0.90569	eval-mlogloss:0.91169

[I 2026-05-06 16:09:01,176] Trial 6 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94109	eval-mlogloss:0.93079
[1]	train-mlogloss:0.81570	eval-mlogloss:0.79830

[I 2026-05-06 16:09:01,278] Trial 7 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.76842	eval-mlogloss:0.74279
[1]	train-mlogloss:0.56880	eval-mlogloss:0.52629

[I 2026-05-06 16:09:01,368] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.76344	eval-mlogloss:0.73131
[1]	train-mlogloss:0.55955	eval-mlogloss:0.51686

[I 2026-05-06 16:09:01,472] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06885	eval-mlogloss:1.07232
[1]	train-mlogloss:1.02699	eval-mlogloss:1.02860
[2]	train-mlogloss:0.98804	eval-mlogloss:0.98822
[3]	train-mlogloss:0.95044	eval-mlogloss:0.94915
[4]	train-mlogloss:0.91490	eval-mlogloss:0.91303
[5]	train-mlogloss:0.88135	eval-mlogloss:0.87719
[6]	train-mlogloss:0.84949	eval-mlogloss:0.84435
[7]	train-mlogloss:0.81921	eval-mlogloss:0.81329
[8]	train-mlogloss:0.79051	eval-mlogloss:0.78367
[9]	train-mlogloss:0.76341	eval-mlogloss:0.75516
[10]	train-mlogloss:0.73730	eval-mlogloss:0.72823
[11]	train-mlogloss:0.71282	eval-mlogloss:0.70262
[12]	train-mlogloss:0.69838	eval-mlogloss:0.68837
[13]	train-mlogloss:0.67552	eval-mlogloss:0.66345
[14]	train-mlogloss:0.66116	eval-mlogloss:0.64913
[15]	train-mlogloss:0.64230	eval-mlogloss:0.62922
[16]	train-mlogloss:0.62426	eval-mlogloss:0.61056
[17]	train-mlogloss:0.60933	eval-mlogloss:0.59583
[18]	train-mlogloss:0.59042	eval-mlogloss:0.57592
[19]	train-mlogloss:0.57539	eval-mlogloss:0.55967
[20]	train-mlogloss:0.55794	eval-mlogloss:0.54128
[21]	train-mlogloss:0.54133	eval-mlogloss:0.52273
[22]	train-mlogloss:0.52718	eval-mlogloss:0.50752
[23]	train-mlogloss:0.51178	eval-mlogloss:0.49025
[24]	train-mlogloss:0.49694	eval-mlogloss:0.47383
[25]	train-mlogloss:0.48282	eval-mlogloss:0.45793
[26]	train-mlogloss:0.47162	eval-mlogloss:0.44611
[27]	train-mlogloss:0.45877	eval-mlogloss:0.43178
[28]	train-mlogloss:0.44847	eval-mlogloss:0.42053
[29]	train-mlogloss:0.43631	eval-mlogloss:0.40713
[30]	train-mlogloss:0.42470	eval-mlogloss:0.39396
[31]	train-mlogloss:0.41617	eval-mlogloss:0.38559
[32]	train-mlogloss:0.40524	eval-mlogloss:0.37350
[33]	train-mlogloss:0.39901	eval-mlogloss:0.36751
[34]	train-mlogloss:0.38860	eval-mlogloss:0.35654
[35]	train-mlogloss:0.37880	eval-mlogloss:0.34532
[36]	train-mlogloss:0.37182	eval-mlogloss:0.33808
[37]	train-mlogloss:0.36233	eval-mlogloss:0.32800
[38]	train-mlogloss:0.35453	eval-mlogloss:0.31947
[39]	train-mlogloss:0.34724	eval-mlogloss:0.31162
[40]	train-mlogloss:0.34113	eval-mlogloss:0.30526
[41]	train-mlogloss:0.33377	eval-mlogloss:0.29651
[42]	train-mlogloss:0.32924	eval-mlogloss:0.29128
[43]	train-mlogloss:0.32317	eval-mlogloss:0.28467
[44]	train-mlogloss:0.31596	eval-mlogloss:0.27630
[45]	train-mlogloss:0.31046	eval-mlogloss:0.27052
[46]	train-mlogloss:0.30423	eval-mlogloss:0.26287
[47]	train-mlogloss:0.29810	eval-mlogloss:0.25575
[48]	train-mlogloss:0.29199	eval-mlogloss:0.24921
[49]	train-mlogloss:0.28590	eval-mlogloss:0.24273
[50]	train-mlogloss:0.28030	eval-mlogloss:0.23606
[51]	train-mlogloss:0.27560	eval-mlogloss:0.23101
[52]	train-mlogloss:0.27110	eval-mlogloss:0.22581
[53]	train-mlogloss:0.26604	eval-mlogloss:0.22000
[54]	train-mlogloss:0.26213	eval-mlogloss:0.21568
[55]	train-mlogloss:0.25734	eval-mlogloss:0.21049
[56]	train-mlogloss:0.25356	eval-mlogloss:0.20621
[57]	train-mlogloss:0.24918	eval-mlogloss:0.20116
[58]	train-mlogloss:0.24593	eval-mlogloss:0.19737
[59]	train-mlogloss:0.24269	eval-mlogloss:0.19343
[60]	train-mlogloss:0.23886	eval-mlogloss:0.18881
[61]	train-mlogloss:0.23660	eval-mlogloss:0.18643
[62]	train-mlogloss:0.23274	eval-mlogloss:0.18190
[63]	train-mlogloss:0.22982	eval-mlogloss:0.17877
[64]	train-mlogloss:0.22775	eval-mlogloss:0.17657
[65]	train-mlogloss:0.22456	eval-mlogloss:0.17306
[66]	train-mlogloss:0.22190	eval-mlogloss:0.16980
[67]	train-mlogloss:0.21891	eval-mlogloss:0.16626
[68]	train-mlogloss:0.21733	eval-mlogloss:0.16440
[69]	train-mlogloss:0.21446	eval-mlogloss:0.16100
[70]	train-mlogloss:0.21308	eval-mlogloss:0.15937
[71]	train-mlogloss:0.21067	eval-mlogloss:0.15629
[72]	train-mlogloss:0.20849	eval-mlogloss:0.15366
[73]	train-mlogloss:0.20609	eval-mlogloss:0.15068
[74]	train-mlogloss:0.20518	eval-mlogloss:0.14966
[75]	train-mlogloss:0.20430	eval-mlogloss:0.14866
[76]	train-mlogloss:0.20264	eval-mlogloss:0.14682
[77]	train-mlogloss:0.20175	eval-mlogloss:0.14559
[78]	train-mlogloss:0.20089	eval-mlogloss:0.14441
[79]	train-mlogloss:0.19949	eval-mlogloss:0.14275
[80]	train-mlogloss:0.19815	eval-mlogloss:0.14138
[81]	train-mlogloss:0.19735	eval-mlogloss:0.14026
[82]	train-mlogloss:0.19658	eval-mlogloss:0.13939
[83]	train-mlogloss:0.19638	eval-mlogloss:0.13913
[84]	train-mlogloss:0.19559	eval-mlogloss:0.13800
[85]	train-mlogloss:0.19482	eval-mlogloss:0.13691
[86]	train-mlogloss:0.19421	eval-mlogloss:0.13608
[87]	train-mlogloss:0.19349	eval-mlogloss:0.13526
[88]	train-mlogloss:0.19276	eval-mlogloss:0.13423
[89]	train-mlogloss:0.19206	eval-mlogloss:0.13344
[90]	train-mlogloss:0.19149	eval-mlogloss:0.13263
[91]	train-mlogloss:0.19084	eval-mlogloss:0.13170
[92]	train-mlogloss:0.19019	eval-mlogloss:0.13076
[93]	train-mlogloss:0.19019	eval-mlogloss:0.13077
[94]	train-mlogloss:0.18959	eval-mlogloss:0.12992
[95]	train-mlogloss:0.18898	eval-mlogloss:0.12902
[96]	train-mlogloss:0.18839	eval-mlogloss:0.12813
[97]	train-mlogloss:0.18781	eval-mlogloss:0.12727
[98]	train-mlogloss:0.18729	eval-mlogloss:0.12654
[99]	train-mlogloss:0.18673	eval-mlogloss:0.12568
[100]	train-mlogloss:0.18624	eval-mlogloss:0.12498
[101]	train-mlogloss:0.18569	eval-mlogloss:0.12417
[102]	train-mlogloss:0.18522	eval-mlogloss:0.12349
[103]	train-mlogloss:0.18470	eval-mlogloss:0.12270
[104]	train-mlogloss:0.18426	eval-mlogloss:0.12205
[105]	train-mlogloss:0.18375	eval-mlogloss:0.12128
[106]	train-mlogloss:0.18331	eval-mlogloss:0.12065
[107]	train-mlogloss:0.18290	eval-mlogloss:0.12004
[108]	train-mlogloss:0.18272	eval-mlogloss:0.11974
[109]	train-mlogloss:0.18272	eval-mlogloss:0.11974
[110]	train-mlogloss:0.18272	eval-mlogloss:0.11975
[111]	train-mlogloss:0.18272	eval-mlogloss:0.11976
[112]	train-mlogloss:0.18224	eval-mlogloss:0.11903
[113]	train-mlogloss:0.18184	eval-mlogloss:0.11844
[114]	train-mlogloss:0.18184	eval-mlogloss:0.11844
[115]	train-mlogloss:0.18184	eval-mlogloss:0.11845
[116]	train-mlogloss:0.18144	eval-mlogloss:0.11786
[117]	train-mlogloss:0.18106	eval-mlogloss:0.11729
[118]	train-mlogloss:0.18069	eval-mlogloss:0.11673
[119]	train-mlogloss:0.18069	eval-mlogloss:0.11674
[120]	train-mlogloss:0.18069	eval-mlogloss:0.11674
[121]	train-mlogloss:0.18069	eval-mlogloss:0.11675
[122]	train-mlogloss:0.18069	eval-mlogloss:0.11676
[123]	train-mlogloss:0.18069	eval-mlogloss:0.11676
[124]	train-mlogloss:0.18069	eval-mlogloss:0.11677
[125]	train-mlogloss:0.18069	eval-mlogloss:0.11678
[126]	train-mlogloss:0.18068	eval-mlogloss:0.11679
[127]	train-mlogloss:0.18068	eval-mlogloss:0.11679
[128]	train-mlogloss:0.18068	eval-mlogloss:0.11679
[129]	train-mlogloss:0.18032	eval-mlogloss:0.11624
[130]	train-mlogloss:0.18032	eval-mlogloss:0.11625
[131]	train-mlogloss:0.18032	eval-mlogloss:0.11626
[132]	train-mlogloss:0.18032	eval-mlogloss:0.11626
[133]	train-mlogloss:0.17996	eval-mlogloss:0.11572
[134]	train-mlogloss:0.17996	eval-mlogloss:0.11573
[135]	train-mlogloss:0.17996	eval-mlogloss:0.11572
[136]	train-mlogloss:0.17996	eval-mlogloss:0.11573
[137]	train-mlogloss:0.17996	eval-mlogloss:0.11574
[138]	train-mlogloss:0.17996	eval-mlogloss:0.11575
[139]	train-mlogloss:0.17996	eval-mlogloss:0.11575
[140]	train-mlogloss:0.17996	eval-mlogloss:0.11576
[141]	train-mlogloss:0.17996	eval-mlogloss:0.11576
[142]	train-mlogloss:0.17996	eval-mlogloss:0.11577
[143]	train-mlogloss:0.17996	eval-mlogloss:0.11577
[144]	train-mlogloss:0.17996	eval-mlogloss:0.11578
[145]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[146]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[147]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[148]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[149]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[150]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[151]	train-mlogloss:0.17995	eval-mlogloss:0.11578
[152]	train-mlogloss:0.17995	eval-mlogloss:0.11579
[153]	train-mlogloss:0.17995	eval-mlogloss:0.11579
[154]	train-mlogloss:0.17995	eval-mlogloss:0.11579
[155]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[156]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[157]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[158]	train-mlogloss:0.17995	eval-mlogloss:0.11580
[159]	train-mlogloss:0.17995	eval-mlogloss:0.11581
[160]	train-mlogloss:0.17995	eval-mlogloss:0.11583
[161]	train-mlogloss:0.17995	eval-mlogloss:0.11583
[162]	train-mlogloss:0.17995	eval-mlogloss:0.11583
[163]	train-mlogloss:0.17995	eval-mlogloss:0.11583

[I 2026-05-06 16:09:05,497] Trial 10 finished with value: 1.0 and parameters: {'lambda': 6.74862121769391e-06, 'alpha': 0.002460426908416612, 'eta': 0.03350192952122644, 'gamma': 0.7502306004968524, 'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.9812946794236702, 'colsample_bytree': 0.5484066659059424}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00039	eval-mlogloss:1.01842
[1]	train-mlogloss:0.79945	eval-mlogloss:0.79974

[I 2026-05-06 16:09:05,606] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94842	eval-mlogloss:0.95423
[1]	train-mlogloss:0.77037	eval-mlogloss:0.76622

[I 2026-05-06 16:09:05,736] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95971	eval-mlogloss:0.98519
[1]	train-mlogloss:0.71720	eval-mlogloss:0.73025

[I 2026-05-06 16:09:05,943] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88826	eval-mlogloss:0.87006
[1]	train-mlogloss:0.73262	eval-mlogloss:0.70774

[I 2026-05-06 16:09:06,096] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05678	eval-mlogloss:1.05923
[1]	train-mlogloss:1.00904	eval-mlogloss:1.00612
[2]	train-mlogloss:0.95791	eval-mlogloss:0.95264
[3]	train-mlogloss:0.91940	eval-mlogloss:0.91242
[4]	train-mlogloss:0.87971	eval-mlogloss:0.87248
[5]	train-mlogloss:0.82547	eval-mlogloss:0.81462
[6]	train-mlogloss:0.78183	eval-mlogloss:0.77109
[7]	train-mlogloss:0.76239	eval-mlogloss:0.75067

[I 2026-05-06 16:09:06,351] Trial 15 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.95265	eval-mlogloss:0.95305
[1]	train-mlogloss:0.77829	eval-mlogloss:0.76332

[I 2026-05-06 16:09:06,469] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.88256	eval-mlogloss:0.87784
[1]	train-mlogloss:0.66863	eval-mlogloss:0.65203

[I 2026-05-06 16:09:06,600] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03410	eval-mlogloss:1.03610
[1]	train-mlogloss:0.95049	eval-mlogloss:0.94590
[2]	train-mlogloss:0.85986	eval-mlogloss:0.84996
[3]	train-mlogloss:0.77814	eval-mlogloss:0.76320
[4]	train-mlogloss:0.70970	eval-mlogloss:0.69058
[5]	train-mlogloss:0.64647	eval-mlogloss:0.62120
[6]	train-mlogloss:0.59439	eval-mlogloss:0.56720
[7]	train-mlogloss:0.55339	eval-mlogloss:0.52815

[I 2026-05-06 16:09:06,812] Trial 18 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.02122	eval-mlogloss:1.03130
[1]	train-mlogloss:0.86030	eval-mlogloss:0.86142

[I 2026-05-06 16:09:06,927] Trial 19 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08106	eval-mlogloss:1.08229
[1]	train-mlogloss:1.03443	eval-mlogloss:1.03337
[2]	train-mlogloss:0.99080	eval-mlogloss:0.98747
[3]	train-mlogloss:0.96001	eval-mlogloss:0.95167
[4]	train-mlogloss:0.92747	eval-mlogloss:0.91619
[5]	train-mlogloss:0.88896	eval-mlogloss:0.87576
[6]	train-mlogloss:0.86221	eval-mlogloss:0.84902
[7]	train-mlogloss:0.84258	eval-mlogloss:0.82899
[8]	train-mlogloss:0.81008	eval-mlogloss:0.79431
[9]	train-mlogloss:0.78627	eval-mlogloss:0.77043
[10]	train-mlogloss:0.75739	eval-mlogloss:0.73915
[11]	train-mlogloss:0.73234	eval-mlogloss:0.71219
[12]	train-mlogloss:0.72307	eval-mlogloss:0.70313
[13]	train-mlogloss:0.69662	eval-mlogloss:0.67407
[14]	train-mlogloss:0.68952	eval-mlogloss:0.66758
[15]	train-mlogloss:0.67530	eval-mlogloss:0.65410
[16]	train-mlogloss:0.65999	eval-mlogloss:0.63662
[17]	train-mlogloss:0.64256	eval-mlogloss:0.61707
[18]	train-mlogloss:0.63002	eval-mlogloss:0.60496
[19]	train-mlogloss:0.61936	eval-mlogloss:0.59381
[20]	train-mlogloss:0.60371	eval-mlogloss:0.57603
[21]	train-mlogloss:0.59187	eval-mlogloss:0.56313
[22]	train-mlogloss:0.58013	eval-mlogloss:0.55135
[23]	train-mlogloss:0.56031	eval-mlogloss:0.53042
[24]	train-mlogloss:0.55045	eval-mlogloss:0.51931
[25]	train-mlogloss:0.53791	eval-mlogloss:0.50517
[26]	train-mlogloss:0.52613	eval-mlogloss:0.49245
[27]	train-mlogloss:0.52281	eval-mlogloss:0.49018
[28]	train-mlogloss:0.51844	eval-mlogloss:0.48568
[29]	train-mlogloss:0.50675	eval-mlogloss:0.47238
[30]	train-mlogloss:0.49544	eval-mlogloss:0.46013
[31]	train-mlogloss:0.49258	eval-mlogloss:0.45803
[32]	train-mlogloss:0.48665	eval-mlogloss:0.45130
[33]	train-mlogloss:0.48036	eval-mlogloss:0.44346
[34]	train-mlogloss:0.46839	eval-mlogloss:0.43001
[35]	train-mlogloss:0.46163	eval-mlogloss:0.42340
[36]	train-mlogloss:0.45672	eval-mlogloss:0.41860
[37]	train-mlogloss:0.44837	eval-mlogloss:0.40968
[38]	train-mlogloss:0.44286	eval-mlogloss:0.40395
[39]	train-mlogloss:0.43685	eval-mlogloss:0.39809
[40]	train-mlogloss:0.43352	eval-mlogloss:0.39457
[41]	train-mlogloss:0.42511	eval-mlogloss:0.38505
[42]	train-mlogloss:0.42370	eval-mlogloss:0.38331
[43]	train-mlogloss:0.41714	eval-mlogloss:0.37563
[44]	train-mlogloss:0.40843	eval-mlogloss:0.36510
[45]	train-mlogloss:0.40513	eval-mlogloss:0.36126
[46]	train-mlogloss:0.39710	eval-mlogloss:0.35218
[47]	train-mlogloss:0.39253	eval-mlogloss:0.34728
[48]	train-mlogloss:0.38652	eval-mlogloss:0.34093
[49]	train-mlogloss:0.37967	eval-mlogloss:0.33384
[50]	train-mlogloss:0.37400	eval-mlogloss:0.32730
[51]	train-mlogloss:0.37173	eval-mlogloss:0.32509
[52]	train-mlogloss:0.36995	eval-mlogloss:0.32313
[53]	train-mlogloss:0.36583	eval-mlogloss:0.31817
[54]	train-mlogloss:0.36485	eval-mlogloss:0.31731
[55]	train-mlogloss:0.35753	eval-mlogloss:0.30937
[56]	train-mlogloss:0.35277	eval-mlogloss:0.30430
[57]	train-mlogloss:0.34630	eval-mlogloss:0.29712
[58]	train-mlogloss:0.34297	eval-mlogloss:0.29363
[59]	train-mlogloss:0.34125	eval-mlogloss:0.29196
[60]	train-mlogloss:0.33900	eval-mlogloss:0.28960
[61]	train-mlogloss:0.33743	eval-mlogloss:0.28816
[62]	train-mlogloss:0.33202	eval-mlogloss:0.28249
[63]	train-mlogloss:0.33203	eval-mlogloss:0.28243
[64]	train-mlogloss:0.33168	eval-mlogloss:0.28142
[65]	train-mlogloss:0.32807	eval-mlogloss:0.27693
[66]	train-mlogloss:0.32541	eval-mlogloss:0.27504
[67]	train-mlogloss:0.32308	eval-mlogloss:0.27203
[68]	train-mlogloss:0.32254	eval-mlogloss:0.27110
[69]	train-mlogloss:0.31977	eval-mlogloss:0.26774
[70]	train-mlogloss:0.31924	eval-mlogloss:0.26695
[71]	train-mlogloss:0.31887	eval-mlogloss:0.26679
[72]	train-mlogloss:0.31649	eval-mlogloss:0.26356
[73]	train-mlogloss:0.31651	eval-mlogloss:0.26349
[74]	train-mlogloss:0.31621	eval-mlogloss:0.26326
[75]	train-mlogloss:0.31431	eval-mlogloss:0.26079
[76]	train-mlogloss:0.31225	eval-mlogloss:0.25802
[77]	train-mlogloss:0.31225	eval-mlogloss:0.25805
[78]	train-mlogloss:0.31224	eval-mlogloss:0.25810
[79]	train-mlogloss:0.31223	eval-mlogloss:0.25814
[80]	train-mlogloss:0.31010	eval-mlogloss:0.25558
[81]	train-mlogloss:0.31009	eval-mlogloss:0.25567
[82]	train-mlogloss:0.31009	eval-mlogloss:0.25573
[83]	train-mlogloss:0.31009	eval-mlogloss:0.25572
[84]	train-mlogloss:0.31009	eval-mlogloss:0.25574
[85]	train-mlogloss:0.31009	eval-mlogloss:0.25572
[86]	train-mlogloss:0.30782	eval-mlogloss:0.25291
[87]	train-mlogloss:0.30698	eval-mlogloss:0.25252
[88]	train-mlogloss:0.30557	eval-mlogloss:0.25114
[89]	train-mlogloss:0.30507	eval-mlogloss:0.25017
[90]	train-mlogloss:0.30508	eval-mlogloss:0.25020
[91]	train-mlogloss:0.30509	eval-mlogloss:0.25020
[92]	train-mlogloss:0.30331	eval-mlogloss:0.24780
[93]	train-mlogloss:0.30330	eval-mlogloss:0.24777
[94]	train-mlogloss:0.30331	eval-mlogloss:0.24783
[95]	train-mlogloss:0.30332	eval-mlogloss:0.24785
[96]	train-mlogloss:0.30333	eval-mlogloss:0.24784
[97]	train-mlogloss:0.30334	eval-mlogloss:0.24784
[98]	train-mlogloss:0.30306	eval-mlogloss:0.24742
[99]	train-mlogloss:0.30306	eval-mlogloss:0.24734
[100]	train-mlogloss:0.30085	eval-mlogloss:0.24494
[101]	train-mlogloss:0.29896	eval-mlogloss:0.24274
[102]	train-mlogloss:0.29896	eval-mlogloss:0.24271
[103]	train-mlogloss:0.29750	eval-mlogloss:0.24076
[104]	train-mlogloss:0.29750	eval-mlogloss:0.24083
[105]	train-mlogloss:0.29748	eval-mlogloss:0.24079
[106]	train-mlogloss:0.29661	eval-mlogloss:0.23966
[107]	train-mlogloss:0.29661	eval-mlogloss:0.23978
[108]	train-mlogloss:0.29660	eval-mlogloss:0.23974
[109]	train-mlogloss:0.29660	eval-mlogloss:0.23971
[110]	train-mlogloss:0.29661	eval-mlogloss:0.23974
[111]	train-mlogloss:0.29662	eval-mlogloss:0.23973
[112]	train-mlogloss:0.29661	eval-mlogloss:0.23973
[113]	train-mlogloss:0.29500	eval-mlogloss:0.23783
[114]	train-mlogloss:0.29501	eval-mlogloss:0.23783
[115]	train-mlogloss:0.29501	eval-mlogloss:0.23779
[116]	train-mlogloss:0.29501	eval-mlogloss:0.23782
[117]	train-mlogloss:0.29485	eval-mlogloss:0.23761
[118]	train-mlogloss:0.29482	eval-mlogloss:0.23769
[119]	train-mlogloss:0.29382	eval-mlogloss:0.23668
[120]	train-mlogloss:0.29238	eval-mlogloss:0.23471
[121]	train-mlogloss:0.29239	eval-mlogloss:0.23471
[122]	train-mlogloss:0.29239	eval-mlogloss:0.23476
[123]	train-mlogloss:0.29240	eval-mlogloss:0.23474
[124]	train-mlogloss:0.29239	eval-mlogloss:0.23473
[125]	train-mlogloss:0.29238	eval-mlogloss:0.23481
[126]	train-mlogloss:0.29237	eval-mlogloss:0.23491
[127]	train-mlogloss:0.29239	eval-mlogloss:0.23487
[128]	train-mlogloss:0.29239	eval-mlogloss:0.23485
[129]	train-mlogloss:0.29072	eval-mlogloss:0.23295
[130]	train-mlogloss:0.29073	eval-mlogloss:0.23293
[131]	train-mlogloss:0.29073	eval-mlogloss:0.23296
[132]	train-mlogloss:0.29072	eval-mlogloss:0.23288
[133]	train-mlogloss:0.29035	eval-mlogloss:0.23227
[134]	train-mlogloss:0.29034	eval-mlogloss:0.23229
[135]	train-mlogloss:0.28855	eval-mlogloss:0.23007
[136]	train-mlogloss:0.28855	eval-mlogloss:0.23009
[137]	train-mlogloss:0.28856	eval-mlogloss:0.23002
[138]	train-mlogloss:0.28855	eval-mlogloss:0.23004
[139]	train-mlogloss:0.28855	eval-mlogloss:0.23002
[140]	train-mlogloss:0.28854	eval-mlogloss:0.23002
[141]	train-mlogloss:0.28855	eval-mlogloss:0.23002
[142]	train-mlogloss:0.28857	eval-mlogloss:0.23003
[143]	train-mlogloss:0.28857	eval-mlogloss:0.23003
[144]	train-mlogloss:0.28857	eval-mlogloss:0.23006
[145]	train-mlogloss:0.28858	eval-mlogloss:0.23012
[146]	train-mlogloss:0.28858	eval-mlogloss:0.23012
[147]	train-mlogloss:0.28857	eval-mlogloss:0.23013
[148]	train-mlogloss:0.28858	eval-mlogloss:0.23021
[149]	train-mlogloss:0.28858	eval-mlogloss:0.23020
[150]	train-mlogloss:0.28857	eval-mlogloss:0.23016
[151]	train-mlogloss:0.28857	eval-mlogloss:0.23009
[152]	train-mlogloss:0.28857	eval-mlogloss:0.23006
[153]	train-mlogloss:0.28857	eval-mlogloss:0.23003
[154]	train-mlogloss:0.28858	eval-mlogloss:0.22989
[155]	train-mlogloss:0.28858	eval-mlogloss:0.22984
[156]	train-mlogloss:0.28861	eval-mlogloss:0.22975
[157]	train-mlogloss:0.28861	eval-mlogloss:0.22971
[158]	train-mlogloss:0.28860	eval-mlogloss:0.22977
[159]	train-mlogloss:0.28829	eval-mlogloss:0.22962
[160]	train-mlogloss:0.28828	eval-mlogloss:0.22965
[161]	train-mlogloss:0.28828	eval-mlogloss:0.22966
[162]	train-mlogloss:0.28826	eval-mlogloss:0.22971
[163]	train-mlogloss:0.28825	eval-mlogloss:0.22975
[164]	train-mlogloss:0.28827	eval-mlogloss:0.22975
[165]	train-mlogloss:0.28655	eval-mlogloss:0.22766
[166]	train-mlogloss:0.28463	eval-mlogloss:0.22521
[167]	train-mlogloss:0.28463	eval-mlogloss:0.22524
[168]	train-mlogloss:0.28464	eval-mlogloss:0.22522
[169]	train-mlogloss:0.28463	eval-mlogloss:0.22522
[170]	train-mlogloss:0.28463	eval-mlogloss:0.22524
[171]	train-mlogloss:0.28463	eval-mlogloss:0.22531
[172]	train-mlogloss:0.28464	eval-mlogloss:0.22525
[173]	train-mlogloss:0.28464	eval-mlogloss:0.22527
[174]	train-mlogloss:0.28464	eval-mlogloss:0.22537
[175]	train-mlogloss:0.28465	eval-mlogloss:0.22533
[176]	train-mlogloss:0.28346	eval-mlogloss:0.22357
[177]	train-mlogloss:0.28345	eval-mlogloss:0.22355
[178]	train-mlogloss:0.28344	eval-mlogloss:0.22357
[179]	train-mlogloss:0.28344	eval-mlogloss:0.22352
[180]	train-mlogloss:0.28346	eval-mlogloss:0.22349
[181]	train-mlogloss:0.28345	eval-mlogloss:0.22350
[182]	train-mlogloss:0.28345	eval-mlogloss:0.22343
[183]	train-mlogloss:0.28345	eval-mlogloss:0.22355
[184]	train-mlogloss:0.28344	eval-mlogloss:0.22352
[185]	train-mlogloss:0.28345	eval-mlogloss:0.22351
[186]	train-mlogloss:0.28345	eval-mlogloss:0.22345
[187]	train-mlogloss:0.28345	eval-mlogloss:0.22342
[188]	train-mlogloss:0.28345	eval-mlogloss:0.22349
[189]	train-mlogloss:0.28345	eval-mlogloss:0.22357
[190]	train-mlogloss:0.28344	eval-mlogloss:0.22370
[191]	train-mlogloss:0.28343	eval-mlogloss:0.22370
[192]	train-mlogloss:0.28342	eval-mlogloss:0.22375
[193]	train-mlogloss:0.28342	eval-mlogloss:0.22374
[194]	train-mlogloss:0.28341	eval-mlogloss:0.22379
[195]	train-mlogloss:0.28342	eval-mlogloss:0.22369
[196]	train-mlogloss:0.28342	eval-mlogloss:0.22369
[197]	train-mlogloss:0.28341	eval-mlogloss:0.22364
[198]	train-mlogloss:0.28342	eval-mlogloss:0.22355
[199]	train-mlogloss:0.28342	eval-mlogloss:0.22355
[200]	train-mlogloss:0.28342	eval-mlogloss:0.22353
[201]	train-mlogloss:0.28343	eval-mlogloss:0.22345
[202]	train-mlogloss:0.28342	eval-mlogloss:0.22347
[203]	train-mlogloss:0.28341	eval-mlogloss:0.22353
[204]	train-mlogloss:0.28341	eval-mlogloss:0.22354
[205]	train-mlogloss:0.28341	eval-mlogloss:0.22352
[206]	train-mlogloss:0.28340	eval-mlogloss:0.22361
[207]	train-mlogloss:0.28340	eval-mlogloss:0.22360
[208]	train-mlogloss:0.28339	eval-mlogloss:0.22369
[209]	train-mlogloss:0.28182	eval-mlogloss:0.22176
[210]	train-mlogloss:0.28155	eval-mlogloss:0.22092
[211]	train-mlogloss:0.28155	eval-mlogloss:0.22093
[212]	train-mlogloss:0.28155	eval-mlogloss:0.22088
[213]	train-mlogloss:0.28155	eval-mlogloss:0.22090
[214]	train-mlogloss:0.28155	eval-mlogloss:0.22086
[215]	train-mlogloss:0.28155	eval-mlogloss:0.22089
[216]	train-mlogloss:0.28156	eval-mlogloss:0.22086
[217]	train-mlogloss:0.28155	eval-mlogloss:0.22088
[218]	train-mlogloss:0.28155	eval-mlogloss:0.22091
[219]	train-mlogloss:0.28156	eval-mlogloss:0.22085
[220]	train-mlogloss:0.28155	eval-mlogloss:0.22090
[221]	train-mlogloss:0.28116	eval-mlogloss:0.22066
[222]	train-mlogloss:0.28117	eval-mlogloss:0.22064
[223]	train-mlogloss:0.28116	eval-mlogloss:0.22072
[224]	train-mlogloss:0.28116	eval-mlogloss:0.22072
[225]	train-mlogloss:0.28081	eval-mlogloss:0.22011
[226]	train-mlogloss:0.28081	eval-mlogloss:0.22004
[227]	train-mlogloss:0.28081	eval-mlogloss:0.22006
[228]	train-mlogloss:0.28081	eval-mlogloss:0.22006
[229]	train-mlogloss:0.28051	eval-mlogloss:0.21995
[230]	train-mlogloss:0.28051	eval-mlogloss:0.21994
[231]	train-mlogloss:0.28052	eval-mlogloss:0.21991
[232]	train-mlogloss:0.28051	eval-mlogloss:0.21996
[233]	train-mlogloss:0.28051	eval-mlogloss:0.21999
[234]	train-mlogloss:0.28051	eval-mlogloss:0.22007
[235]	train-mlogloss:0.28051	eval-mlogloss:0.22006
[236]	train-mlogloss:0.28051	eval-mlogloss:0.22013
[237]	train-mlogloss:0.28051	eval-mlogloss:0.22024
[238]	train-mlogloss:0.28052	eval-mlogloss:0.22030
[239]	train-mlogloss:0.28051	eval-mlogloss:0.22029
[240]	train-mlogloss:0.28052	eval-mlogloss:0.22038
[241]	train-mlogloss:0.28051	eval-mlogloss:0.22036
[242]	train-mlogloss:0.28052	eval-mlogloss:0.22037
[243]	train-mlogloss:0.28051	eval-mlogloss:0.22032
[244]	train-mlogloss:0.28050	eval-mlogloss:0.22028
[245]	train-mlogloss:0.28050	eval-mlogloss:0.22028
[246]	train-mlogloss:0.28049	eval-mlogloss:0.22016
[247]	train-mlogloss:0.28050	eval-mlogloss:0.22013
[248]	train-mlogloss:0.28050	eval-mlogloss:0.22014
[249]	train-mlogloss:0.28049	eval-mlogloss:0.22013
[250]	train-mlogloss:0.28050	eval-mlogloss:0.22003
[251]	train-mlogloss:0.28049	eval-mlogloss:0.22007
[252]	train-mlogloss:0.28050	eval-mlogloss:0.21999
[253]	train-mlogloss:0.28050	eval-mlogloss:0.22002
[254]	train-mlogloss:0.28049	eval-mlogloss:0.22006
[255]	train-mlogloss:0.28049	eval-mlogloss:0.22006
[256]	train-mlogloss:0.28050	eval-mlogloss:0.22001
[257]	train-mlogloss:0.28050	eval-mlogloss:0.22000
[258]	train-mlogloss:0.28050	eval-mlogloss:0.21998
[259]	train-mlogloss:0.28050	eval-mlogloss:0.21998
[260]	train-mlogloss:0.28050	eval-mlogloss:0.21996
[261]	train-mlogloss:0.28051	eval-mlogloss:0.21993

[I 2026-05-06 16:09:13,012] Trial 20 finished with value: 1.0 and parameters: {'lambda': 1.6470706351782528e-06, 'alpha': 0.03211956280708532, 'eta': 0.0377287613814099, 'gamma': 0.9821223637929984, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.6451906350711615, 'colsample_bytree': 0.4785128393615763}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.02998	eval-mlogloss:1.02303
[1]	train-mlogloss:0.93063	eval-mlogloss:0.91903

[I 2026-05-06 16:09:13,287] Trial 21 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06734	eval-mlogloss:1.06954
[1]	train-mlogloss:0.99459	eval-mlogloss:0.99296
[2]	train-mlogloss:0.92846	eval-mlogloss:0.92369
[3]	train-mlogloss:0.88177	eval-mlogloss:0.87272
[4]	train-mlogloss:0.83546	eval-mlogloss:0.82343
[5]	train-mlogloss:0.78348	eval-mlogloss:0.76860
[6]	train-mlogloss:0.74760	eval-mlogloss:0.73299
[7]	train-mlogloss:0.72141	eval-mlogloss:0.70716

[I 2026-05-06 16:09:13,698] Trial 22 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08807	eval-mlogloss:1.09115
[1]	train-mlogloss:1.06564	eval-mlogloss:1.06771
[2]	train-mlogloss:1.04347	eval-mlogloss:1.04402
[3]	train-mlogloss:1.02663	eval-mlogloss:1.02600
[4]	train-mlogloss:1.00887	eval-mlogloss:1.00869
[5]	train-mlogloss:0.98789	eval-mlogloss:0.98645
[6]	train-mlogloss:0.97254	eval-mlogloss:0.97186
[7]	train-mlogloss:0.96079	eval-mlogloss:0.96106
[8]	train-mlogloss:0.94195	eval-mlogloss:0.94090
[9]	train-mlogloss:0.92742	eval-mlogloss:0.92657
[10]	train-mlogloss:0.90942	eval-mlogloss:0.90787
[11]	train-mlogloss:0.89378	eval-mlogloss:0.89142
[12]	train-mlogloss:0.88611	eval-mlogloss:0.88505
[13]	train-mlogloss:0.86929	eval-mlogloss:0.86679
[14]	train-mlogloss:0.86307	eval-mlogloss:0.86148
[15]	train-mlogloss:0.85271	eval-mlogloss:0.85158
[16]	train-mlogloss:0.84200	eval-mlogloss:0.84071
[17]	train-mlogloss:0.82947	eval-mlogloss:0.82813
[18]	train-mlogloss:0.82018	eval-mlogloss:0.81879
[19]	train-mlogloss:0.81082	eval-mlogloss:0.80972
[20]	train-mlogloss:0.79576	eval-mlogloss:0.79363
[21]	train-mlogloss:0.78527	eval-mlogloss:0.78266
[22]	train-mlogloss:0.77596	eval-mlogloss:0.77287
[23]	train-mlogloss:0.76148	eval-mlogloss:0.75765
[24]	train-mlogloss:0.75260	eval-mlogloss:0.74908
[25]	train-mlogloss:0.74191	eval-mlogloss:0.73818
[26]	train-mlogloss:0.73103	eval-mlogloss:0.72798
[27]	train-mlogloss:0.72680	eval-mlogloss:0.72501
[28]	train-mlogloss:0.72187	eval-mlogloss:0.72124
[29]	train-mlogloss:0.71125	eval-mlogloss:0.70975
[30]	train-mlogloss:0.70210	eval-mlogloss:0.70040
[31]	train-mlogloss:0.69835	eval-mlogloss:0.69788
[32]	train-mlogloss:0.69161	eval-mlogloss:0.69123
[33]	train-mlogloss:0.68558	eval-mlogloss:0.68510
[34]	train-mlogloss:0.67518	eval-mlogloss:0.67401
[35]	train-mlogloss:0.66835	eval-mlogloss:0.66709
[36]	train-mlogloss:0.66281	eval-mlogloss:0.66223
[37]	train-mlogloss:0.65469	eval-mlogloss:0.65414
[38]	train-mlogloss:0.64603	eval-mlogloss:0.64521
[39]	train-mlogloss:0.63854	eval-mlogloss:0.63824
[40]	train-mlogloss:0.63451	eval-mlogloss:0.63463
[41]	train-mlogloss:0.62668	eval-mlogloss:0.62612
[42]	train-mlogloss:0.62383	eval-mlogloss:0.62418
[43]	train-mlogloss:0.61606	eval-mlogloss:0.61684
[44]	train-mlogloss:0.60830	eval-mlogloss:0.60850
[45]	train-mlogloss:0.60341	eval-mlogloss:0.60410
[46]	train-mlogloss:0.59584	eval-mlogloss:0.59592
[47]	train-mlogloss:0.59017	eval-mlogloss:0.59100
[48]	train-mlogloss:0.58172	eval-mlogloss:0.58263
[49]	train-mlogloss:0.57385	eval-mlogloss:0.57499
[50]	train-mlogloss:0.56636	eval-mlogloss:0.56642
[51]	train-mlogloss:0.56169	eval-mlogloss:0.56182
[52]	train-mlogloss:0.55715	eval-mlogloss:0.55742
[53]	train-mlogloss:0.54819	eval-mlogloss:0.54719
[54]	train-mlogloss:0.54351	eval-mlogloss:0.54234
[55]	train-mlogloss:0.53472	eval-mlogloss:0.53305
[56]	train-mlogloss:0.52801	eval-mlogloss:0.52582
[57]	train-mlogloss:0.51976	eval-mlogloss:0.51648
[58]	train-mlogloss:0.51527	eval-mlogloss:0.51190
[59]	train-mlogloss:0.51228	eval-mlogloss:0.50924
[60]	train-mlogloss:0.50628	eval-mlogloss:0.50311
[61]	train-mlogloss:0.50144	eval-mlogloss:0.49772
[62]	train-mlogloss:0.49365	eval-mlogloss:0.48931
[63]	train-mlogloss:0.48969	eval-mlogloss:0.48506
[64]	train-mlogloss:0.48705	eval-mlogloss:0.48252
[65]	train-mlogloss:0.48267	eval-mlogloss:0.47831
[66]	train-mlogloss:0.47669	eval-mlogloss:0.47191
[67]	train-mlogloss:0.47209	eval-mlogloss:0.46702
[68]	train-mlogloss:0.46930	eval-mlogloss:0.46531
[69]	train-mlogloss:0.46238	eval-mlogloss:0.45763
[70]	train-mlogloss:0.45798	eval-mlogloss:0.45318
[71]	train-mlogloss:0.45098	eval-mlogloss:0.44530
[72]	train-mlogloss:0.44556	eval-mlogloss:0.43932
[73]	train-mlogloss:0.44144	eval-mlogloss:0.43511
[74]	train-mlogloss:0.43678	eval-mlogloss:0.43018
[75]	train-mlogloss:0.43126	eval-mlogloss:0.42415
[76]	train-mlogloss:0.42798	eval-mlogloss:0.42104
[77]	train-mlogloss:0.42524	eval-mlogloss:0.41857
[78]	train-mlogloss:0.42201	eval-mlogloss:0.41537
[79]	train-mlogloss:0.41934	eval-mlogloss:0.41323
[80]	train-mlogloss:0.41614	eval-mlogloss:0.41039
[81]	train-mlogloss:0.41101	eval-mlogloss:0.40487
[82]	train-mlogloss:0.40799	eval-mlogloss:0.40176
[83]	train-mlogloss:0.40371	eval-mlogloss:0.39715
[84]	train-mlogloss:0.40029	eval-mlogloss:0.39334
[85]	train-mlogloss:0.39592	eval-mlogloss:0.38838
[86]	train-mlogloss:0.39147	eval-mlogloss:0.38311
[87]	train-mlogloss:0.38692	eval-mlogloss:0.37813
[88]	train-mlogloss:0.38320	eval-mlogloss:0.37405
[89]	train-mlogloss:0.37865	eval-mlogloss:0.36946
[90]	train-mlogloss:0.37478	eval-mlogloss:0.36491
[91]	train-mlogloss:0.37186	eval-mlogloss:0.36197
[92]	train-mlogloss:0.36716	eval-mlogloss:0.35689
[93]	train-mlogloss:0.36562	eval-mlogloss:0.35588
[94]	train-mlogloss:0.36061	eval-mlogloss:0.34993
[95]	train-mlogloss:0.35625	eval-mlogloss:0.34452
[96]	train-mlogloss:0.35157	eval-mlogloss:0.33939
[97]	train-mlogloss:0.34909	eval-mlogloss:0.33680
[98]	train-mlogloss:0.34604	eval-mlogloss:0.33331
[99]	train-mlogloss:0.34498	eval-mlogloss:0.33284
[100]	train-mlogloss:0.34163	eval-mlogloss:0.32976
[101]	train-mlogloss:0.33865	eval-mlogloss:0.32631
[102]	train-mlogloss:0.33645	eval-mlogloss:0.32408
[103]	train-mlogloss:0.33196	eval-mlogloss:0.31912
[104]	train-mlogloss:0.32930	eval-mlogloss:0.31664
[105]	train-mlogloss:0.32709	eval-mlogloss:0.31443
[106]	train-mlogloss:0.32405	eval-mlogloss:0.31158
[107]	train-mlogloss:0.31959	eval-mlogloss:0.30616
[108]	train-mlogloss:0.31723	eval-mlogloss:0.30415
[109]	train-mlogloss:0.31325	eval-mlogloss:0.29946
[110]	train-mlogloss:0.31066	eval-mlogloss:0.29641
[111]	train-mlogloss:0.30751	eval-mlogloss:0.29299
[112]	train-mlogloss:0.30505	eval-mlogloss:0.29032
[113]	train-mlogloss:0.30109	eval-mlogloss:0.28546
[114]	train-mlogloss:0.29913	eval-mlogloss:0.28376
[115]	train-mlogloss:0.29654	eval-mlogloss:0.28107
[116]	train-mlogloss:0.29286	eval-mlogloss:0.27680
[117]	train-mlogloss:0.28994	eval-mlogloss:0.27375
[118]	train-mlogloss:0.28733	eval-mlogloss:0.27109
[119]	train-mlogloss:0.28519	eval-mlogloss:0.26886
[120]	train-mlogloss:0.28182	eval-mlogloss:0.26510
[121]	train-mlogloss:0.27883	eval-mlogloss:0.26203
[122]	train-mlogloss:0.27529	eval-mlogloss:0.25766
[123]	train-mlogloss:0.27232	eval-mlogloss:0.25427
[124]	train-mlogloss:0.26988	eval-mlogloss:0.25163
[125]	train-mlogloss:0.26740	eval-mlogloss:0.24892
[126]	train-mlogloss:0.26573	eval-mlogloss:0.24716
[127]	train-mlogloss:0.26407	eval-mlogloss:0.24553
[128]	train-mlogloss:0.26178	eval-mlogloss:0.24308
[129]	train-mlogloss:0.26015	eval-mlogloss:0.24115
[130]	train-mlogloss:0.25956	eval-mlogloss:0.24084
[131]	train-mlogloss:0.25638	eval-mlogloss:0.23685
[132]	train-mlogloss:0.25398	eval-mlogloss:0.23458
[133]	train-mlogloss:0.25187	eval-mlogloss:0.23237
[134]	train-mlogloss:0.25054	eval-mlogloss:0.23120
[135]	train-mlogloss:0.24818	eval-mlogloss:0.22812
[136]	train-mlogloss:0.24629	eval-mlogloss:0.22611
[137]	train-mlogloss:0.24341	eval-mlogloss:0.22294
[138]	train-mlogloss:0.24136	eval-mlogloss:0.22093
[139]	train-mlogloss:0.23997	eval-mlogloss:0.21987
[140]	train-mlogloss:0.23798	eval-mlogloss:0.21756
[141]	train-mlogloss:0.23605	eval-mlogloss:0.21556
[142]	train-mlogloss:0.23391	eval-mlogloss:0.21308
[143]	train-mlogloss:0.23117	eval-mlogloss:0.21007
[144]	train-mlogloss:0.22890	eval-mlogloss:0.20734
[145]	train-mlogloss:0.22709	eval-mlogloss:0.20510
[146]	train-mlogloss:0.22516	eval-mlogloss:0.20283
[147]	train-mlogloss:0.22342	eval-mlogloss:0.20090
[148]	train-mlogloss:0.22153	eval-mlogloss:0.19884
[149]	train-mlogloss:0.22079	eval-mlogloss:0.19827
[150]	train-mlogloss:0.21854	eval-mlogloss:0.19566
[151]	train-mlogloss:0.21629	eval-mlogloss:0.19287
[152]	train-mlogloss:0.21521	eval-mlogloss:0.19176
[153]	train-mlogloss:0.21358	eval-mlogloss:0.19019
[154]	train-mlogloss:0.21109	eval-mlogloss:0.18745
[155]	train-mlogloss:0.20949	eval-mlogloss:0.18598
[156]	train-mlogloss:0.20766	eval-mlogloss:0.18401
[157]	train-mlogloss:0.20664	eval-mlogloss:0.18303
[158]	train-mlogloss:0.20466	eval-mlogloss:0.18068
[159]	train-mlogloss:0.20361	eval-mlogloss:0.17958
[160]	train-mlogloss:0.20197	eval-mlogloss:0.17776
[161]	train-mlogloss:0.19985	eval-mlogloss:0.17551
[162]	train-mlogloss:0.19894	eval-mlogloss:0.17449
[163]	train-mlogloss:0.19809	eval-mlogloss:0.17341
[164]	train-mlogloss:0.19757	eval-mlogloss:0.17306
[165]	train-mlogloss:0.19659	eval-mlogloss:0.17184
[166]	train-mlogloss:0.19463	eval-mlogloss:0.16955
[167]	train-mlogloss:0.19264	eval-mlogloss:0.16706
[168]	train-mlogloss:0.19125	eval-mlogloss:0.16551
[169]	train-mlogloss:0.19029	eval-mlogloss:0.16510
[170]	train-mlogloss:0.18985	eval-mlogloss:0.16499
[171]	train-mlogloss:0.18843	eval-mlogloss:0.16339
[172]	train-mlogloss:0.18796	eval-mlogloss:0.16305
[173]	train-mlogloss:0.18713	eval-mlogloss:0.16235
[174]	train-mlogloss:0.18606	eval-mlogloss:0.16123
[175]	train-mlogloss:0.18500	eval-mlogloss:0.16027
[176]	train-mlogloss:0.18351	eval-mlogloss:0.15852
[177]	train-mlogloss:0.18298	eval-mlogloss:0.15818
[178]	train-mlogloss:0.18171	eval-mlogloss:0.15701
[179]	train-mlogloss:0.18093	eval-mlogloss:0.15618
[180]	train-mlogloss:0.17952	eval-mlogloss:0.15434
[181]	train-mlogloss:0.17823	eval-mlogloss:0.15302
[182]	train-mlogloss:0.17745	eval-mlogloss:0.15228
[183]	train-mlogloss:0.17714	eval-mlogloss:0.15210
[184]	train-mlogloss:0.17598	eval-mlogloss:0.15083
[185]	train-mlogloss:0.17469	eval-mlogloss:0.14949
[186]	train-mlogloss:0.17348	eval-mlogloss:0.14842
[187]	train-mlogloss:0.17242	eval-mlogloss:0.14725
[188]	train-mlogloss:0.17126	eval-mlogloss:0.14563
[189]	train-mlogloss:0.16969	eval-mlogloss:0.14389
[190]	train-mlogloss:0.16896	eval-mlogloss:0.14295
[191]	train-mlogloss:0.16797	eval-mlogloss:0.14168
[192]	train-mlogloss:0.16708	eval-mlogloss:0.14069
[193]	train-mlogloss:0.16617	eval-mlogloss:0.13963
[194]	train-mlogloss:0.16520	eval-mlogloss:0.13849
[195]	train-mlogloss:0.16382	eval-mlogloss:0.13689
[196]	train-mlogloss:0.16267	eval-mlogloss:0.13594
[197]	train-mlogloss:0.16119	eval-mlogloss:0.13375
[198]	train-mlogloss:0.16067	eval-mlogloss:0.13315
[199]	train-mlogloss:0.15993	eval-mlogloss:0.13238
[200]	train-mlogloss:0.15907	eval-mlogloss:0.13149
[201]	train-mlogloss:0.15859	eval-mlogloss:0.13088
[202]	train-mlogloss:0.15799	eval-mlogloss:0.13012
[203]	train-mlogloss:0.15705	eval-mlogloss:0.12915
[204]	train-mlogloss:0.15642	eval-mlogloss:0.12878
[205]	train-mlogloss:0.15589	eval-mlogloss:0.12822
[206]	train-mlogloss:0.15510	eval-mlogloss:0.12741
[207]	train-mlogloss:0.15430	eval-mlogloss:0.12650
[208]	train-mlogloss:0.15344	eval-mlogloss:0.12565
[209]	train-mlogloss:0.15224	eval-mlogloss:0.12400
[210]	train-mlogloss:0.15204	eval-mlogloss:0.12378
[211]	train-mlogloss:0.15154	eval-mlogloss:0.12351
[212]	train-mlogloss:0.15067	eval-mlogloss:0.12279
[213]	train-mlogloss:0.14962	eval-mlogloss:0.12151
[214]	train-mlogloss:0.14866	eval-mlogloss:0.12021
[215]	train-mlogloss:0.14752	eval-mlogloss:0.11859
[216]	train-mlogloss:0.14690	eval-mlogloss:0.11792
[217]	train-mlogloss:0.14586	eval-mlogloss:0.11647
[218]	train-mlogloss:0.14553	eval-mlogloss:0.11638
[219]	train-mlogloss:0.14440	eval-mlogloss:0.11498
[220]	train-mlogloss:0.14392	eval-mlogloss:0.11463
[221]	train-mlogloss:0.14339	eval-mlogloss:0.11426
[222]	train-mlogloss:0.14291	eval-mlogloss:0.11390
[223]	train-mlogloss:0.14234	eval-mlogloss:0.11337
[224]	train-mlogloss:0.14158	eval-mlogloss:0.11245
[225]	train-mlogloss:0.14133	eval-mlogloss:0.11222
[226]	train-mlogloss:0.14073	eval-mlogloss:0.11157
[227]	train-mlogloss:0.14045	eval-mlogloss:0.11132
[228]	train-mlogloss:0.13978	eval-mlogloss:0.11081
[229]	train-mlogloss:0.13920	eval-mlogloss:0.11010
[230]	train-mlogloss:0.13904	eval-mlogloss:0.11005
[231]	train-mlogloss:0.13851	eval-mlogloss:0.10938
[232]	train-mlogloss:0.13826	eval-mlogloss:0.10950
[233]	train-mlogloss:0.13766	eval-mlogloss:0.10886
[234]	train-mlogloss:0.13671	eval-mlogloss:0.10749
[235]	train-mlogloss:0.13606	eval-mlogloss:0.10657
[236]	train-mlogloss:0.13552	eval-mlogloss:0.10589
[237]	train-mlogloss:0.13502	eval-mlogloss:0.10532
[238]	train-mlogloss:0.13449	eval-mlogloss:0.10465
[239]	train-mlogloss:0.13384	eval-mlogloss:0.10384
[240]	train-mlogloss:0.13294	eval-mlogloss:0.10255
[241]	train-mlogloss:0.13244	eval-mlogloss:0.10232
[242]	train-mlogloss:0.13190	eval-mlogloss:0.10168
[243]	train-mlogloss:0.13160	eval-mlogloss:0.10131
[244]	train-mlogloss:0.13118	eval-mlogloss:0.10121
[245]	train-mlogloss:0.13062	eval-mlogloss:0.10043
[246]	train-mlogloss:0.13042	eval-mlogloss:0.10020
[247]	train-mlogloss:0.13028	eval-mlogloss:0.10011
[248]	train-mlogloss:0.13012	eval-mlogloss:0.10016
[249]	train-mlogloss:0.12950	eval-mlogloss:0.09924
[250]	train-mlogloss:0.12884	eval-mlogloss:0.09843
[251]	train-mlogloss:0.12837	eval-mlogloss:0.09775
[252]	train-mlogloss:0.12799	eval-mlogloss:0.09733
[253]	train-mlogloss:0.12760	eval-mlogloss:0.09690
[254]	train-mlogloss:0.12709	eval-mlogloss:0.09625
[255]	train-mlogloss:0.12678	eval-mlogloss:0.09606
[256]	train-mlogloss:0.12626	eval-mlogloss:0.09551
[257]	train-mlogloss:0.12580	eval-mlogloss:0.09485
[258]	train-mlogloss:0.12551	eval-mlogloss:0.09450
[259]	train-mlogloss:0.12535	eval-mlogloss:0.09449
[260]	train-mlogloss:0.12502	eval-mlogloss:0.09460
[261]	train-mlogloss:0.12451	eval-mlogloss:0.09399
[262]	train-mlogloss:0.12401	eval-mlogloss:0.09346
[263]	train-mlogloss:0.12349	eval-mlogloss:0.09303
[264]	train-mlogloss:0.12325	eval-mlogloss:0.09305
[265]	train-mlogloss:0.12291	eval-mlogloss:0.09275
[266]	train-mlogloss:0.12242	eval-mlogloss:0.09206
[267]	train-mlogloss:0.12200	eval-mlogloss:0.09182
[268]	train-mlogloss:0.12162	eval-mlogloss:0.09129
[269]	train-mlogloss:0.12110	eval-mlogloss:0.09041
[270]	train-mlogloss:0.12054	eval-mlogloss:0.08989
[271]	train-mlogloss:0.12038	eval-mlogloss:0.08978
[272]	train-mlogloss:0.11965	eval-mlogloss:0.08873
[273]	train-mlogloss:0.11944	eval-mlogloss:0.08850
[274]	train-mlogloss:0.11918	eval-mlogloss:0.08835
[275]	train-mlogloss:0.11859	eval-mlogloss:0.08746
[276]	train-mlogloss:0.11844	eval-mlogloss:0.08716
[277]	train-mlogloss:0.11809	eval-mlogloss:0.08667
[278]	train-mlogloss:0.11772	eval-mlogloss:0.08613
[279]	train-mlogloss:0.11720	eval-mlogloss:0.08549
[280]	train-mlogloss:0.11684	eval-mlogloss:0.08500
[281]	train-mlogloss:0.11642	eval-mlogloss:0.08452
[282]	train-mlogloss:0.11589	eval-mlogloss:0.08379
[283]	train-mlogloss:0.11579	eval-mlogloss:0.08372
[284]	train-mlogloss:0.11527	eval-mlogloss:0.08288
[285]	train-mlogloss:0.11501	eval-mlogloss:0.08273
[286]	train-mlogloss:0.11470	eval-mlogloss:0.08231
[287]	train-mlogloss:0.11432	eval-mlogloss:0.08175
[288]	train-mlogloss:0.11422	eval-mlogloss:0.08171
[289]	train-mlogloss:0.11398	eval-mlogloss:0.08148
[290]	train-mlogloss:0.11364	eval-mlogloss:0.08112
[291]	train-mlogloss:0.11345	eval-mlogloss:0.08090
[292]	train-mlogloss:0.11336	eval-mlogloss:0.08091
[293]	train-mlogloss:0.11310	eval-mlogloss:0.08068
[294]	train-mlogloss:0.11285	eval-mlogloss:0.08035
[295]	train-mlogloss:0.11259	eval-mlogloss:0.08004
[296]	train-mlogloss:0.11237	eval-mlogloss:0.07974
[297]	train-mlogloss:0.11208	eval-mlogloss:0.07936
[298]	train-mlogloss:0.11194	eval-mlogloss:0.07905
[299]	train-mlogloss:0.11172	eval-mlogloss:0.07856

[I 2026-05-06 16:09:24,486] Trial 23 finished with value: 1.0 and parameters: {'lambda': 0.11143951343530697, 'alpha': 0.0006445656001925672, 'eta': 0.01766578946175449, 'gamma': 1.0667585969767582e-05, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.6737421136656657, 'colsample_bytree': 0.4941104451468695}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.03964	eval-mlogloss:1.04006
[1]	train-mlogloss:0.95762	eval-mlogloss:0.95373

[I 2026-05-06 16:09:24,584] Trial 24 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.94160	eval-mlogloss:0.95977
[1]	train-mlogloss:0.78188	eval-mlogloss:0.76603

[I 2026-05-06 16:09:24,679] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00513	eval-mlogloss:1.00407
[1]	train-mlogloss:0.81034	eval-mlogloss:0.80036

[I 2026-05-06 16:09:24,872] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02990	eval-mlogloss:1.04388
[1]	train-mlogloss:0.89524	eval-mlogloss:0.90161

[I 2026-05-06 16:09:25,102] Trial 27 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.97894	eval-mlogloss:0.97247
[1]	train-mlogloss:0.82483	eval-mlogloss:0.80610

[I 2026-05-06 16:09:25,212] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91559	eval-mlogloss:0.90836
[1]	train-mlogloss:0.70496	eval-mlogloss:0.68632

[I 2026-05-06 16:09:25,326] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.92471	eval-mlogloss:0.92410
[1]	train-mlogloss:0.73446	eval-mlogloss:0.71775

[I 2026-05-06 16:09:25,427] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06196	eval-mlogloss:1.06576
[1]	train-mlogloss:1.00979	eval-mlogloss:1.01154
[2]	train-mlogloss:0.96165	eval-mlogloss:0.96165
[3]	train-mlogloss:0.91608	eval-mlogloss:0.91496
[4]	train-mlogloss:0.87387	eval-mlogloss:0.87174
[5]	train-mlogloss:0.83435	eval-mlogloss:0.82993
[6]	train-mlogloss:0.79790	eval-mlogloss:0.79231
[7]	train-mlogloss:0.76354	eval-mlogloss:0.75612

[I 2026-05-06 16:09:25,606] Trial 31 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.08836	eval-mlogloss:1.09057
[1]	train-mlogloss:1.07372	eval-mlogloss:1.07536
[2]	train-mlogloss:1.05936	eval-mlogloss:1.06017
[3]	train-mlogloss:1.04518	eval-mlogloss:1.04553
[4]	train-mlogloss:1.03128	eval-mlogloss:1.03096
[5]	train-mlogloss:1.01757	eval-mlogloss:1.01665
[6]	train-mlogloss:1.00430	eval-mlogloss:1.00305
[7]	train-mlogloss:0.99119	eval-mlogloss:0.98938
[8]	train-mlogloss:0.97844	eval-mlogloss:0.97631
[9]	train-mlogloss:0.96580	eval-mlogloss:0.96311
[10]	train-mlogloss:0.95342	eval-mlogloss:0.95034
[11]	train-mlogloss:0.94139	eval-mlogloss:0.93800
[12]	train-mlogloss:0.93403	eval-mlogloss:0.93064
[13]	train-mlogloss:0.92226	eval-mlogloss:0.91804
[14]	train-mlogloss:0.91459	eval-mlogloss:0.91022
[15]	train-mlogloss:0.90442	eval-mlogloss:0.89951
[16]	train-mlogloss:0.89435	eval-mlogloss:0.88928
[17]	train-mlogloss:0.88571	eval-mlogloss:0.88078
[18]	train-mlogloss:0.87488	eval-mlogloss:0.86967
[19]	train-mlogloss:0.86599	eval-mlogloss:0.86037
[20]	train-mlogloss:0.85551	eval-mlogloss:0.84961
[21]	train-mlogloss:0.84514	eval-mlogloss:0.83866
[22]	train-mlogloss:0.83596	eval-mlogloss:0.82927
[23]	train-mlogloss:0.82586	eval-mlogloss:0.81867
[24]	train-mlogloss:0.81598	eval-mlogloss:0.80804
[25]	train-mlogloss:0.80626	eval-mlogloss:0.79754
[26]	train-mlogloss:0.79832	eval-mlogloss:0.78924
[27]	train-mlogloss:0.78904	eval-mlogloss:0.77939
[28]	train-mlogloss:0.78129	eval-mlogloss:0.77105
[29]	train-mlogloss:0.77217	eval-mlogloss:0.76139
[30]	train-mlogloss:0.76320	eval-mlogloss:0.75172
[31]	train-mlogloss:0.75632	eval-mlogloss:0.74495
[32]	train-mlogloss:0.74772	eval-mlogloss:0.73570
[33]	train-mlogloss:0.74248	eval-mlogloss:0.73044
[34]	train-mlogloss:0.73391	eval-mlogloss:0.72164
[35]	train-mlogloss:0.72555	eval-mlogloss:0.71261
[36]	train-mlogloss:0.71916	eval-mlogloss:0.70633
[37]	train-mlogloss:0.71097	eval-mlogloss:0.69790
[38]	train-mlogloss:0.70376	eval-mlogloss:0.69045
[39]	train-mlogloss:0.69666	eval-mlogloss:0.68331
[40]	train-mlogloss:0.69066	eval-mlogloss:0.67707
[41]	train-mlogloss:0.68309	eval-mlogloss:0.66872
[42]	train-mlogloss:0.67813	eval-mlogloss:0.66376
[43]	train-mlogloss:0.67192	eval-mlogloss:0.65722
[44]	train-mlogloss:0.66450	eval-mlogloss:0.64924
[45]	train-mlogloss:0.65848	eval-mlogloss:0.64283
[46]	train-mlogloss:0.65132	eval-mlogloss:0.63504
[47]	train-mlogloss:0.64421	eval-mlogloss:0.62752
[48]	train-mlogloss:0.63723	eval-mlogloss:0.62024
[49]	train-mlogloss:0.63036	eval-mlogloss:0.61307
[50]	train-mlogloss:0.62358	eval-mlogloss:0.60587
[51]	train-mlogloss:0.61757	eval-mlogloss:0.59969
[52]	train-mlogloss:0.61181	eval-mlogloss:0.59359
[53]	train-mlogloss:0.60534	eval-mlogloss:0.58654
[54]	train-mlogloss:0.60002	eval-mlogloss:0.58100
[55]	train-mlogloss:0.59368	eval-mlogloss:0.57438
[56]	train-mlogloss:0.58810	eval-mlogloss:0.56880
[57]	train-mlogloss:0.58192	eval-mlogloss:0.56224
[58]	train-mlogloss:0.57653	eval-mlogloss:0.55669
[59]	train-mlogloss:0.57160	eval-mlogloss:0.55149
[60]	train-mlogloss:0.56571	eval-mlogloss:0.54505
[61]	train-mlogloss:0.56191	eval-mlogloss:0.54152
[62]	train-mlogloss:0.55612	eval-mlogloss:0.53547
[63]	train-mlogloss:0.55179	eval-mlogloss:0.53119
[64]	train-mlogloss:0.54814	eval-mlogloss:0.52780
[65]	train-mlogloss:0.54255	eval-mlogloss:0.52194
[66]	train-mlogloss:0.53771	eval-mlogloss:0.51703
[67]	train-mlogloss:0.53228	eval-mlogloss:0.51134
[68]	train-mlogloss:0.52861	eval-mlogloss:0.50737
[69]	train-mlogloss:0.52334	eval-mlogloss:0.50166
[70]	train-mlogloss:0.51968	eval-mlogloss:0.49783
[71]	train-mlogloss:0.51454	eval-mlogloss:0.49226
[72]	train-mlogloss:0.50943	eval-mlogloss:0.48678
[73]	train-mlogloss:0.50438	eval-mlogloss:0.48135
[74]	train-mlogloss:0.49940	eval-mlogloss:0.47600
[75]	train-mlogloss:0.49514	eval-mlogloss:0.47142
[76]	train-mlogloss:0.49028	eval-mlogloss:0.46632
[77]	train-mlogloss:0.48668	eval-mlogloss:0.46257
[78]	train-mlogloss:0.48260	eval-mlogloss:0.45799
[79]	train-mlogloss:0.47798	eval-mlogloss:0.45281
[80]	train-mlogloss:0.47337	eval-mlogloss:0.44784
[81]	train-mlogloss:0.46882	eval-mlogloss:0.44306
[82]	train-mlogloss:0.46490	eval-mlogloss:0.43884
[83]	train-mlogloss:0.46191	eval-mlogloss:0.43553
[84]	train-mlogloss:0.45751	eval-mlogloss:0.43093
[85]	train-mlogloss:0.45424	eval-mlogloss:0.42754
[86]	train-mlogloss:0.44994	eval-mlogloss:0.42276
[87]	train-mlogloss:0.44627	eval-mlogloss:0.41879
[88]	train-mlogloss:0.44211	eval-mlogloss:0.41426
[89]	train-mlogloss:0.43796	eval-mlogloss:0.40991
[90]	train-mlogloss:0.43394	eval-mlogloss:0.40537
[91]	train-mlogloss:0.42990	eval-mlogloss:0.40113
[92]	train-mlogloss:0.42591	eval-mlogloss:0.39694
[93]	train-mlogloss:0.42365	eval-mlogloss:0.39475
[94]	train-mlogloss:0.41981	eval-mlogloss:0.39039
[95]	train-mlogloss:0.41597	eval-mlogloss:0.38626
[96]	train-mlogloss:0.41222	eval-mlogloss:0.38225
[97]	train-mlogloss:0.40850	eval-mlogloss:0.37820
[98]	train-mlogloss:0.40482	eval-mlogloss:0.37420
[99]	train-mlogloss:0.40167	eval-mlogloss:0.37094
[100]	train-mlogloss:0.39810	eval-mlogloss:0.36701
[101]	train-mlogloss:0.39455	eval-mlogloss:0.36316
[102]	train-mlogloss:0.39104	eval-mlogloss:0.35930
[103]	train-mlogloss:0.38757	eval-mlogloss:0.35565
[104]	train-mlogloss:0.38418	eval-mlogloss:0.35195
[105]	train-mlogloss:0.38080	eval-mlogloss:0.34829
[106]	train-mlogloss:0.37801	eval-mlogloss:0.34517
[107]	train-mlogloss:0.37507	eval-mlogloss:0.34167
[108]	train-mlogloss:0.37267	eval-mlogloss:0.33894
[109]	train-mlogloss:0.36977	eval-mlogloss:0.33559
[110]	train-mlogloss:0.36661	eval-mlogloss:0.33234
[111]	train-mlogloss:0.36378	eval-mlogloss:0.32922
[112]	train-mlogloss:0.36076	eval-mlogloss:0.32602
[113]	train-mlogloss:0.35803	eval-mlogloss:0.32275
[114]	train-mlogloss:0.35581	eval-mlogloss:0.32045
[115]	train-mlogloss:0.35311	eval-mlogloss:0.31736
[116]	train-mlogloss:0.35030	eval-mlogloss:0.31422
[117]	train-mlogloss:0.34757	eval-mlogloss:0.31102
[118]	train-mlogloss:0.34482	eval-mlogloss:0.30792
[119]	train-mlogloss:0.34267	eval-mlogloss:0.30556
[120]	train-mlogloss:0.34001	eval-mlogloss:0.30269
[121]	train-mlogloss:0.33736	eval-mlogloss:0.29972
[122]	train-mlogloss:0.33491	eval-mlogloss:0.29674
[123]	train-mlogloss:0.33246	eval-mlogloss:0.29393
[124]	train-mlogloss:0.33004	eval-mlogloss:0.29115
[125]	train-mlogloss:0.32758	eval-mlogloss:0.28844
[126]	train-mlogloss:0.32605	eval-mlogloss:0.28679
[127]	train-mlogloss:0.32418	eval-mlogloss:0.28484
[128]	train-mlogloss:0.32189	eval-mlogloss:0.28204
[129]	train-mlogloss:0.32000	eval-mlogloss:0.27992
[130]	train-mlogloss:0.31822	eval-mlogloss:0.27781
[131]	train-mlogloss:0.31591	eval-mlogloss:0.27519
[132]	train-mlogloss:0.31372	eval-mlogloss:0.27266
[133]	train-mlogloss:0.31181	eval-mlogloss:0.27051
[134]	train-mlogloss:0.31010	eval-mlogloss:0.26855
[135]	train-mlogloss:0.30837	eval-mlogloss:0.26636
[136]	train-mlogloss:0.30618	eval-mlogloss:0.26403
[137]	train-mlogloss:0.30400	eval-mlogloss:0.26172
[138]	train-mlogloss:0.30204	eval-mlogloss:0.25937
[139]	train-mlogloss:0.30040	eval-mlogloss:0.25760
[140]	train-mlogloss:0.29838	eval-mlogloss:0.25527
[141]	train-mlogloss:0.29672	eval-mlogloss:0.25352
[142]	train-mlogloss:0.29518	eval-mlogloss:0.25173
[143]	train-mlogloss:0.29317	eval-mlogloss:0.24958
[144]	train-mlogloss:0.29121	eval-mlogloss:0.24747
[145]	train-mlogloss:0.28938	eval-mlogloss:0.24541
[146]	train-mlogloss:0.28757	eval-mlogloss:0.24321
[147]	train-mlogloss:0.28571	eval-mlogloss:0.24099
[148]	train-mlogloss:0.28392	eval-mlogloss:0.23897
[149]	train-mlogloss:0.28251	eval-mlogloss:0.23731
[150]	train-mlogloss:0.28069	eval-mlogloss:0.23524
[151]	train-mlogloss:0.27894	eval-mlogloss:0.23322
[152]	train-mlogloss:0.27724	eval-mlogloss:0.23131
[153]	train-mlogloss:0.27550	eval-mlogloss:0.22934
[154]	train-mlogloss:0.27379	eval-mlogloss:0.22736
[155]	train-mlogloss:0.27213	eval-mlogloss:0.22542
[156]	train-mlogloss:0.27055	eval-mlogloss:0.22355
[157]	train-mlogloss:0.26894	eval-mlogloss:0.22162
[158]	train-mlogloss:0.26732	eval-mlogloss:0.21985
[159]	train-mlogloss:0.26606	eval-mlogloss:0.21830
[160]	train-mlogloss:0.26499	eval-mlogloss:0.21711
[161]	train-mlogloss:0.26339	eval-mlogloss:0.21537
[162]	train-mlogloss:0.26189	eval-mlogloss:0.21369
[163]	train-mlogloss:0.26066	eval-mlogloss:0.21224
[164]	train-mlogloss:0.25984	eval-mlogloss:0.21126
[165]	train-mlogloss:0.25866	eval-mlogloss:0.20992
[166]	train-mlogloss:0.25719	eval-mlogloss:0.20815
[167]	train-mlogloss:0.25569	eval-mlogloss:0.20640
[168]	train-mlogloss:0.25450	eval-mlogloss:0.20502
[169]	train-mlogloss:0.25310	eval-mlogloss:0.20345
[170]	train-mlogloss:0.25205	eval-mlogloss:0.20223
[171]	train-mlogloss:0.25061	eval-mlogloss:0.20045
[172]	train-mlogloss:0.24946	eval-mlogloss:0.19923
[173]	train-mlogloss:0.24826	eval-mlogloss:0.19785
[174]	train-mlogloss:0.24725	eval-mlogloss:0.19662
[175]	train-mlogloss:0.24604	eval-mlogloss:0.19530
[176]	train-mlogloss:0.24480	eval-mlogloss:0.19394
[177]	train-mlogloss:0.24428	eval-mlogloss:0.19332
[178]	train-mlogloss:0.24313	eval-mlogloss:0.19209
[179]	train-mlogloss:0.24235	eval-mlogloss:0.19124
[180]	train-mlogloss:0.24111	eval-mlogloss:0.18989
[181]	train-mlogloss:0.23994	eval-mlogloss:0.18861
[182]	train-mlogloss:0.23888	eval-mlogloss:0.18737
[183]	train-mlogloss:0.23809	eval-mlogloss:0.18652
[184]	train-mlogloss:0.23697	eval-mlogloss:0.18529
[185]	train-mlogloss:0.23586	eval-mlogloss:0.18397
[186]	train-mlogloss:0.23484	eval-mlogloss:0.18292
[187]	train-mlogloss:0.23402	eval-mlogloss:0.18199
[188]	train-mlogloss:0.23319	eval-mlogloss:0.18096
[189]	train-mlogloss:0.23207	eval-mlogloss:0.17974
[190]	train-mlogloss:0.23109	eval-mlogloss:0.17862
[191]	train-mlogloss:0.23039	eval-mlogloss:0.17788
[192]	train-mlogloss:0.22943	eval-mlogloss:0.17678
[193]	train-mlogloss:0.22841	eval-mlogloss:0.17555
[194]	train-mlogloss:0.22747	eval-mlogloss:0.17448
[195]	train-mlogloss:0.22657	eval-mlogloss:0.17349
[196]	train-mlogloss:0.22585	eval-mlogloss:0.17267
[197]	train-mlogloss:0.22494	eval-mlogloss:0.17158
[198]	train-mlogloss:0.22409	eval-mlogloss:0.17057
[199]	train-mlogloss:0.22325	eval-mlogloss:0.16956
[200]	train-mlogloss:0.22253	eval-mlogloss:0.16871
[201]	train-mlogloss:0.22170	eval-mlogloss:0.16772
[202]	train-mlogloss:0.22125	eval-mlogloss:0.16724
[203]	train-mlogloss:0.22082	eval-mlogloss:0.16676
[204]	train-mlogloss:0.22045	eval-mlogloss:0.16625
[205]	train-mlogloss:0.22027	eval-mlogloss:0.16603
[206]	train-mlogloss:0.21985	eval-mlogloss:0.16557
[207]	train-mlogloss:0.21916	eval-mlogloss:0.16474
[208]	train-mlogloss:0.21875	eval-mlogloss:0.16428
[209]	train-mlogloss:0.21812	eval-mlogloss:0.16353
[210]	train-mlogloss:0.21796	eval-mlogloss:0.16333
[211]	train-mlogloss:0.21784	eval-mlogloss:0.16318
[212]	train-mlogloss:0.21750	eval-mlogloss:0.16272
[213]	train-mlogloss:0.21710	eval-mlogloss:0.16227
[214]	train-mlogloss:0.21677	eval-mlogloss:0.16190
[215]	train-mlogloss:0.21637	eval-mlogloss:0.16137
[216]	train-mlogloss:0.21601	eval-mlogloss:0.16089
[217]	train-mlogloss:0.21562	eval-mlogloss:0.16046
[218]	train-mlogloss:0.21551	eval-mlogloss:0.16031
[219]	train-mlogloss:0.21512	eval-mlogloss:0.15980
[220]	train-mlogloss:0.21501	eval-mlogloss:0.15965
[221]	train-mlogloss:0.21490	eval-mlogloss:0.15950
[222]	train-mlogloss:0.21452	eval-mlogloss:0.15899
[223]	train-mlogloss:0.21417	eval-mlogloss:0.15861
[224]	train-mlogloss:0.21380	eval-mlogloss:0.15819
[225]	train-mlogloss:0.21343	eval-mlogloss:0.15778
[226]	train-mlogloss:0.21309	eval-mlogloss:0.15740
[227]	train-mlogloss:0.21272	eval-mlogloss:0.15698
[228]	train-mlogloss:0.21239	eval-mlogloss:0.15661
[229]	train-mlogloss:0.21203	eval-mlogloss:0.15621
[230]	train-mlogloss:0.21165	eval-mlogloss:0.15570
[231]	train-mlogloss:0.21136	eval-mlogloss:0.15532
[232]	train-mlogloss:0.21126	eval-mlogloss:0.15518
[233]	train-mlogloss:0.21092	eval-mlogloss:0.15473
[234]	train-mlogloss:0.21059	eval-mlogloss:0.15428
[235]	train-mlogloss:0.21024	eval-mlogloss:0.15381
[236]	train-mlogloss:0.20995	eval-mlogloss:0.15349
[237]	train-mlogloss:0.20961	eval-mlogloss:0.15310
[238]	train-mlogloss:0.20928	eval-mlogloss:0.15266
[239]	train-mlogloss:0.20917	eval-mlogloss:0.15250
[240]	train-mlogloss:0.20892	eval-mlogloss:0.15216
[241]	train-mlogloss:0.20862	eval-mlogloss:0.15175
[242]	train-mlogloss:0.20831	eval-mlogloss:0.15134
[243]	train-mlogloss:0.20820	eval-mlogloss:0.15119
[244]	train-mlogloss:0.20796	eval-mlogloss:0.15086
[245]	train-mlogloss:0.20769	eval-mlogloss:0.15050
[246]	train-mlogloss:0.20762	eval-mlogloss:0.15040
[247]	train-mlogloss:0.20752	eval-mlogloss:0.15024
[248]	train-mlogloss:0.20723	eval-mlogloss:0.14987
[249]	train-mlogloss:0.20700	eval-mlogloss:0.14954
[250]	train-mlogloss:0.20669	eval-mlogloss:0.14912
[251]	train-mlogloss:0.20639	eval-mlogloss:0.14871
[252]	train-mlogloss:0.20611	eval-mlogloss:0.14835
[253]	train-mlogloss:0.20584	eval-mlogloss:0.14798
[254]	train-mlogloss:0.20574	eval-mlogloss:0.14783
[255]	train-mlogloss:0.20564	eval-mlogloss:0.14770
[256]	train-mlogloss:0.20535	eval-mlogloss:0.14730
[257]	train-mlogloss:0.20506	eval-mlogloss:0.14691
[258]	train-mlogloss:0.20477	eval-mlogloss:0.14652
[259]	train-mlogloss:0.20468	eval-mlogloss:0.14637
[260]	train-mlogloss:0.20437	eval-mlogloss:0.14595
[261]	train-mlogloss:0.20431	eval-mlogloss:0.14585
[262]	train-mlogloss:0.20406	eval-mlogloss:0.14550
[263]	train-mlogloss:0.20376	eval-mlogloss:0.14508
[264]	train-mlogloss:0.20351	eval-mlogloss:0.14475
[265]	train-mlogloss:0.20342	eval-mlogloss:0.14464
[266]	train-mlogloss:0.20315	eval-mlogloss:0.14426
[267]	train-mlogloss:0.20306	eval-mlogloss:0.14413
[268]	train-mlogloss:0.20281	eval-mlogloss:0.14380
[269]	train-mlogloss:0.20256	eval-mlogloss:0.14347
[270]	train-mlogloss:0.20228	eval-mlogloss:0.14310
[271]	train-mlogloss:0.20205	eval-mlogloss:0.14276
[272]	train-mlogloss:0.20181	eval-mlogloss:0.14244
[273]	train-mlogloss:0.20172	eval-mlogloss:0.14232
[274]	train-mlogloss:0.20150	eval-mlogloss:0.14196
[275]	train-mlogloss:0.20123	eval-mlogloss:0.14160
[276]	train-mlogloss:0.20097	eval-mlogloss:0.14123
[277]	train-mlogloss:0.20074	eval-mlogloss:0.14090
[278]	train-mlogloss:0.20068	eval-mlogloss:0.14081
[279]	train-mlogloss:0.20039	eval-mlogloss:0.14040
[280]	train-mlogloss:0.20012	eval-mlogloss:0.14002
[281]	train-mlogloss:0.19989	eval-mlogloss:0.13970
[282]	train-mlogloss:0.19964	eval-mlogloss:0.13935
[283]	train-mlogloss:0.19956	eval-mlogloss:0.13923
[284]	train-mlogloss:0.19936	eval-mlogloss:0.13896
[285]	train-mlogloss:0.19911	eval-mlogloss:0.13861
[286]	train-mlogloss:0.19889	eval-mlogloss:0.13830
[287]	train-mlogloss:0.19866	eval-mlogloss:0.13799
[288]	train-mlogloss:0.19841	eval-mlogloss:0.13768
[289]	train-mlogloss:0.19836	eval-mlogloss:0.13772
[290]	train-mlogloss:0.19812	eval-mlogloss:0.13739
[291]	train-mlogloss:0.19787	eval-mlogloss:0.13705
[292]	train-mlogloss:0.19760	eval-mlogloss:0.13668
[293]	train-mlogloss:0.19736	eval-mlogloss:0.13634
[294]	train-mlogloss:0.19716	eval-mlogloss:0.13604
[295]	train-mlogloss:0.19690	eval-mlogloss:0.13569
[296]	train-mlogloss:0.19669	eval-mlogloss:0.13541
[297]	train-mlogloss:0.19664	eval-mlogloss:0.13533
[298]	train-mlogloss:0.19642	eval-mlogloss:0.13505
[299]	train-mlogloss:0.19621	eval-mlogloss:0.13476

[I 2026-05-06 16:09:33,895] Trial 32 finished with value: 1.0 and parameters: {'lambda': 1.9237520309707069e-07, 'alpha': 0.16448958805764397, 'eta': 0.011506230465798656, 'gamma': 0.1798919927668393, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.9889032140849771, 'colsample_bytree': 0.5180122659863753}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.06442	eval-mlogloss:1.06478
[1]	train-mlogloss:1.01503	eval-mlogloss:1.01322
[2]	train-mlogloss:0.96919	eval-mlogloss:0.96568
[3]	train-mlogloss:0.92605	eval-mlogloss:0.92158
[4]	train-mlogloss:0.88521	eval-mlogloss:0.87899
[5]	train-mlogloss:0.84707	eval-mlogloss:0.83896
[6]	train-mlogloss:0.81174	eval-mlogloss:0.80282
[7]	train-mlogloss:0.77842	eval-mlogloss:0.76780

[I 2026-05-06 16:09:34,176] Trial 33 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.99191	eval-mlogloss:1.00027
[1]	train-mlogloss:0.76615	eval-mlogloss:0.76141

[I 2026-05-06 16:09:34,327] Trial 34 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06816	eval-mlogloss:1.07168
[1]	train-mlogloss:0.99907	eval-mlogloss:0.99950
[2]	train-mlogloss:0.93610	eval-mlogloss:0.93428
[3]	train-mlogloss:0.89240	eval-mlogloss:0.88609
[4]	train-mlogloss:0.84773	eval-mlogloss:0.83887
[5]	train-mlogloss:0.79743	eval-mlogloss:0.78515
[6]	train-mlogloss:0.76178	eval-mlogloss:0.75060
[7]	train-mlogloss:0.73574	eval-mlogloss:0.72487

[I 2026-05-06 16:09:34,596] Trial 35 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.99105	eval-mlogloss:0.99248
[1]	train-mlogloss:0.87026	eval-mlogloss:0.86836

[I 2026-05-06 16:09:34,777] Trial 36 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.01873	eval-mlogloss:1.03117
[1]	train-mlogloss:0.92293	eval-mlogloss:0.91637

[I 2026-05-06 16:09:34,890] Trial 37 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.82079	eval-mlogloss:0.85498
[1]	train-mlogloss:0.59805	eval-mlogloss:0.63630

[I 2026-05-06 16:09:35,056] Trial 38 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90076	eval-mlogloss:0.88778
[1]	train-mlogloss:0.74990	eval-mlogloss:0.73376

[I 2026-05-06 16:09:35,171] Trial 39 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07048	eval-mlogloss:1.07069
[1]	train-mlogloss:1.05092	eval-mlogloss:1.04818
[2]	train-mlogloss:1.03304	eval-mlogloss:1.02976
[3]	train-mlogloss:1.00862	eval-mlogloss:1.00439
[4]	train-mlogloss:0.98921	eval-mlogloss:0.98469
[5]	train-mlogloss:0.96615	eval-mlogloss:0.96008
[6]	train-mlogloss:0.94842	eval-mlogloss:0.94076
[7]	train-mlogloss:0.93226	eval-mlogloss:0.92394
[8]	train-mlogloss:0.91517	eval-mlogloss:0.90590
[9]	train-mlogloss:0.89767	eval-mlogloss:0.88847
[10]	train-mlogloss:0.87885	eval-mlogloss:0.86850
[11]	train-mlogloss:0.85909	eval-mlogloss:0.84900
[12]	train-mlogloss:0.84348	eval-mlogloss:0.83226
[13]	train-mlogloss:0.82601	eval-mlogloss:0.81330
[14]	train-mlogloss:0.81357	eval-mlogloss:0.80041
[15]	train-mlogloss:0.79857	eval-mlogloss:0.78472
[16]	train-mlogloss:0.78473	eval-mlogloss:0.77022
[17]	train-mlogloss:0.77091	eval-mlogloss:0.75498
[18]	train-mlogloss:0.75783	eval-mlogloss:0.74114
[19]	train-mlogloss:0.74365	eval-mlogloss:0.72555
[20]	train-mlogloss:0.73187	eval-mlogloss:0.71177
[21]	train-mlogloss:0.72062	eval-mlogloss:0.69871
[22]	train-mlogloss:0.70628	eval-mlogloss:0.68299
[23]	train-mlogloss:0.69444	eval-mlogloss:0.67069
[24]	train-mlogloss:0.68069	eval-mlogloss:0.65507
[25]	train-mlogloss:0.67075	eval-mlogloss:0.64412
[26]	train-mlogloss:0.65749	eval-mlogloss:0.62925
[27]	train-mlogloss:0.64923	eval-mlogloss:0.62086
[28]	train-mlogloss:0.63910	eval-mlogloss:0.61018
[29]	train-mlogloss:0.62962	eval-mlogloss:0.59932
[30]	train-mlogloss:0.61981	eval-mlogloss:0.58908
[31]	train-mlogloss:0.60741	eval-mlogloss:0.57607

[I 2026-05-06 16:09:35,990] Trial 40 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.08344	eval-mlogloss:1.08435
[1]	train-mlogloss:1.04460	eval-mlogloss:1.04363
[2]	train-mlogloss:1.01135	eval-mlogloss:1.00889
[3]	train-mlogloss:0.98498	eval-mlogloss:0.97820
[4]	train-mlogloss:0.95705	eval-mlogloss:0.94774
[5]	train-mlogloss:0.92344	eval-mlogloss:0.91173
[6]	train-mlogloss:0.90083	eval-mlogloss:0.88716
[7]	train-mlogloss:0.88343	eval-mlogloss:0.87067

[I 2026-05-06 16:09:36,234] Trial 41 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07267	eval-mlogloss:1.07272
[1]	train-mlogloss:1.00684	eval-mlogloss:1.00367
[2]	train-mlogloss:0.94695	eval-mlogloss:0.94064
[3]	train-mlogloss:0.90541	eval-mlogloss:0.89258
[4]	train-mlogloss:0.86237	eval-mlogloss:0.84622
[5]	train-mlogloss:0.81270	eval-mlogloss:0.79412
[6]	train-mlogloss:0.77845	eval-mlogloss:0.75911
[7]	train-mlogloss:0.75403	eval-mlogloss:0.73585

[I 2026-05-06 16:09:36,488] Trial 42 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.04922	eval-mlogloss:1.04447
[1]	train-mlogloss:0.97016	eval-mlogloss:0.96165

[I 2026-05-06 16:09:36,584] Trial 43 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.07037	eval-mlogloss:1.07240
[1]	train-mlogloss:1.03314	eval-mlogloss:1.03093
[2]	train-mlogloss:0.99236	eval-mlogloss:0.98833
[3]	train-mlogloss:0.94829	eval-mlogloss:0.94298
[4]	train-mlogloss:0.90969	eval-mlogloss:0.90374
[5]	train-mlogloss:0.87294	eval-mlogloss:0.86366
[6]	train-mlogloss:0.84395	eval-mlogloss:0.83348
[7]	train-mlogloss:0.81739	eval-mlogloss:0.80614

[I 2026-05-06 16:09:36,836] Trial 44 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06250	eval-mlogloss:1.06230
[1]	train-mlogloss:0.97006	eval-mlogloss:0.96514

[I 2026-05-06 16:09:36,938] Trial 45 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03654	eval-mlogloss:1.03394
[1]	train-mlogloss:0.88685	eval-mlogloss:0.87668

[I 2026-05-06 16:09:37,044] Trial 46 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.00738	eval-mlogloss:1.00798
[1]	train-mlogloss:0.89087	eval-mlogloss:0.88600

[I 2026-05-06 16:09:37,170] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.86446	eval-mlogloss:0.84358
[1]	train-mlogloss:0.69931	eval-mlogloss:0.66609

[I 2026-05-06 16:09:37,277] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.08345	eval-mlogloss:1.08447
[1]	train-mlogloss:1.04607	eval-mlogloss:1.04542
[2]	train-mlogloss:1.01057	eval-mlogloss:1.00869
[3]	train-mlogloss:0.98449	eval-mlogloss:0.97932
[4]	train-mlogloss:0.95750	eval-mlogloss:0.95013
[5]	train-mlogloss:0.92594	eval-mlogloss:0.91680
[6]	train-mlogloss:0.90271	eval-mlogloss:0.89383
[7]	train-mlogloss:0.88564	eval-mlogloss:0.87749
[8]	train-mlogloss:0.85757	eval-mlogloss:0.84725
[9]	train-mlogloss:0.83711	eval-mlogloss:0.82611
[10]	train-mlogloss:0.81138	eval-mlogloss:0.79931
[11]	train-mlogloss:0.78909	eval-mlogloss:0.77666
[12]	train-mlogloss:0.78061	eval-mlogloss:0.76577
[13]	train-mlogloss:0.75753	eval-mlogloss:0.74055
[14]	train-mlogloss:0.74989	eval-mlogloss:0.73412
[15]	train-mlogloss:0.73706	eval-mlogloss:0.72183
[16]	train-mlogloss:0.72315	eval-mlogloss:0.70707
[17]	train-mlogloss:0.70691	eval-mlogloss:0.69055
[18]	train-mlogloss:0.69545	eval-mlogloss:0.67927
[19]	train-mlogloss:0.68460	eval-mlogloss:0.66853
[20]	train-mlogloss:0.66553	eval-mlogloss:0.64815
[21]	train-mlogloss:0.65232	eval-mlogloss:0.63433
[22]	train-mlogloss:0.64134	eval-mlogloss:0.62266
[23]	train-mlogloss:0.62351	eval-mlogloss:0.60379
[24]	train-mlogloss:0.61358	eval-mlogloss:0.59313
[25]	train-mlogloss:0.60136	eval-mlogloss:0.57946
[26]	train-mlogloss:0.58852	eval-mlogloss:0.56564
[27]	train-mlogloss:0.58508	eval-mlogloss:0.56304
[28]	train-mlogloss:0.58033	eval-mlogloss:0.55906
[29]	train-mlogloss:0.56795	eval-mlogloss:0.54512
[30]	train-mlogloss:0.55703	eval-mlogloss:0.53387
[31]	train-mlogloss:0.55382	eval-mlogloss:0.53151

[I 2026-05-06 16:09:38,224] Trial 49 pruned. Trial was pruned at iteration 32.

Best trial: {'lambda': 3.3040973683415064e-06, 'alpha': 3.9530011973898634e-05, 'eta': 0.2098190616012191, 'gamma': 0.003439146899030436, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8516066499538626, 'colsample_bytree': 0.49771044637713563}
Best accuracy: 1.0

In [35]:
 # pip install optuna-integration[xgboost]

In [37]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).write_html('data2/intermediate values during the trials.html')