# CSV file:
--> Comma Separated Values

--> Universaly Use 

--> Easy to Understand

--> Quick to Create

# Site for DataSet "https://www.kaggle.com"
# https://www.kaggle.com/datasets/kianindeed/imdb-movie-dataset-dec-2023

In [1]:
path = r"C:\Users\Lenovo\Data Science\Classroom\Module_1\Python_Libraries\Pandas\DataFrame\Data\imdb_movie_data_2023.csv"
# path = "C:\\Users\\Lenovo\\Data Science\\Classroom\\Module_1\\Python_Libraries\\Pandas\\DataFrame\\Data\\imdb_movie_data_2023.csv"

### Importing Important Library

In [2]:
import pandas as pd
import numpy as np

### Read csv file

In [3]:
df = pd.read_csv(path)
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_Id     1950 non-null   int64
 1   Moive Name  1950 non-null   object
 2   Rating      1944 non-null   float64
 3   Votes       1944 non-null   float64
 4   Meta Score  1833 non-null   float64
 5   Genre       1833 non-null   object
 6   PG Rating   1874 non-null   object
 7   Year        1950 non-null   int64
 8   Duration    1948 non-null   object
 9   Cast        1833 non-null   object
 10  Director    1833 non-null   object
dtypes: float64(3), int64(2), object(6)
memory usage: 167.7+ KB

# change datatype

In [5]:
df['User_Id'] = df['User_Id'].astype(np.int32)

In [6]:
df.dtypes

User_Id         int32
Moive Name     object
Rating        float64
Votes         float64
Meta Score    float64
Genre          object
PG Rating      object
Year            int64
Duration       object
Cast           object
Director       object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_Id     1950 non-null   int32
 1   Moive Name  1950 non-null   object
 2   Rating      1944 non-null   float64
 3   Votes       1944 non-null   float64
 4   Meta Score  1833 non-null   float64
 5   Genre       1833 non-null   object
 6   PG Rating   1874 non-null   object
 7   Year        1950 non-null   int64
 8   Duration    1948 non-null   object
 9   Cast        1833 non-null   object
 10  Director    1833 non-null   object
dtypes: float64(3), int32(1), int64(1), object(6)
memory usage: 160.1+ KB

In [14]:
df["Rating"] = df["Rating"].astype(float)

In [15]:
df.dtypes

User_Id         int32
Moive Name     object
Rating        float64
Votes         float64
Meta Score    float64
Genre          object
PG Rating      object
Year            int64
Duration       object
Cast           object
Director       object
dtype: object

In [8]:
df = pd.read_csv(path,dtype={"Votes":"float32","Year":"int32","Rating":"float32"})
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [9]:
df.dtypes

User_Id         int64
Moive Name     object
Rating        float32
Votes         float32
Meta Score    float64
Genre          object
PG Rating      object
Year            int32
Duration       object
Cast           object
Director       object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   User_Id     1950 non-null   int64
 1   Moive Name  1950 non-null   object
 2   Rating      1944 non-null   float32
 3   Votes       1944 non-null   float32
 4   Meta Score  1833 non-null   float64
 5   Genre       1833 non-null   object
 6   PG Rating   1874 non-null   object
 7   Year        1950 non-null   int32
 8   Duration    1948 non-null   object
 9   Cast        1833 non-null   object
 10  Director    1833 non-null   object
dtypes: float32(2), float64(1), int32(1), int64(1), object(6)
memory usage: 144.9+ KB

# nrow , skiprows and usecols while csv reading

In [20]:
# nrow
df = pd.read_csv(path,nrows=5)
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes

In [21]:
# skiprows
df = pd.read_csv(path,skiprows=5)
df

,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton, Julianne Moore",Todd Haynes
0,6,The Hunger Games: The Ballad of Songbirds & S...,7.1,56000.0,54.0,"Action, Adventure, Drama",PG-13,2023,2h 37m,"Rachel Zegler, Tom Blyth, Viola Davis, Dexter ...",Francis Lawrence
1,7,Napoleon,6.6,66000.0,64.0,"Action, Adventure, Biography",R,2023,2h 38m,"Joaquin Phoenix, Vanessa Kirby, Tahar Rahim, R...",Ridley Scott
2,8,Oppenheimer,8.4,553000.0,89.0,"Biography, Drama, History",R,2023,3h,"Cillian Murphy, Emily Blunt, Matt Damon, Rober...",Christopher Nolan
3,9,Love Actually,7.6,517000.0,55.0,"Comedy, Drama, Romance",R,2003,2h 15m,"Hugh Grant, Martine McCutcheon, Liam Neeson, L...",Richard Curtis
4,10,Candy Cane Lane,5.6,13000.0,47.0,"Comedy, Family, Fantasy",PG,2023,1h 57m,"Eddie Murphy, Tracee Ellis Ross, Jillian Bell,...",Reginald Hudlin
...,...,...,...,...,...,...,...,...,...,...,...
1940,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1941,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1942,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1943,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1944,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [22]:
df = pd.read_csv(path,skiprows=[1,3,7,10,11])
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
1,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
2,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
3,6,The Hunger Games: The Ballad of Songbirds & S...,7.1,56000.0,54.0,"Action, Adventure, Drama",PG-13,2023,2h 37m,"Rachel Zegler, Tom Blyth, Viola Davis, Dexter ...",Francis Lawrence
4,8,Oppenheimer,8.4,553000.0,89.0,"Biography, Drama, History",R,2023,3h,"Cillian Murphy, Emily Blunt, Matt Damon, Rober...",Christopher Nolan
...,...,...,...,...,...,...,...,...,...,...,...
1940,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1941,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1942,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1943,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1944,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [23]:
df.dtypes

User_Id         int64
Moive Name     object
Rating        float64
Votes         float64
Meta Score    float64
Genre          object
PG Rating      object
Year            int64
Duration       object
Cast           object
Director       object
dtype: object

In [24]:
# usecols
df = pd.read_csv(path,usecols=["Moive Name"])
df

                       Moive Name
0          Leave the World Behind
1                           Wonka
2                     Poor Things
3      Killers of the Flower Moon
4                    May December
...                           ...
1945            Definitely, Maybe
1946                      The Fly
1947             The Mighty Ducks
1948                Little Giants
1949                American Made

[1950 rows x 1 columns]

In [26]:
pd.read_csv("Data/imdb_movie_data_2023.csv").head(1)

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail

In [27]:
df = pd.read_csv(path,usecols=["User_Id","Moive Name","Rating","Genre"])
df

      User_Id                   Moive Name  Rating                      Genre
0           1       Leave the World Behind     6.5   Drama, Mystery, Thriller
1           2                        Wonka     7.4  Adventure, Comedy, Family
2           3                  Poor Things     8.5     Comedy, Drama, Romance
3           4   Killers of the Flower Moon     7.8      Crime, Drama, History
4           5                 May December     7.0              Comedy, Drama
...       ...                          ...     ...                        ...
1945     1946            Definitely, Maybe     7.1     Comedy, Drama, Romance
1946     1947                      The Fly     7.6      Drama, Horror, Sci-Fi
1947     1948             The Mighty Ducks     6.5      Comedy, Drama, Family
1948     1949                Little Giants     6.4                        NaN
1949     1950                American Made     7.1      Action, Comedy, Crime

[1950 rows x 4 columns]

In [41]:
pd.read_csv("Data/imdb_movie_data_2023.csv").head(1)

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail

In [28]:
df = pd.read_csv(path,usecols=[2,3,5,4])
df

      Rating     Votes  Meta Score                      Genre
0        6.5   90000.0        67.0   Drama, Mystery, Thriller
1        7.4   24000.0        66.0  Adventure, Comedy, Family
2        8.5    6700.0        86.0     Comedy, Drama, Romance
3        7.8  128000.0        89.0      Crime, Drama, History
4        7.0   21000.0        85.0              Comedy, Drama
...      ...       ...         ...                        ...
1945     7.1  172000.0        59.0     Comedy, Drama, Romance
1946     7.6  198000.0        79.0      Drama, Horror, Sci-Fi
1947     6.5   71000.0        46.0      Comedy, Drama, Family
1948     6.4   30000.0         NaN                        NaN
1949     7.1  203000.0        65.0      Action, Comedy, Crime

[1950 rows x 4 columns]

# set column as index one or more

In [37]:
df_User_id = pd.read_csv(path,index_col=["User_Id"])
df_User_id

,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
User_Id,,,,,,,,,,
1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...
1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [42]:
df_User_id.loc[2]

Moive Name                                                Wonka
Rating                                                      7.4
Votes                                                   24000.0
Meta Score                                                 66.0
Genre                                 Adventure, Comedy, Family
PG Rating                                                    PG
Year                                                       2023
Duration                                                 1h 56m
Cast          Timothée Chalamet, Gustave Die, Murray McArthu...
Director                                              Paul King
Name: 2, dtype: object

In [44]:
df_MN_UID = pd.read_csv(path,index_col=["Moive Name","User_Id"])
df_MN_UID

,,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
Moive Name,User_Id,,,,,,,,,
Leave the World Behind,1,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
Wonka,2,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
Poor Things,3,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
Killers of the Flower Moon,4,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
May December,5,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...
"Definitely, Maybe",1946,7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
The Fly,1947,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
The Mighty Ducks,1948,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
Little Giants,1949,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
American Made,1950,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [47]:
df['Moive Name'].values

array([' Leave the World Behind', ' Wonka', ' Poor Things', ...,
       ' The Mighty Ducks', ' Little Giants', ' American Made'],
      dtype=object)

In [48]:
df_MN_UID.loc[' Poor Things']

,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
User_Id,,,,,,,,,
3,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos

In [49]:
df_col_index = pd.read_csv(path,index_col=[0,1,2,3])
df_col_index

,,,,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
User_Id,Moive Name,Rating,Votes,,,,,,,
1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...
1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [50]:
# reset column index with example of missing index

df = pd.read_csv(path,index_col=['Genre','Duration'])
df

,,User_Id,Moive Name,Rating,Votes,Meta Score,PG Rating,Year,Cast,Director
Genre,Duration,,,,,,,,,
"Drama, Mystery, Thriller",2h 18m,1,Leave the World Behind,6.5,90000.0,67.0,R,2023,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
"Adventure, Comedy, Family",1h 56m,2,Wonka,7.4,24000.0,66.0,PG,2023,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
"Comedy, Drama, Romance",2h 21m,3,Poor Things,8.5,6700.0,86.0,R,2023,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
"Crime, Drama, History",3h 26m,4,Killers of the Flower Moon,7.8,128000.0,89.0,R,2023,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
"Comedy, Drama",1h 57m,5,May December,7.0,21000.0,85.0,R,2023,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...
"Comedy, Drama, Romance",1h 52m,1946,"Definitely, Maybe",7.1,172000.0,59.0,PG-13,2008,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
"Drama, Horror, Sci-Fi",1h 36m,1947,The Fly,7.6,198000.0,79.0,R,1986,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
"Comedy, Drama, Family",1h 44m,1948,The Mighty Ducks,6.5,71000.0,46.0,PG,1992,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
NaN,1h 47m,1949,Little Giants,6.4,30000.0,NaN,PG,1994,NaN,NaN
"Action, Comedy, Crime",1h 55m,1950,American Made,7.1,203000.0,65.0,R,2017,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [51]:
df.reset_index(inplace=True)
df

,Genre,Duration,User_Id,Moive Name,Rating,Votes,Meta Score,PG Rating,Year,Cast,Director
0,"Drama, Mystery, Thriller",2h 18m,1,Leave the World Behind,6.5,90000.0,67.0,R,2023,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,"Adventure, Comedy, Family",1h 56m,2,Wonka,7.4,24000.0,66.0,PG,2023,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,"Comedy, Drama, Romance",2h 21m,3,Poor Things,8.5,6700.0,86.0,R,2023,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,"Crime, Drama, History",3h 26m,4,Killers of the Flower Moon,7.8,128000.0,89.0,R,2023,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,"Comedy, Drama",1h 57m,5,May December,7.0,21000.0,85.0,R,2023,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,"Comedy, Drama, Romance",1h 52m,1946,"Definitely, Maybe",7.1,172000.0,59.0,PG-13,2008,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,"Drama, Horror, Sci-Fi",1h 36m,1947,The Fly,7.6,198000.0,79.0,R,1986,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,"Comedy, Drama, Family",1h 44m,1948,The Mighty Ducks,6.5,71000.0,46.0,PG,1992,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,NaN,1h 47m,1949,Little Giants,6.4,30000.0,NaN,PG,1994,NaN,NaN
1949,"Action, Comedy, Crime",1h 55m,1950,American Made,7.1,203000.0,65.0,R,2017,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

# sort index

In [52]:
df = pd.read_csv(path,index_col=["Year"])
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Duration,Cast,Director
Year,,,,,,,,,,
2023,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
2023,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2023,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
2023,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
2023,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...
2008,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1986,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1992,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1994,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1h 47m,NaN,NaN
2017,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [53]:
df.sort_index()

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Duration,Cast,Director
Year,,,,,,,,,,
1938,1047,A Christmas Carol,7.5,8500.0,72.0,"Drama, Family, Fantasy",Passed,1h 9m,"Reginald Owen, Gene Lockhart, Kathleen Lockhar...",Edwin L. Marin
1939,802,Gone with the Wind,8.2,329000.0,97.0,"Drama, Romance, War",Passed,3h 58m,"Clark Gable, Vivien Leigh, Thomas Mitchell, Ba...",Victor FlemingGeorge CukorSam Wood
1939,882,Remember the Night,7.6,6800.0,78.0,"Comedy, Drama, Romance",Passed,1h 34m,"Barbara Stanwyck, Fred MacMurray, Beulah Bondi...",Mitchell Leisen
1939,163,The Wizard of Oz,8.1,421000.0,92.0,"Adventure, Family, Fantasy",G,1h 42m,"Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr",Victor FlemingKing Vidor
1940,852,The Shop Around the Corner,8.0,37000.0,96.0,"Comedy, Drama, Romance",NaN,1h 39m,"Margaret Sullavan, James Stewart, Frank Morgan...",Ernst Lubitsch
...,...,...,...,...,...,...,...,...,...,...
2023,292,Renaissance: A Film by Beyoncé,8.7,2500.0,86.0,"Documentary, Music",NaN,2h 49m,"Beyoncé, Blue Ivy Carter, Diana Ross, Kendrick...",BeyoncéEd Burke
2023,1583,Boston Strangler,6.5,31000.0,58.0,"Crime, Drama, History",R,1h 52m,"Keira Knightley, Carrie Coon, Chris Cooper, Al...",Matt Ruskin
2023,578,The Book of Clarence,NaN,NaN,62.0,"Adventure, Comedy, Drama",PG-13,2h 16m,"Teyana Taylor, Benedict Cumberbatch, James McA...",Jeymes Samuel
2023,867,Kill Shot,4.6,1500.0,NaN,NaN,NaN,1h 33m,NaN,NaN
2023,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail

In [54]:
df.sort_index(ascending=False,inplace=True)
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Duration,Cast,Director
Year,,,,,,,,,,
2023,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
2023,857,The Persian Version,6.4,1400.0,61.0,"Comedy, Drama, Romance",R,1h 47m,"Layla Mohammadi, Niousha Noor, Kamand Shafieis...",Maryam Keshavarz
2023,228,Dashing Through the Snow,5.5,2600.0,NaN,NaN,PG,1h 32m,NaN,NaN
2023,227,The Covenant,7.5,144000.0,63.0,"Action, Drama, Thriller",R,2h 3m,"Jake Gyllenhaal, Dar Salim, Sean Sagar, Jason ...",Guy Ritchie
2023,551,PAW Patrol: The Mighty Movie,6.0,4000.0,49.0,"Animation, Action, Adventure",PG,1h 28m,"Dan Duran, Kristen Bell, James Marsden, Finn L...",Cal Brunker
...,...,...,...,...,...,...,...,...,...,...
1940,852,The Shop Around the Corner,8.0,37000.0,96.0,"Comedy, Drama, Romance",NaN,1h 39m,"Margaret Sullavan, James Stewart, Frank Morgan...",Ernst Lubitsch
1939,163,The Wizard of Oz,8.1,421000.0,92.0,"Adventure, Family, Fantasy",G,1h 42m,"Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr",Victor FlemingKing Vidor
1939,882,Remember the Night,7.6,6800.0,78.0,"Comedy, Drama, Romance",Passed,1h 34m,"Barbara Stanwyck, Fred MacMurray, Beulah Bondi...",Mitchell Leisen
1939,802,Gone with the Wind,8.2,329000.0,97.0,"Drama, Romance, War",Passed,3h 58m,"Clark Gable, Vivien Leigh, Thomas Mitchell, Ba...",Victor FlemingGeorge CukorSam Wood
1938,1047,A Christmas Carol,7.5,8500.0,72.0,"Drama, Family, Fantasy",Passed,1h 9m,"Reginald Owen, Gene Lockhart, Kathleen Lockhar...",Edwin L. Marin

# header

In [58]:
df = pd.read_csv(r"Data/imdb_movie_data_header_ex.csv")
df

,1,2,3,4,5,6,7,8,9,10,11
0,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
1,1,Leave the World Behind,6.5,90000,67,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
2,2,Wonka,7.4,24000,66,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
3,3,Poor Things,8.5,6700,86,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
4,4,Killers of the Flower Moon,7.8,128000,89,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
...,...,...,...,...,...,...,...,...,...,...,...
1946,1946,"Definitely, Maybe",7.1,172000,59,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1947,1947,The Fly,7.6,198000,79,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1948,1948,The Mighty Ducks,6.5,71000,46,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1949,1949,Little Giants,6.4,30000,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1950,1950,American Made,7.1,203000,65,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [61]:
df = pd.read_csv(r"Data/imdb_movie_data_header_ex.csv",header=1)
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

# head and tail

In [62]:
df = pd.read_csv(path)
df

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [63]:
df.head(60) # max 60

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
5,6,The Hunger Games: The Ballad of Songbirds & S...,7.1,56000.0,54.0,"Action, Adventure, Drama",PG-13,2023,2h 37m,"Rachel Zegler, Tom Blyth, Viola Davis, Dexter ...",Francis Lawrence
6,7,Napoleon,6.6,66000.0,64.0,"Action, Adventure, Biography",R,2023,2h 38m,"Joaquin Phoenix, Vanessa Kirby, Tahar Rahim, R...",Ridley Scott
7,8,Oppenheimer,8.4,553000.0,89.0,"Biography, Drama, History",R,2023,3h,"Cillian Murphy, Emily Blunt, Matt Damon, Rober...",Christopher Nolan
8,9,Love Actually,7.6,517000.0,55.0,"Comedy, Drama, Romance",R,2003,2h 15m,"Hugh Grant, Martine McCutcheon, Liam Neeson, L...",Richard Curtis
9,10,Candy Cane Lane,5.6,13000.0,47.0,"Comedy, Family, Fantasy",PG,2023,1h 57m,"Eddie Murphy, Tracee Ellis Ross, Jillian Bell,...",Reginald Hudlin
10,11,Saltburn,7.5,13000.0,61.0,"Comedy, Drama, Thriller",R,2023,2h 11m,"Barry Keoghan, Jacob Elordi, Archie Madekwe, S...",Emerald Fennell
11,12,Barbie,7.0,417000.0,80.0,"Adventure, Comedy, Fantasy",PG-13,2023,1h 54m,"Margot Robbie, Ryan Gosling, Issa Rae, Kate Mc...",Greta Gerwig
12,13,National Lampoon's Christmas Vacation,7.5,213000.0,49.0,Comedy,PG-13,1989,1h 37m,"Chevy Chase, Beverly D'Angelo, Juliette Lewis,...",Jeremiah S. Chechik
13,14,Rebel Moon - Part One: A Child of Fire,6.3,1900.0,32.0,"Action, Adventure, Drama",PG-13,2023,2h 13m,"Sofia Boutella, Charlie Hunnam, Ed Skrein, Jen...",Zack Snyder
14,15,The Family Plan,6.3,9200.0,40.0,"Action, Comedy",PG-13,2023,1h 58m,"Mark Wahlberg, Michelle Monaghan, Ciarán Hinds...",Simon Cellan Jones
15,16,The Holdovers,8.0,24000.0,82.0,"Comedy, Drama",R,2023,2h 13m,"Paul Giamatti, Da'Vine Joy Randolph, Dominic S...",Alexander Payne
16,17,Family Switch,5.6,16000.0,37.0,"Comedy, Family",PG,2023,1h 46m,"Jennifer Garner, Ed Helms, Emma Myers, Brady Noon",McG
17,18,Indiana Jones and the Dial of Destiny,6.6,159000.0,58.0,"Action, Adventure, Sci-Fi",PG-13,2023,2h 34m,"Harrison Ford, Phoebe Waller-Bridge, Antonio B...",James Mangold
18,19,Elf,7.1,300000.0,66.0,"Adventure, Comedy, Family",PG,2003,1h 37m,"Will Ferrell, James Caan, Bob Newhart, Zooey D...",Jon Favreau
19,20,How the Grinch Stole Christmas,6.3,280000.0,46.0,"Comedy, Family, Fantasy",PG,2000,1h 44m,"Jim Carrey, Taylor Momsen, Kelley, Jeffrey Tambor",Ron Howard
20,21,Maestro,7.3,3600.0,78.0,"Biography, Drama, Music",R,2023,2h 9m,"Carey Mulligan, Bradley Cooper, Matt Bomer, Vi...",Bradley Cooper
21,22,Mr. Monk's Last Case: A Monk Movie,7.0,3500.0,65.0,"Comedy, Crime, Mystery",TV-PG,2023,1h 37m,"Tony Shalhoub, Traylor Howard, Jason Gray-Stan...",Randy Zisk
22,23,The Iron Claw,NaN,NaN,72.0,"Biography, Drama, Sport",R,2023,2h 10m,"Zac Efron, Jeremy Allen White, Harris Dickinso...",Sean Durkin
23,24,Leo,7.0,21000.0,65.0,"Animation, Comedy, Family",PG,2023,1h 42m,"Adam Sandler, Bill Burr, Cecily Strong, Jason ...",Robert MarianettiRobert SmigelDavid Wachtenheim
24,25,Fast Charlie,5.9,3700.0,70.0,"Action, Crime, Drama",NaN,2023,1h 30m,"Pierce Brosnan, Morena Baccarin, James Caan, G...",Phillip Noyce
25,26,The Creator,6.9,92000.0,63.0,"Action, Adventure, Drama",PG-13,2023,2h 13m,"John David Washington, Madeleine Yuna Voyles, ...",Gareth Edwards
26,27,The Grinch,6.4,85000.0,51.0,"Animation, Comedy, Family",PG,2018,1h 25m,"Benedict Cumberbatch, Cameron Seely, Rashida J...",Yarrow CheneyScott Mosier
27,28,Chicken Run: Dawn of the Nugget,6.5,6300.0,63.0,"Animation, Adventure, Comedy",PG,2023,1h 41m,"Thandiwe Newton, Zachary Levi, Bella Ramsey, I...",Sam Fell
28,29,Die Hard,8.2,924000.0,72.0,"Action, Thriller",R,1988,2h 12m,"Bruce Willis, Alan Rickman, Bonnie Bedelia, Re...",John McTiernan
29,30,The Killer,6.8,140000.0,73.0,"Action, Adventure, Crime",R,2023,1h 58m,"Michael Fassbender, Tilda Swinton, Charles Par...",David Fincher
30,31,The Super Mario Bros. Movie,7.0,213000.0,46.0,"Animation, Adventure, Comedy",PG,2023,1h 32m,"Chris Pratt, Anya Taylor-Joy, Charlie Day, Jac...",Aaron HorvathMichael JelenicPierre Leduc
31,32,Violent Night,6.7,88000.0,55.0,"Action, Comedy, Thriller",R,2022,1h 52m,"David Harbour, John Leguizamo, Beverly D'Angel...",Tommy Wirkola
32,33,Home Alone 2: Lost in New York,6.9,389000.0,46.0,"Adventure, Comedy, Crime",PG,1992,2h,"Macaulay Culkin, Joe Pesci, Daniel Stern, Cath...",Chris Columbus
33,34,A Haunting in Venice,6.5,84000.0,63.0,"Crime, Drama, Horror",PG-13,2023,1h 43m,"Kenneth Branagh, Michelle Yeoh, Jamie Dornan, ...",Kenneth Branagh
34,35,The Marvels,5.9,64000.0,50.0,"Action, Adventure, Fantasy",PG-13,2023,1h 45m,"Brie Larson, Teyonah Parris, Iman Vellani, Sam...",Nia DaCosta
35,36,Wish,5.8,11000.0,47.0,"Animation, Adventure, Comedy",PG,2023,1h 35m,"Ariana DeBose, Chris Pine, Alan Tudyk, Angeliq...",Chris BuckFawn Veerasunthorn
36,37,The Polar Express,6.6,233000.0,61.0,"Animation, Adventure, Comedy",G,2004,1h 40m,"Tom Hanks, Chris Coppola, Michael Jeter, Lesli...",Robert Zemeckis
37,38,It's a Wonderful Life,8.6,486000.0,89.0,"Drama, Family, Fantasy",PG,1946,2h 10m,"James Stewart, Donna Reed, Lionel Barrymore, T...",Frank Capra
38,39,Five Nights at Freddy's,5.5,78000.0,33.0,"Horror, Mystery, Thriller",PG-13,2023,1h 49m,"Josh Hutcherson, Piper Rubio, Elizabeth Lail, ...",Emma Tammi
39,40,The Shift,6.4,2400.0,NaN,NaN,PG-13,2023,1h 55m,NaN,NaN
40,41,The Santa Clause,6.6,130000.0,57.0,"Comedy, Drama, Family",PG,1994,1h 37m,"Tim Allen, Judge Reinhold, Wendy Crewson, Eric...",John Pasquin
41,42,Christmas on Cherry Lane,6.2,689.0,NaN,NaN,TV-G,2023,1h 30m,NaN,NaN
42,43,White Christmas,7.6,49000.0,56.0,"Comedy, Musical, Romance",NaN,1954,2h,"Bing Crosby, Danny Kaye, Rosemary Clooney, Ver...",Michael Curtiz
43,44,Finestkind,5.8,1900.0,44.0,"Crime, Drama, Thriller",R,2023,2h 6m,"Ben Foster, Toby Wallace, Jenna Ortega, Tommy ...",Brian Helgeland
44,45,Thanksgiving,6.8,15000.0,63.0,"Horror, Mystery, Thriller",R,2023,1h 46m,"Patrick Dempsey, Ty Olsson, Gina Gershon, Gabr...",Eli Roth
45,46,The Holiday,6.9,312000.0,52.0,"Comedy, Romance",PG-13,2006,2h 16m,"Kate Winslet, Cameron Diaz, Jude Law, Jack Black",Nancy Meyers
46,47,The Hunger Games,7.2,982000.0,68.0,"Action, Adventure, Sci-Fi",PG-13,2012,2h 22m,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",Gary Ross
47,48,The Boys in the Boat,NaN,NaN,50.0,"Biography, Drama, Sport",PG-13,2023,2h 4m,"Joel Edgerton, Callum Turner, Peter Guinness, ...",George Clooney
48,49,A Christmas Story,7.9,165000.0,77.0,"Comedy, Family",PG,1983,1h 33m,"Peter Billingsley, Melinda Dillon, Darren McGa...",Bob Clark
49,50,The Color Purple,NaN,NaN,70.0,"Drama, Musical",PG-13,2023,2h 20m,"Fantasia Barrino, Taraji P. Henson, Danielle B...",Blitz Bazawule
50,51,Willy Wonka & the Chocolate Factory,7.8,218000.0,67.0,"Family, Fantasy, Musical",G,1971,1h 40m,"Gene Wilder, Jack Albertson, Peter Ostrum, Roy...",Mel Stuart
51,52,Trolls Band Together,6.0,7200.0,53.0,"Animation, Adventure, Comedy",PG,2023,1h 31m,"Anna Kendrick, Justin Timberlake, Kenan Thomps...",Walt DohrnTim Heitz
52,53,Scrooged,6.9,113000.0,38.0,"Comedy, Drama, Fantasy",PG-13,1988,1h 41m,"Bill Murray, Karen Allen, John Forsythe, John ...",Richard Donner
53,54,Ferrari,6.7,1800.0,74.0,"Biography, Drama, History",R,2023,2h 10m,"Adam Driver, Shailene Woodley, Giuseppe Festin...",Michael Mann
54,55,No Hard Feelings,6.4,118000.0,59.0,"Comedy, Romance",R,2023,1h 43m,"Jennifer Lawrence, Andrew Barth Feldman, Laura...",Gene Stupnitsky
55,56,Charlie and the Chocolate Factory,6.7,514000.0,72.0,"Adventure, Comedy, Family",PG,2005,1h 55m,"Johnny Depp, Freddie Highmore, David Kelly, He...",Tim Burton
56,57,Lady Ballers,6.2,9200.0,NaN,NaN,TV-14,2023,1h 52m,NaN,NaN
57,58,X,6.5,157000.0,79.0,"Horror, Mystery, Thriller",R,2022,1h 45m,"Mia Goth, Jenna Ortega, Brittany Snow, Kid Cudi",Ti West
58,59,Mission: Impossible - Dead Reckoning Part One,7.8,202000.0,81.0,"Action, Adventure, Thriller",PG-13,2023,2h 43m,"Tom Cruise, Hayley Atwell, Ving Rhames, Simon ...",Christopher McQuarrie
59,60,Spider-Man: Across the Spider-Verse,8.6,314000.0,86.0,"Animation, Action, Adventure",PG,2023,2h 20m,"Shameik Moore, Hailee Steinfeld, Brian Tyree H...",Joaquim Dos SantosKemp PowersJustin K. Thompson

In [64]:
df.tail() # max 60

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

# access in column with loc and iloc

### **🔹 `df.loc[]` (Label-Based Indexing)**  
- Used for selecting data **by labels** (row/column names).  
- Supports **single labels, lists, slices, and boolean indexing**.  
- When slicing, **both start and end indexes are included**.  

### **🔹 `df.iloc[]` (Position-Based Indexing)**  
- Used for selecting data **by integer positions** (0-based index).  
- Supports **single positions, lists, and slices**.  
- When slicing, **end index is excluded** (like Python lists).  

### **🔹 Key Differences**  
| Feature  | `df.loc[]` | `df.iloc[]` |
|----------|-----------|-------------|
| Indexing Type | Label-based | Position-based |
| Row Selection | By label | By position |
| Column Selection | By column name | By position |
| Slicing | Includes end index | Excludes end index |
| Boolean Masking | Supported | Not supported |

In [65]:
#loc
df.head()

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes

In [68]:
df.loc[0]

User_Id                                                       1
Moive Name                               Leave the World Behind
Rating                                                      6.5
Votes                                                   90000.0
Meta Score                                                 67.0
Genre                                  Drama, Mystery, Thriller
PG Rating                                                     R
Year                                                       2023
Duration                                                 2h 18m
Cast          Julia Roberts, Mahershala Ali, Ethan Hawke, My...
Director                                             Sam Esmail
Name: 0, dtype: object

In [69]:
df.loc[[0]]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail

In [70]:
df.loc[[5,1,8]]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
5,6,The Hunger Games: The Ballad of Songbirds & S...,7.1,56000.0,54.0,"Action, Adventure, Drama",PG-13,2023,2h 37m,"Rachel Zegler, Tom Blyth, Viola Davis, Dexter ...",Francis Lawrence
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
8,9,Love Actually,7.6,517000.0,55.0,"Comedy, Drama, Romance",R,2003,2h 15m,"Hugh Grant, Martine McCutcheon, Liam Neeson, L...",Richard Curtis

In [71]:
df.loc[5,"Moive Name"]

' The Hunger Games: The Ballad of Songbirds & Snakes'

In [73]:
df.columns

Index(['User_Id', 'Moive Name', 'Rating', 'Votes', 'Meta Score', 'Genre',
       'PG Rating', 'Year', 'Duration', 'Cast', 'Director'],
      dtype='object')

In [82]:
df.loc[1:10,"Moive Name"]

1                                                 Wonka
2                                           Poor Things
3                            Killers of the Flower Moon
4                                          May December
5      The Hunger Games: The Ballad of Songbirds & S...
6                                              Napoleon
7                                           Oppenheimer
8                                         Love Actually
9                                       Candy Cane Lane
10                                             Saltburn
Name: Moive Name, dtype: object

In [80]:
df.loc[0:2,['User_Id', 'Moive Name', 'Rating', 'Votes','Genre', 'Year']]

,User_Id,Moive Name,Rating,Votes,Genre,Year
0,1,Leave the World Behind,6.5,90000.0,"Drama, Mystery, Thriller",2023
1,2,Wonka,7.4,24000.0,"Adventure, Comedy, Family",2023
2,3,Poor Things,8.5,6700.0,"Comedy, Drama, Romance",2023

In [84]:
x = df.loc[:,['User_Id', 'Moive Name', 'Rating', 'Votes','Genre', 'Year']]
x

,User_Id,Moive Name,Rating,Votes,Genre,Year
0,1,Leave the World Behind,6.5,90000.0,"Drama, Mystery, Thriller",2023
1,2,Wonka,7.4,24000.0,"Adventure, Comedy, Family",2023
2,3,Poor Things,8.5,6700.0,"Comedy, Drama, Romance",2023
3,4,Killers of the Flower Moon,7.8,128000.0,"Crime, Drama, History",2023
4,5,May December,7.0,21000.0,"Comedy, Drama",2023
...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,"Comedy, Drama, Romance",2008
1946,1947,The Fly,7.6,198000.0,"Drama, Horror, Sci-Fi",1986
1947,1948,The Mighty Ducks,6.5,71000.0,"Comedy, Drama, Family",1992
1948,1949,Little Giants,6.4,30000.0,NaN,1994
1949,1950,American Made,7.1,203000.0,"Action, Comedy, Crime",2017

In [ ]:
#iloc

In [85]:
df.iloc[0]

User_Id                                                       1
Moive Name                               Leave the World Behind
Rating                                                      6.5
Votes                                                   90000.0
Meta Score                                                 67.0
Genre                                  Drama, Mystery, Thriller
PG Rating                                                     R
Year                                                       2023
Duration                                                 2h 18m
Cast          Julia Roberts, Mahershala Ali, Ethan Hawke, My...
Director                                             Sam Esmail
Name: 0, dtype: object

In [86]:
df.iloc[[0]]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail

In [87]:
df.iloc[[0,1]]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King

In [89]:
df.iloc[:,1]   # only in iloc

0            Leave the World Behind
1                             Wonka
2                       Poor Things
3        Killers of the Flower Moon
4                      May December
                   ...
1945              Definitely, Maybe
1946                        The Fly
1947               The Mighty Ducks
1948                  Little Giants
1949                  American Made
Name: Moive Name, Length: 1950, dtype: object

In [92]:
df.iloc[:,[1]]

                       Moive Name
0          Leave the World Behind
1                           Wonka
2                     Poor Things
3      Killers of the Flower Moon
4                    May December
...                           ...
1945            Definitely, Maybe
1946                      The Fly
1947             The Mighty Ducks
1948                Little Giants
1949                American Made

[1950 rows x 1 columns]

In [94]:
df.iloc[0:11,0:6]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller"
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family"
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance"
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History"
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama"
5,6,The Hunger Games: The Ballad of Songbirds & S...,7.1,56000.0,54.0,"Action, Adventure, Drama"
6,7,Napoleon,6.6,66000.0,64.0,"Action, Adventure, Biography"
7,8,Oppenheimer,8.4,553000.0,89.0,"Biography, Drama, History"
8,9,Love Actually,7.6,517000.0,55.0,"Comedy, Drama, Romance"
9,10,Candy Cane Lane,5.6,13000.0,47.0,"Comedy, Family, Fantasy"
10,11,Saltburn,7.5,13000.0,61.0,"Comedy, Drama, Thriller"

In [97]:
df.iloc[8:15,[1,7,3]]

                                 Moive Name  Year     Votes
8                             Love Actually  2003  517000.0
9                           Candy Cane Lane  2023   13000.0
10                                 Saltburn  2023   13000.0
11                                   Barbie  2023  417000.0
12    National Lampoon's Christmas Vacation  1989  213000.0
13   Rebel Moon - Part One: A Child of Fire  2023    1900.0
14                          The Family Plan  2023    9200.0

In [98]:
df.iloc[8:35:3,::2]

,User_Id,Rating,Meta Score,PG Rating,Duration,Director
8,9,7.6,55.0,R,2h 15m,Richard Curtis
11,12,7.0,80.0,PG-13,1h 54m,Greta Gerwig
14,15,6.3,40.0,PG-13,1h 58m,Simon Cellan Jones
17,18,6.6,58.0,PG-13,2h 34m,James Mangold
20,21,7.3,78.0,R,2h 9m,Bradley Cooper
23,24,7.0,65.0,PG,1h 42m,Robert MarianettiRobert SmigelDavid Wachtenheim
26,27,6.4,51.0,PG,1h 25m,Yarrow CheneyScott Mosier
29,30,6.8,73.0,R,1h 58m,David Fincher
32,33,6.9,46.0,PG,2h,Chris Columbus

In [96]:
df['Moive Name'].values

array([' Leave the World Behind', ' Wonka', ' Poor Things', ...,
       ' The Mighty Ducks', ' Little Giants', ' American Made'],
      dtype=object)

In [95]:
df.iloc[0,2]=" Killers of the Flower Moon"
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_3240\1374660333.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value ' Killers of the Flower Moon' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.iloc[0,2]=" Killers of the Flower Moon"

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,Killers of the Flower Moon,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

# set_option for rows and column

In [ ]:
# pd.set_option("display.max_rows",None) 
# pd.set_option("display.min_rows",5)
# pd.set_option("display.max_column",6)
# pd.set_option("display.max_colwidth",None)
# pd.reset_option("display.max_colwidth")
# pd.reset_option("display.width")

In [1]:
import pandas as pd
pd.set_option("display.max_rows",50)

In [2]:
# pd.set_option("display.max_column",6)

In [5]:
pd.set_option("display.max_colwidth", None)  # Show full column content

In [4]:
pd.reset_option("display.max_rows")

In [6]:
df_set = pd.read_csv('Data/imdb_movie_data_2023.csv')
df_set

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, Myha'la",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthur, Paul G. Raymond",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Youssef",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladstone, Jesse Plemons",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton, Julianne Moore",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, An Nguyen",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Boushel",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heidi Kling",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Jesse Plemons",Doug Liman