In [1]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv('Data/Movies_clean.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

# na_values concept / na_values for fixed key

In [29]:
pd.read_csv('Data/Movies_clean.csv')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [31]:
df = pd.read_csv('Data/Movies_clean.csv',na_values = ['not available','not value','not mension'])
df

    USER_ID  MOVIE_ID    MOVIE_TITLE  PRODUCTION_YEAR    GENRES  RATING
0     101.0     201.0      Inception           2010.0    Sci-Fi     8.8
1     102.0     202.0        Titanic           1997.0   Romance     7.8
2     103.0     203.0         Avatar           2009.0    Action     NaN
3     104.0     204.0  The Godfather           1972.0     Crime     9.2
4     105.0     205.0            NaN           1994.0       NaN     8.5
5       NaN     206.0          Joker              NaN  Thriller     8.7
6     107.0       NaN      Gladiator              NaN     Drama     NaN
7       NaN     208.0            NaN           2019.0       NaN     9.0
8     109.0     209.0   Interstellar           2014.0    Sci-Fi     NaN
9     110.0       NaN            NaN           2009.0       NaN     8.2
10      NaN     211.0         Frozen              NaN    Comedy     NaN
11    112.0     213.0         Matrix              NaN    Action     7.9
12      NaN       NaN            NaN           2003.0       NaN     NaN

In [32]:
df = pd.read_csv('Data/Movieratingdata1.csv',na_values = {"PRODUCTION_YEAR":"not available","GENRES":"not mension"})
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,4642044,Riot,2015,Action,NaN
1,2,NaN,NaN,NaN,NaN,NaN
2,3,not value,NaN,2014,NaN,NaN
3,4,1390411,NaN,2015,NaN,5
4,5,6306064,NaN,NaN,Action|Adventure|Biography|Drama|Romance|Thriller,4
5,6,6306064,NaN,not mension,Action|Adventure|Biography|Drama|Romance|Thriller,5
6,7,2719848,NaN,2015,Action|Adventure|Biography|Drama|Thriller,not available
7,8,462504,NaN,2006,Action|Adventure|Biography|Drama|War,not mension
8,9,NaN,NaN,2020,Action|Adventure|Biography|Drama|Western,10
9,10,163225,The Revenant,2015,Action|Adventure|Biography|Drama|Western,9
10,11,1663202,NaN,2015,Action|Adventure|Biography|Drama|Western,9
11,12,1663202,The Revenant,2021,Action|Adventure|Biography|Drama|Western,6

# keep_default_na value to default setting

In [48]:
df = pd.read_csv('Data/Movies_clean.csv',keep_default_na=True)
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

# Replace method and np.nan

In [51]:
df.dtypes

USER_ID             object
MOVIE_ID           float64
MOVIE_TITLE         object
PRODUCTION_YEAR     object
GENRES              object
RATING              object
dtype: object

In [45]:
pd.read_csv("Data/Movies_clean.csv")

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [49]:
df.replace(to_replace='not available',value=None,inplace=True)

In [50]:
df

   USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR       GENRES RATING
0      101     201.0      Inception            2010       Sci-Fi    8.8
1      102     202.0        Titanic            1997      Romance    7.8
2      103     203.0         Avatar            2009       Action    NaN
3      104     204.0  The Godfather            1972        Crime    9.2
4      105     205.0            NaN            1994          NaN    8.5
5      NaN     206.0          Joker            None     Thriller    8.7
6      107       NaN      Gladiator             NaN        Drama   None
7     None     208.0      not value            2019  not mension    9.0
8      109     209.0   Interstellar            2014       Sci-Fi    NaN
9      110       NaN            NaN            2009          NaN    8.2
10     NaN     211.0         Frozen             NaN       Comedy    NaN
11     112     213.0         Matrix             NaN       Action    7.9
12     NaN       NaN            NaN            2003          NaN    NaN

In [52]:
df.replace('not mension',np.nan,inplace=True)

In [53]:
df

   USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR    GENRES RATING
0      101     201.0      Inception            2010    Sci-Fi    8.8
1      102     202.0        Titanic            1997   Romance    7.8
2      103     203.0         Avatar            2009    Action    NaN
3      104     204.0  The Godfather            1972     Crime    9.2
4      105     205.0            NaN            1994       NaN    8.5
5      NaN     206.0          Joker            None  Thriller    8.7
6      107       NaN      Gladiator             NaN     Drama   None
7     None     208.0      not value            2019       NaN    9.0
8      109     209.0   Interstellar            2014    Sci-Fi    NaN
9      110       NaN            NaN            2009       NaN    8.2
10     NaN     211.0         Frozen             NaN    Comedy    NaN
11     112     213.0         Matrix             NaN    Action    7.9
12     NaN       NaN            NaN            2003       NaN    NaN

# Replace method with specific value

In [54]:
df.dtypes

USER_ID             object
MOVIE_ID           float64
MOVIE_TITLE         object
PRODUCTION_YEAR     object
GENRES              object
RATING              object
dtype: object

In [57]:
df['MOVIE_ID'].values

array([201., 202., 203., 204., 205., 206.,  nan, 208., 209.,  nan, 211.,
       213.,  nan])

In [60]:
df.dtypes

USER_ID            object
MOVIE_ID           object
MOVIE_TITLE        object
PRODUCTION_YEAR    object
GENRES             object
RATING             object
dtype: object

In [61]:
df.dtypes

USER_ID            object
MOVIE_ID           object
MOVIE_TITLE        object
PRODUCTION_YEAR    object
GENRES             object
RATING             object
dtype: object

In [62]:
df['USER_ID'].values

array(['101', '102', '103', '104', '105', nan, '107', None, '109', '110',
       nan, '112', nan], dtype=object)

In [63]:
df.replace('104',12,inplace=True)
df

   USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR    GENRES RATING
0      101   batman      Inception            2010    Sci-Fi    8.8
1      102    202.0        Titanic            1997   Romance    7.8
2      103    203.0         Avatar            2009    Action    NaN
3       12    204.0  The Godfather            1972     Crime    9.2
4      105    205.0            NaN            1994       NaN    8.5
5      NaN    206.0          Joker            None  Thriller    8.7
6      107      NaN      Gladiator             NaN     Drama   None
7     None    208.0      not value            2019       NaN    9.0
8      109    209.0   Interstellar            2014    Sci-Fi    NaN
9      110      NaN            NaN            2009       NaN    8.2
10     NaN    211.0         Frozen             NaN    Comedy    NaN
11     112    213.0         Matrix             NaN    Action    7.9
12     NaN      NaN            NaN            2003       NaN    NaN

In [64]:
df['USER_ID'].values

array(['101', '102', '103', 12, '105', nan, '107', None, '109', '110',
       nan, '112', nan], dtype=object)

In [65]:
df.replace(['101', '102', '103'],[1,1,1],inplace=True)
df

   USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR    GENRES RATING
0        1   batman      Inception            2010    Sci-Fi    8.8
1        1    202.0        Titanic            1997   Romance    7.8
2        1    203.0         Avatar            2009    Action    NaN
3       12    204.0  The Godfather            1972     Crime    9.2
4      105    205.0            NaN            1994       NaN    8.5
5      NaN    206.0          Joker            None  Thriller    8.7
6      107      NaN      Gladiator             NaN     Drama   None
7     None    208.0      not value            2019       NaN    9.0
8      109    209.0   Interstellar            2014    Sci-Fi    NaN
9      110      NaN            NaN            2009       NaN    8.2
10     NaN    211.0         Frozen             NaN    Comedy    NaN
11     112    213.0         Matrix             NaN    Action    7.9
12     NaN      NaN            NaN            2003       NaN    NaN

In [66]:
df.dtypes

USER_ID            object
MOVIE_ID           object
MOVIE_TITLE        object
PRODUCTION_YEAR    object
GENRES             object
RATING             object
dtype: object

In [68]:
df.replace(213.0,'batman',inplace=True)
df

   USER_ID MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR    GENRES RATING
0        1   batman      Inception            2010    Sci-Fi    8.8
1        1    202.0        Titanic            1997   Romance    7.8
2        1    203.0         Avatar            2009    Action    NaN
3       12    204.0  The Godfather            1972     Crime    9.2
4      105    205.0            NaN            1994       NaN    8.5
5      NaN    206.0          Joker            None  Thriller    8.7
6      107      NaN      Gladiator             NaN     Drama   None
7     None    208.0      not value            2019       NaN    9.0
8      109    209.0   Interstellar            2014    Sci-Fi    NaN
9      110      NaN            NaN            2009       NaN    8.2
10     NaN    211.0         Frozen             NaN    Comedy    NaN
11     112   batman         Matrix             NaN    Action    7.9
12     NaN      NaN            NaN            2003       NaN    NaN

In [69]:
df.replace({"MOVIE_ID":"batman"},208.0,inplace=True)
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7320\3124307013.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({"MOVIE_ID":"batman"},208.0,inplace=True)

   USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR    GENRES RATING
0        1     208.0      Inception            2010    Sci-Fi    8.8
1        1     202.0        Titanic            1997   Romance    7.8
2        1     203.0         Avatar            2009    Action    NaN
3       12     204.0  The Godfather            1972     Crime    9.2
4      105     205.0            NaN            1994       NaN    8.5
5      NaN     206.0          Joker            None  Thriller    8.7
6      107       NaN      Gladiator             NaN     Drama   None
7     None     208.0      not value            2019       NaN    9.0
8      109     209.0   Interstellar            2014    Sci-Fi    NaN
9      110       NaN            NaN            2009       NaN    8.2
10     NaN     211.0         Frozen             NaN    Comedy    NaN
11     112     208.0         Matrix             NaN    Action    7.9
12     NaN       NaN            NaN            2003       NaN    NaN

# isnull() and sum()

In [71]:
df = pd.read_csv('Data/Movies_clean.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [72]:
df.isnull()     # find empty cells

    USER_ID  MOVIE_ID  MOVIE_TITLE  PRODUCTION_YEAR  GENRES  RATING
0     False     False        False            False   False   False
1     False     False        False            False   False   False
2     False     False        False            False   False    True
3     False     False        False            False   False   False
4     False     False         True            False    True   False
5      True     False        False            False   False   False
6     False      True        False             True   False   False
7     False     False        False            False   False   False
8     False     False        False            False   False    True
9     False      True         True            False    True   False
10     True     False        False             True   False    True
11    False     False        False             True   False   False
12     True      True         True            False    True    True

In [73]:
df.isnull().sum()

USER_ID            3
MOVIE_ID           3
MOVIE_TITLE        3
PRODUCTION_YEAR    3
GENRES             3
RATING             4
dtype: int64

In [74]:
df.isnull().sum().sum()

19

In [75]:
df.shape[0]

13

In [63]:
# 20 - 15 ==> fill - number --> mean,median
# 20 < --> drop

In [76]:
df.isnull().sum()*100/(df.shape[0])

USER_ID            23.076923
MOVIE_ID           23.076923
MOVIE_TITLE        23.076923
PRODUCTION_YEAR    23.076923
GENRES             23.076923
RATING             30.769231
dtype: float64

# notnull() and sum()

In [78]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [79]:
df.shape

(13, 6)

In [80]:
df.notnull()       # find non empty cells

    USER_ID  MOVIE_ID  MOVIE_TITLE  PRODUCTION_YEAR  GENRES  RATING
0      True      True         True             True    True    True
1      True      True         True             True    True    True
2      True      True         True             True    True   False
3      True      True         True             True    True    True
4      True      True        False             True   False    True
5     False      True         True             True    True    True
6      True     False         True            False    True    True
7      True      True         True             True    True    True
8      True      True         True             True    True   False
9      True     False        False             True   False    True
10    False      True         True            False    True   False
11     True      True         True            False    True    True
12    False     False        False             True   False   False

In [81]:
df.notnull().sum()

USER_ID            10
MOVIE_ID           10
MOVIE_TITLE        10
PRODUCTION_YEAR    10
GENRES             10
RATING              9
dtype: int64

In [82]:
df.notnull().sum().sum()

59

# dropna and all inside function

In [2]:
df = pd.read_csv('Data/Movies_clean.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [3]:
df.dropna()     # by default how = any

         USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR       GENRES RATING
0            101     201.0      Inception            2010       Sci-Fi    8.8
1            102     202.0        Titanic            1997      Romance    7.8
3            104     204.0  The Godfather            1972        Crime    9.2
7  not available     208.0      not value            2019  not mension    9.0

In [5]:
df_clean['MOVIE_TITLE'].values

array(['Inception', 'Titanic', 'The Godfather', 'not value'], dtype=object)

In [6]:
df_clean  = df.dropna()
df_clean.replace(['not available','not mension','not value'],np.nan,inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14524\2951374895.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean.replace(['not available','not mension','not value'],np.nan,inplace=True)

In [7]:
# axis = 0 , axis = 1
df_clean

  USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR   GENRES RATING
0     101     201.0      Inception            2010   Sci-Fi    8.8
1     102     202.0        Titanic            1997  Romance    7.8
3     104     204.0  The Godfather            1972    Crime    9.2
7     NaN     208.0            NaN            2019      NaN    9.0

In [9]:
df_clean.dropna(how='any')      # if raw any one value is nan then it will drop

  USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR   GENRES RATING
0     101     201.0      Inception            2010   Sci-Fi    8.8
1     102     202.0        Titanic            1997  Romance    7.8
3     104     204.0  The Godfather            1972    Crime    9.2

In [12]:
df_clean.loc[7,['MOVIE_ID','PRODUCTION_YEAR','RATING']] = np.nan

In [14]:
df_clean.dropna(how='all')

  USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR   GENRES RATING
0     101     201.0      Inception            2010   Sci-Fi    8.8
1     102     202.0        Titanic            1997  Romance    7.8
3     104     204.0  The Godfather            1972    Crime    9.2

In [15]:
df.isna().sum()

USER_ID            3
MOVIE_ID           3
MOVIE_TITLE        3
PRODUCTION_YEAR    3
GENRES             3
RATING             4
dtype: int64

In [16]:
df.notnull().sum()

USER_ID            10
MOVIE_ID           10
MOVIE_TITLE        10
PRODUCTION_YEAR    10
GENRES             10
RATING              9
dtype: int64

In [18]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [20]:
df.loc[12,'PRODUCTION_YEAR'] = np.nan

In [23]:
df.dropna(how='all')     # if raw all value is nan then drop

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9

In [24]:
df = pd.read_csv('Data/Movies_clean.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [25]:
df.shape

(13, 6)

In [26]:
df.dropna(axis=0,thresh=2).shape

(12, 6)

In [28]:
df.dropna(axis=0,thresh=1)  #if one value in raw   thresh=1 
# thresh parameter value desides the minimum number of non-NAN values needed in a "RAW" not to drop.

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [ ]:
# for x in range(0,10):
#     print(df.dropna(axis=0,thresh=x))

In [29]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [30]:
df.dropna(subset=['RATING'])

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
9,110,NaN,NaN,2009,NaN,8.2
11,112,213.0,Matrix,NaN,Action,7.9

# how to drop column

In [32]:
df = pd.read_csv('Data/Movies_clean.csv')
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [33]:
df.drop(columns='MOVIE_TITLE',inplace=True)
df

          USER_ID  MOVIE_ID PRODUCTION_YEAR       GENRES         RATING
0             101     201.0            2010       Sci-Fi            8.8
1             102     202.0            1997      Romance            7.8
2             103     203.0            2009       Action            NaN
3             104     204.0            1972        Crime            9.2
4             105     205.0            1994          NaN            8.5
5             NaN     206.0   not available     Thriller            8.7
6             107       NaN             NaN        Drama  not available
7   not available     208.0            2019  not mension            9.0
8             109     209.0            2014       Sci-Fi            NaN
9             110       NaN            2009          NaN            8.2
10            NaN     211.0             NaN       Comedy            NaN
11            112     213.0             NaN       Action            7.9
12            NaN       NaN            2003          NaN            NaN

# how to drop column

In [34]:
df = pd.read_csv("Data/Movies_clean.csv")
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [35]:
df.drop(columns='MOVIE_TITLE',inplace=True)
df

          USER_ID  MOVIE_ID PRODUCTION_YEAR       GENRES         RATING
0             101     201.0            2010       Sci-Fi            8.8
1             102     202.0            1997      Romance            7.8
2             103     203.0            2009       Action            NaN
3             104     204.0            1972        Crime            9.2
4             105     205.0            1994          NaN            8.5
5             NaN     206.0   not available     Thriller            8.7
6             107       NaN             NaN        Drama  not available
7   not available     208.0            2019  not mension            9.0
8             109     209.0            2014       Sci-Fi            NaN
9             110       NaN            2009          NaN            8.2
10            NaN     211.0             NaN       Comedy            NaN
11            112     213.0             NaN       Action            7.9
12            NaN       NaN            2003          NaN            NaN

# filling data (fillna)

In [36]:
df = pd.read_csv("Data/Movies_clean.csv")
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [ ]:
# fillna with specific value

In [37]:
df.fillna(5)    # inplace = true   #fill the data where nan has

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,5
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,5,1994,5,8.5
5,5,206.0,Joker,not available,Thriller,8.7
6,107,5.0,Gladiator,5,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,5
9,110,5.0,5,2009,5,8.2
10,5,211.0,Frozen,5,Comedy,5
11,112,213.0,Matrix,5,Action,7.9
12,5,5.0,5,2003,5,5

In [38]:
# fillna with spacific value in perticuler column

In [39]:
df.fillna({'MOVIE_TITLE':'Batman','RATING':6})

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,6
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,Batman,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,6
9,110,NaN,Batman,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,6
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,Batman,2003,NaN,6

In [ ]:
# ffill method   #f = forward

In [41]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [42]:
df.fillna(method='ffill')
# it is must to have one value at top else as we can see rating has NAN value ramain

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14524\4156025296.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,7.8
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,The Godfather,1994,Crime,8.5
5,105,206.0,Joker,not available,Thriller,8.7
6,107,206.0,Gladiator,not available,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,9.0
9,110,209.0,Interstellar,2009,Sci-Fi,8.2
10,110,211.0,Frozen,2009,Comedy,8.2
11,112,213.0,Matrix,2009,Action,7.9
12,112,213.0,Matrix,2003,Action,7.9

In [43]:
df.fillna(method='ffill',limit=2)    # axis also pass in fillna

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_14524\4275621378.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill',limit=2)    # axis also pass in fillna

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,7.8
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,The Godfather,1994,Crime,8.5
5,105,206.0,Joker,not available,Thriller,8.7
6,107,206.0,Gladiator,not available,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,9.0
9,110,209.0,Interstellar,2009,Sci-Fi,8.2
10,110,211.0,Frozen,2009,Comedy,8.2
11,112,213.0,Matrix,2009,Action,7.9
12,112,213.0,Matrix,2003,Action,7.9

In [45]:
import warnings
warnings.filterwarnings('ignore')

In [46]:
# bfill method    #b = backward

In [47]:
df.fillna(method='bfill')

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,9.2
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,Joker,1994,Thriller,8.5
5,107,206.0,Joker,not available,Thriller,8.7
6,107,208.0,Gladiator,2019,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,8.2
9,110,211.0,Frozen,2009,Comedy,8.2
10,112,211.0,Frozen,2003,Comedy,7.9
11,112,213.0,Matrix,2003,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [48]:
df.fillna(method='bfill',limit=2)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,9.2
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,Joker,1994,Thriller,8.5
5,107,206.0,Joker,not available,Thriller,8.7
6,107,208.0,Gladiator,2019,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,8.2
9,110,211.0,Frozen,2009,Comedy,8.2
10,112,211.0,Frozen,2003,Comedy,7.9
11,112,213.0,Matrix,2003,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [49]:
df['MOVIE_TITLE'].fillna(method='bfill',limit=2)

0         Inception
1           Titanic
2            Avatar
3     The Godfather
4             Joker
5             Joker
6         Gladiator
7         not value
8      Interstellar
9            Frozen
10           Frozen
11           Matrix
12              NaN
Name: MOVIE_TITLE, dtype: object

# replace method and its parameters

In [50]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,Inception,2010,Sci-Fi,8.8
1,102,202.0,Titanic,1997,Romance,7.8
2,103,203.0,Avatar,2009,Action,NaN
3,104,204.0,The Godfather,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,Joker,not available,Thriller,8.7
6,107,NaN,Gladiator,NaN,Drama,not available
7,not available,208.0,not value,2019,not mension,9.0
8,109,209.0,Interstellar,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,Frozen,NaN,Comedy,NaN
11,112,213.0,Matrix,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [51]:
# convert all string values in integer using Regex(regular expression) parameter
df.replace('[A-Za-z]',24,regex=True)    #24 is depends on you

   USER_ID  MOVIE_ID  MOVIE_TITLE PRODUCTION_YEAR  GENRES RATING
0      101     201.0         24.0            2010    24.0    8.8
1      102     202.0         24.0            1997    24.0    7.8
2      103     203.0         24.0            2009    24.0    NaN
3      104     204.0         24.0            1972    24.0    9.2
4      105     205.0          NaN            1994     NaN    8.5
5      NaN     206.0         24.0              24    24.0    8.7
6      107       NaN         24.0             NaN    24.0     24
7       24     208.0         24.0            2019    24.0    9.0
8      109     209.0         24.0            2014    24.0    NaN
9      110       NaN          NaN            2009     NaN    8.2
10     NaN     211.0         24.0             NaN    24.0    NaN
11     112     213.0         24.0             NaN    24.0    7.9
12     NaN       NaN          NaN            2003     NaN    NaN

In [52]:
df.replace({"MOVIE_TITLE":'[A-Za-z]'},50,regex=True)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,101,201.0,50.0,2010,Sci-Fi,8.8
1,102,202.0,50.0,1997,Romance,7.8
2,103,203.0,50.0,2009,Action,NaN
3,104,204.0,50.0,1972,Crime,9.2
4,105,205.0,NaN,1994,NaN,8.5
5,NaN,206.0,50.0,not available,Thriller,8.7
6,107,NaN,50.0,NaN,Drama,not available
7,not available,208.0,50.0,2019,not mension,9.0
8,109,209.0,50.0,2014,Sci-Fi,NaN
9,110,NaN,NaN,2009,NaN,8.2
10,NaN,211.0,50.0,NaN,Comedy,NaN
11,112,213.0,50.0,NaN,Action,7.9
12,NaN,NaN,NaN,2003,NaN,NaN

In [55]:
df['USER_ID'] = range(1,14)

In [56]:
df

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,201.0,Inception,2010,Sci-Fi,8.8
1,2,202.0,Titanic,1997,Romance,7.8
2,3,203.0,Avatar,2009,Action,NaN
3,4,204.0,The Godfather,1972,Crime,9.2
4,5,205.0,NaN,1994,NaN,8.5
5,6,206.0,Joker,not available,Thriller,8.7
6,7,NaN,Gladiator,NaN,Drama,not available
7,8,208.0,not value,2019,not mension,9.0
8,9,209.0,Interstellar,2014,Sci-Fi,NaN
9,10,NaN,NaN,2009,NaN,8.2
10,11,211.0,Frozen,NaN,Comedy,NaN
11,12,213.0,Matrix,NaN,Action,7.9
12,13,NaN,NaN,2003,NaN,NaN

In [57]:
# method in replace
df.replace("5",method="ffill")

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,201.0,Inception,2010,Sci-Fi,8.8
1,2,202.0,Titanic,1997,Romance,7.8
2,3,203.0,Avatar,2009,Action,NaN
3,4,204.0,The Godfather,1972,Crime,9.2
4,5,205.0,NaN,1994,NaN,8.5
5,6,206.0,Joker,not available,Thriller,8.7
6,7,NaN,Gladiator,NaN,Drama,not available
7,8,208.0,not value,2019,not mension,9.0
8,9,209.0,Interstellar,2014,Sci-Fi,NaN
9,10,NaN,NaN,2009,NaN,8.2
10,11,211.0,Frozen,NaN,Comedy,NaN
11,12,213.0,Matrix,NaN,Action,7.9
12,13,NaN,NaN,2003,NaN,NaN

In [58]:
df.replace("9",method="ffill",limit=1)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,201.0,Inception,2010,Sci-Fi,8.8
1,2,202.0,Titanic,1997,Romance,7.8
2,3,203.0,Avatar,2009,Action,NaN
3,4,204.0,The Godfather,1972,Crime,9.2
4,5,205.0,NaN,1994,NaN,8.5
5,6,206.0,Joker,not available,Thriller,8.7
6,7,NaN,Gladiator,NaN,Drama,not available
7,8,208.0,not value,2019,not mension,9.0
8,9,209.0,Interstellar,2014,Sci-Fi,NaN
9,10,NaN,NaN,2009,NaN,8.2
10,11,211.0,Frozen,NaN,Comedy,NaN
11,12,213.0,Matrix,NaN,Action,7.9
12,13,NaN,NaN,2003,NaN,NaN

In [59]:
df.replace("9",method="bfill")

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,201.0,Inception,2010,Sci-Fi,8.8
1,2,202.0,Titanic,1997,Romance,7.8
2,3,203.0,Avatar,2009,Action,NaN
3,4,204.0,The Godfather,1972,Crime,9.2
4,5,205.0,NaN,1994,NaN,8.5
5,6,206.0,Joker,not available,Thriller,8.7
6,7,NaN,Gladiator,NaN,Drama,not available
7,8,208.0,not value,2019,not mension,9.0
8,9,209.0,Interstellar,2014,Sci-Fi,NaN
9,10,NaN,NaN,2009,NaN,8.2
10,11,211.0,Frozen,NaN,Comedy,NaN
11,12,213.0,Matrix,NaN,Action,7.9
12,13,NaN,NaN,2003,NaN,NaN

In [60]:
df.replace("9",method="bfill",limit=1)

,USER_ID,MOVIE_ID,MOVIE_TITLE,PRODUCTION_YEAR,GENRES,RATING
0,1,201.0,Inception,2010,Sci-Fi,8.8
1,2,202.0,Titanic,1997,Romance,7.8
2,3,203.0,Avatar,2009,Action,NaN
3,4,204.0,The Godfather,1972,Crime,9.2
4,5,205.0,NaN,1994,NaN,8.5
5,6,206.0,Joker,not available,Thriller,8.7
6,7,NaN,Gladiator,NaN,Drama,not available
7,8,208.0,not value,2019,not mension,9.0
8,9,209.0,Interstellar,2014,Sci-Fi,NaN
9,10,NaN,NaN,2009,NaN,8.2
10,11,211.0,Frozen,NaN,Comedy,NaN
11,12,213.0,Matrix,NaN,Action,7.9
12,13,NaN,NaN,2003,NaN,NaN

# interpolation

In [1]:
df = pd.read_csv(r"Data/Movies_clean.csv")
df

NameError: name 'pd' is not defined

In [6]:
df['USER_ID'] = pd.to_numeric(df['USER_ID'], errors='coerce').astype('Int64')  # Nullable Integer
df['MOVIE_ID'] = pd.to_numeric(df['MOVIE_ID'], errors='coerce').astype('Int64')
df['RATING'] = pd.to_numeric(df['RATING'], errors='coerce').astype('float')

In [7]:
df.dtypes

USER_ID              Int64
MOVIE_ID             Int64
MOVIE_TITLE         object
PRODUCTION_YEAR     object
GENRES              object
RATING             float64
dtype: object

In [9]:
df.interpolate(method='linear')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\1321276365.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear')

    USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR       GENRES  RATING
0     101.0     201.0      Inception            2010       Sci-Fi    8.80
1     102.0     202.0        Titanic            1997      Romance    7.80
2     103.0     203.0         Avatar            2009       Action    8.50
3     104.0     204.0  The Godfather            1972        Crime    9.20
4     105.0     205.0            NaN            1994          NaN    8.50
5     106.0     206.0          Joker   not available     Thriller    8.70
6     107.0     207.0      Gladiator             NaN        Drama    8.85
7     108.0     208.0      not value            2019  not mension    9.00
8     109.0     209.0   Interstellar            2014       Sci-Fi    8.60
9     110.0     210.0            NaN            2009          NaN    8.20
10    111.0     211.0         Frozen             NaN       Comedy    8.05
11    112.0     213.0         Matrix             NaN       Action    7.90
12    112.0     213.0            NaN            2003          NaN    7.90

In [10]:
df.interpolate(method='linear')   #average value between 2 data

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\1326321047.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='linear')   #average value between 2 data

    USER_ID  MOVIE_ID    MOVIE_TITLE PRODUCTION_YEAR       GENRES  RATING
0     101.0     201.0      Inception            2010       Sci-Fi    8.80
1     102.0     202.0        Titanic            1997      Romance    7.80
2     103.0     203.0         Avatar            2009       Action    8.50
3     104.0     204.0  The Godfather            1972        Crime    9.20
4     105.0     205.0            NaN            1994          NaN    8.50
5     106.0     206.0          Joker   not available     Thriller    8.70
6     107.0     207.0      Gladiator             NaN        Drama    8.85
7     108.0     208.0      not value            2019  not mension    9.00
8     109.0     209.0   Interstellar            2014       Sci-Fi    8.60
9     110.0     210.0            NaN            2009          NaN    8.20
10    111.0     211.0         Frozen             NaN       Comedy    8.05
11    112.0     213.0         Matrix             NaN       Action    7.90
12    112.0     213.0            NaN            2003          NaN    7.90

In [11]:
df = pd.read_csv(r"Data/Movieratingdata4.csv",parse_dates=["DATE"])
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\2904213943.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df = pd.read_csv(r"Data/Movieratingdata4.csv",parse_dates=["DATE"])

        DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0 2021-01-25      1.0   4642044           2015.0       A    10.0
1 2021-02-25      NaN   4642044              NaN     NaN     NaN
2 2021-03-25      3.0   1245897           2014.0     NaN     8.0
3 2021-04-25      NaN   1390411           2015.0     NaN     6.0
4 2021-05-25      NaN   6306064              NaN       B     NaN
5 2021-06-25      NaN   6306064           2020.0       D     4.0
6 2021-07-25      7.0   2719848           2015.0       E     4.0
7 2021-08-25      8.0    462504           2006.0       B     9.0
8 2021-09-25      9.0     25468           2015.0       F     NaN
9 2021-10-25     10.0   2564789           2015.0       D     9.0

In [12]:
df.dtypes

DATE               datetime64[ns]
USER_ID                   float64
MOVIE_ID                    int64
PRODUCTION_YEAR           float64
Section                    object
RATING                    float64
dtype: object

In [13]:
type(df.DATE[0])

pandas._libs.tslibs.timestamps.Timestamp

In [14]:
df.set_index('DATE',inplace=True)
df

            USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
DATE
2021-01-25      1.0   4642044           2015.0       A    10.0
2021-02-25      NaN   4642044              NaN     NaN     NaN
2021-03-25      3.0   1245897           2014.0     NaN     8.0
2021-04-25      NaN   1390411           2015.0     NaN     6.0
2021-05-25      NaN   6306064              NaN       B     NaN
2021-06-25      NaN   6306064           2020.0       D     4.0
2021-07-25      7.0   2719848           2015.0       E     4.0
2021-08-25      8.0    462504           2006.0       B     9.0
2021-09-25      9.0     25468           2015.0       F     NaN
2021-10-25     10.0   2564789           2015.0       D     9.0

In [15]:
df.interpolate(method='time')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\722817345.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='time')

              USER_ID  MOVIE_ID  PRODUCTION_YEAR Section     RATING
DATE
2021-01-25   1.000000   4642044      2015.000000       A  10.000000
2021-02-25   2.050847   4642044      2014.474576     NaN   8.949153
2021-03-25   3.000000   1245897      2014.000000     NaN   8.000000
2021-04-25   4.016393   1390411      2015.000000     NaN   6.000000
2021-05-25   5.000000   6306064      2017.459016       B   5.016393
2021-06-25   6.016393   6306064      2020.000000       D   4.000000
2021-07-25   7.000000   2719848      2015.000000       E   4.000000
2021-08-25   8.000000    462504      2006.000000       B   9.000000
2021-09-25   9.000000     25468      2015.000000       F   9.000000
2021-10-25  10.000000   2564789      2015.000000       D   9.000000

In [16]:
df = pd.read_csv(r"Data/Movieratingdata4.csv",index_col=["MOVIE_ID"])
df

                DATE  USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044   25-01-2021      1.0           2015.0       A    10.0
4642044   25-02-2021      NaN              NaN     NaN     NaN
1245897   25-03-2021      3.0           2014.0     NaN     8.0
1390411   25-04-2021      NaN           2015.0     NaN     6.0
6306064   25-05-2021      NaN              NaN       B     NaN
6306064   25-06-2021      NaN           2020.0       D     4.0
2719848   25-07-2021      7.0           2015.0       E     4.0
462504    25-08-2021      8.0           2006.0       B     9.0
25468     25-09-2021      9.0           2015.0       F     NaN
2564789   25-10-2021     10.0           2015.0       D     9.0

In [17]:
df.interpolate(method='index')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\2515484856.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='index')

                DATE    USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044   25-01-2021   1.000000           2015.0       A    10.0
4642044   25-02-2021   1.000000           2015.0     NaN    10.0
1245897   25-03-2021   3.000000           2014.0     NaN     8.0
1390411   25-04-2021   3.767006           2015.0     NaN     6.0
6306064   25-05-2021   1.000000           2020.0       B     4.0
6306064   25-06-2021   1.000000           2020.0       D     4.0
2719848   25-07-2021   7.000000           2015.0       E     4.0
462504    25-08-2021   8.000000           2006.0       B     9.0
25468     25-09-2021   9.000000           2015.0       F     9.0
2564789   25-10-2021  10.000000           2015.0       D     9.0

In [18]:
df.interpolate(method='nearest')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\1654062127.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='nearest')

                DATE  USER_ID  PRODUCTION_YEAR Section  RATING
MOVIE_ID
4642044   25-01-2021      1.0           2015.0       A    10.0
4642044   25-02-2021      1.0           2015.0     NaN    10.0
1245897   25-03-2021      3.0           2014.0     NaN     8.0
1390411   25-04-2021      3.0           2015.0     NaN     6.0
6306064   25-05-2021      NaN           2020.0       B     4.0
6306064   25-06-2021      NaN           2020.0       D     4.0
2719848   25-07-2021      7.0           2015.0       E     4.0
462504    25-08-2021      8.0           2006.0       B     9.0
25468     25-09-2021      9.0           2015.0       F     NaN
2564789   25-10-2021     10.0           2015.0       D     9.0

In [19]:
df = pd.read_csv(r"Data/Movieratingdata4.csv")
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      NaN   4642044              NaN     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064              NaN       B     NaN
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [20]:
df.interpolate(limit=1)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\1270544217.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit=1)

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5     NaN     9.0
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      4.0   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064           2017.5       B     5.0
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [21]:
df.interpolate(limit_direction="backward",limit=2)  # default = forward

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\3590120624.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_direction="backward",limit=2)  # default = forward

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5     NaN     9.0
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      5.0   6306064           2017.5       B     5.0
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [22]:
df.interpolate(limit_direction="both",limit=2)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20668\167825398.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(limit_direction="both",limit=2)

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      2.0   4642044           2014.5     NaN     9.0
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      4.0   1390411           2015.0     NaN     6.0
4  25-05-2021      5.0   6306064           2017.5       B     5.0
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     9.0
9  25-10-2021     10.0   2564789           2015.0       D     9.0

# main method

In [23]:
df = pd.read_csv(r"Data/Movieratingdata4.csv")
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      NaN   4642044              NaN     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      NaN   1390411           2015.0     NaN     6.0
4  25-05-2021      NaN   6306064              NaN       B     NaN
5  25-06-2021      NaN   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [24]:
df.isnull()

    DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR  Section  RATING
0  False    False     False            False    False   False
1  False     True     False             True     True    True
2  False    False     False            False     True   False
3  False     True     False            False     True   False
4  False     True     False             True    False    True
5  False     True     False            False    False   False
6  False    False     False            False    False   False
7  False    False     False            False    False   False
8  False    False     False            False    False    True
9  False    False     False            False    False   False

In [25]:
df.isnull().sum()

DATE               0
USER_ID            4
MOVIE_ID           0
PRODUCTION_YEAR    2
Section            3
RATING             3
dtype: int64

In [26]:
df.dtypes

DATE                object
USER_ID            float64
MOVIE_ID             int64
PRODUCTION_YEAR    float64
Section             object
RATING             float64
dtype: object

In [24]:
df['RATING'] = df['RATING'].fillna(df['RATING'].mean())
df

         DATE    USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021   1.000000   4642044           2015.0       A    10.0
1  25-02-2021   6.333333   4642044              NaN     NaN     NaN
2  25-03-2021   3.000000   1245897           2014.0     NaN     8.0
3  25-04-2021   6.333333   1390411           2015.0     NaN     6.0
4  25-05-2021   6.333333   6306064              NaN       B     NaN
5  25-06-2021   6.333333   6306064           2020.0       D     4.0
6  25-07-2021   7.000000   2719848           2015.0       E     4.0
7  25-08-2021   8.000000    462504           2006.0       B     9.0
8  25-09-2021   9.000000     25468           2015.0       F     NaN
9  25-10-2021  10.000000   2564789           2015.0       D     9.0

In [27]:
xz = df['USER_ID'].mean()

In [28]:
ro = round(xz,0)
ro

6.0

In [29]:
df = pd.read_csv(r"Data/Movieratingdata4.csv")
df['USER_ID'] = df['USER_ID'].fillna(ro)
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      6.0   4642044              NaN     NaN     NaN
2  25-03-2021      3.0   1245897           2014.0     NaN     8.0
3  25-04-2021      6.0   1390411           2015.0     NaN     6.0
4  25-05-2021      6.0   6306064              NaN       B     NaN
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0

In [1]:
df['Section'].mode()

NameError: name 'df' is not defined

In [34]:
df['Section'] = df['Section'].fillna(df['Section'].mode()[0])
df

         DATE  USER_ID  MOVIE_ID  PRODUCTION_YEAR Section  RATING
0  25-01-2021      1.0   4642044           2015.0       A    10.0
1  25-02-2021      6.0   4642044              NaN       B     NaN
2  25-03-2021      3.0   1245897           2014.0       B     8.0
3  25-04-2021      6.0   1390411           2015.0       B     6.0
4  25-05-2021      6.0   6306064              NaN       B     NaN
5  25-06-2021      6.0   6306064           2020.0       D     4.0
6  25-07-2021      7.0   2719848           2015.0       E     4.0
7  25-08-2021      8.0    462504           2006.0       B     9.0
8  25-09-2021      9.0     25468           2015.0       F     NaN
9  25-10-2021     10.0   2564789           2015.0       D     9.0