In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"Data/imdb_movie_data_2023.csv"

In [3]:
data = pd.read_csv(path)
data

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

# Filtering

In [4]:
data['Year']>2020

0        True
1        True
2        True
3        True
4        True
        ...
1945    False
1946    False
1947    False
1948    False
1949    False
Name: Year, Length: 1950, dtype: bool

In [5]:
data1 = data[data['Year']>2020]
data1

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1907,1908,Missing,7.1,54000.0,66.0,"Drama, Mystery, Thriller",PG-13,2023,1h 51m,"Tim Griffin, Ava Zaria Lee, Nia Long, Kimberly...",Nicholas D. JohnsonWill Merrick
1917,1918,Memory,5.7,34000.0,41.0,"Action, Crime, Thriller",R,2022,1h 54m,"Liam Neeson, Guy Pearce, Taj Atwal, Harold Torres",Martin Campbell
1928,1929,Boudica: Queen of War,4.4,1600.0,NaN,NaN,R,2023,1h 41m,NaN,NaN
1937,1938,Occupied City,7.1,141.0,75.0,"Documentary, History, War",PG-13,2023,4h 6m,Melanie Hyams,Steve McQueen
1944,1945,Annette,6.3,22000.0,67.0,"Drama, Musical, Romance",R,2021,2h 21m,"Adam Driver, Marion Cotillard, Simon Helberg, ...",Leos Carax

In [6]:
data[data['Moive Name'].duplicated()]['Moive Name']

98             Miracle on 34th Street
158                  The Color Purple
370                              Dune
422                 A Christmas Carol
514                     The Lion King
532                   Black Christmas
561                          Godzilla
694                            Scream
794                         The Mummy
862                          Vacation
1046                A Christmas Carol
1084                           Legend
1099                     Little Women
1187                       Wrong Turn
1204             Beauty and the Beast
1240               Planet of the Apes
1352                  Black Christmas
1443                            Crash
1450                  West Side Story
1463                       Cinderella
1496                          Aladdin
1505                          RoboCop
1521     Teenage Mutant Ninja Turtles
1542                           Lolita
1562           Leave the World Behind
1574               The Girl Next Door
1616                         Hercules
1690                           Frozen
1710                          Ben-Hur
1763              Conan the Barbarian
1809                          Hellboy
1834                       Hellraiser
1849                           Carrie
1873               The Little Mermaid
1883                   The Karate Kid
1917                           Memory
Name: Moive Name, dtype: object

# filtering with and

### Year > 1980 and Moive Name

In [7]:
data2 = data[(data['Year']>1980) & (data['Moive Name']==' The Lion King')]
data2

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
507,508,The Lion King,8.5,1100000.0,88.0,"Animation, Adventure, Drama",G,1994,1h 28m,"Matthew Broderick, Jeremy Irons, James Earl Jo...",Roger AllersRob Minkoff
514,515,The Lion King,6.8,262000.0,55.0,"Animation, Adventure, Drama",PG,2019,1h 58m,"Donald Glover, Beyoncé, Seth Rogen, Chiwetel E...",Jon Favreau

# filtering with or

In [8]:
data2 = data[(data['Year']>2012) | (data['Moive Name']==' The Karate Kid')]
data2

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1937,1938,Occupied City,7.1,141.0,75.0,"Documentary, History, War",PG-13,2023,4h 6m,Melanie Hyams,Steve McQueen
1941,1942,Dragged Across Concrete,6.9,54000.0,60.0,"Action, Crime, Drama",R,2018,2h 39m,"Mel Gibson, Vince Vaughn, Tory Kittles, Michae...",S. Craig Zahler
1943,1944,Transformers: Age of Extinction,5.6,328000.0,32.0,"Action, Adventure, Sci-Fi",PG-13,2014,2h 45m,"Mark Wahlberg, Nicola Peltz Beckham, Jack Reyn...",Michael Bay
1944,1945,Annette,6.3,22000.0,67.0,"Drama, Musical, Romance",R,2021,2h 21m,"Adam Driver, Marion Cotillard, Simon Helberg, ...",Leos Carax
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

# filtering with str

In [9]:
data3 = data[data['Genre'].str.contains('Adventure', na=False)]
data3
# if i do not put na = False and if GENERES colume have nan value then error will occure

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
5,6,The Hunger Games: The Ballad of Songbirds & S...,7.1,56000.0,54.0,"Action, Adventure, Drama",PG-13,2023,2h 37m,"Rachel Zegler, Tom Blyth, Viola Davis, Dexter ...",Francis Lawrence
6,7,Napoleon,6.6,66000.0,64.0,"Action, Adventure, Biography",R,2023,2h 38m,"Joaquin Phoenix, Vanessa Kirby, Tahar Rahim, R...",Ridley Scott
11,12,Barbie,7.0,417000.0,80.0,"Adventure, Comedy, Fantasy",PG-13,2023,1h 54m,"Margot Robbie, Ryan Gosling, Issa Rae, Kate Mc...",Greta Gerwig
13,14,Rebel Moon - Part One: A Child of Fire,6.3,1900.0,32.0,"Action, Adventure, Drama",PG-13,2023,2h 13m,"Sofia Boutella, Charlie Hunnam, Ed Skrein, Jen...",Zack Snyder
...,...,...,...,...,...,...,...,...,...,...,...
1908,1909,Cold Mountain,7.2,154000.0,73.0,"Adventure, Drama, Romance",R,2003,2h 34m,"Jude Law, Nicole Kidman, Renée Zellweger, Eile...",Anthony Minghella
1921,1922,Monsters,6.4,96000.0,63.0,"Adventure, Drama, Romance",R,2010,1h 34m,"Scoot McNairy, Whitney Able, Mario Zuniga Bena...",Gareth Edwards
1924,1925,Goldfinger,7.7,200000.0,87.0,"Action, Adventure, Thriller",PG,1964,1h 50m,"Sean Connery, Gert Fröbe, Honor Blackman, Shir...",Guy Hamilton
1938,1939,The Man in the Iron Mask,6.5,176000.0,48.0,"Action, Adventure, Drama",PG-13,1998,2h 12m,"Leonardo DiCaprio, Jeremy Irons, John Malkovic...",Randall Wallace
1943,1944,Transformers: Age of Extinction,5.6,328000.0,32.0,"Action, Adventure, Sci-Fi",PG-13,2014,2h 45m,"Mark Wahlberg, Nicola Peltz Beckham, Jack Reyn...",Michael Bay

In [10]:
data4 = data[(data['Genre'].str.contains('Adventure')) & (data['Year']>2015) ]
data4

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
5,6,The Hunger Games: The Ballad of Songbirds & S...,7.1,56000.0,54.0,"Action, Adventure, Drama",PG-13,2023,2h 37m,"Rachel Zegler, Tom Blyth, Viola Davis, Dexter ...",Francis Lawrence
6,7,Napoleon,6.6,66000.0,64.0,"Action, Adventure, Biography",R,2023,2h 38m,"Joaquin Phoenix, Vanessa Kirby, Tahar Rahim, R...",Ridley Scott
11,12,Barbie,7.0,417000.0,80.0,"Adventure, Comedy, Fantasy",PG-13,2023,1h 54m,"Margot Robbie, Ryan Gosling, Issa Rae, Kate Mc...",Greta Gerwig
13,14,Rebel Moon - Part One: A Child of Fire,6.3,1900.0,32.0,"Action, Adventure, Drama",PG-13,2023,2h 13m,"Sofia Boutella, Charlie Hunnam, Ed Skrein, Jen...",Zack Snyder
...,...,...,...,...,...,...,...,...,...,...,...
1842,1843,Star Trek Beyond,7.0,256000.0,68.0,"Action, Adventure, Sci-Fi",PG-13,2016,2h 2m,"Chris Pine, Zachary Quinto, Karl Urban, Zoe Sa...",Justin Lin
1888,1889,The Witches,5.4,45000.0,47.0,"Adventure, Comedy, Family",PG,2020,1h 46m,"Anne Hathaway, Octavia Spencer, Stanley Tucci,...",Robert Zemeckis
1891,1892,Rampage,6.1,182000.0,45.0,"Action, Adventure, Sci-Fi",PG-13,2018,1h 47m,"Dwayne Johnson, Naomie Harris, Malin Akerman, ...",Brad Peyton
1905,1906,Pinocchio,5.1,41000.0,38.0,"Adventure, Comedy, Drama",PG,2022,1h 45m,"Joseph Gordon-Levitt, Tom Hanks, Benjamin Evan...",Robert Zemeckis
1906,1907,The Jungle Book,7.4,289000.0,77.0,"Animation, Action, Adventure",PG,2016,1h 46m,"Neel Sethi, Bill Murray, Ben Kingsley, Idris Elba",Jon Favreau

In [11]:
data4 = data[(data['Genre'].str.contains('Adventure')) | (data['Year']>2015) ]
data4

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1938,1939,The Man in the Iron Mask,6.5,176000.0,48.0,"Action, Adventure, Drama",PG-13,1998,2h 12m,"Leonardo DiCaprio, Jeremy Irons, John Malkovic...",Randall Wallace
1941,1942,Dragged Across Concrete,6.9,54000.0,60.0,"Action, Crime, Drama",R,2018,2h 39m,"Mel Gibson, Vince Vaughn, Tory Kittles, Michae...",S. Craig Zahler
1943,1944,Transformers: Age of Extinction,5.6,328000.0,32.0,"Action, Adventure, Sci-Fi",PG-13,2014,2h 45m,"Mark Wahlberg, Nicola Peltz Beckham, Jack Reyn...",Michael Bay
1944,1945,Annette,6.3,22000.0,67.0,"Drama, Musical, Romance",R,2021,2h 21m,"Adam Driver, Marion Cotillard, Simon Helberg, ...",Leos Carax
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

# filtering with loc

In [12]:
data.loc[5,"Moive Name"]

' The Hunger Games: The Ballad of Songbirds & Snakes'

In [13]:
data.loc[0:5,"Moive Name"]

0                               Leave the World Behind
1                                                Wonka
2                                          Poor Things
3                           Killers of the Flower Moon
4                                         May December
5     The Hunger Games: The Ballad of Songbirds & S...
Name: Moive Name, dtype: object

In [14]:
filt = data['Rating']>6
data.loc[filt]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
0,1,Leave the World Behind,6.5,90000.0,67.0,"Drama, Mystery, Thriller",R,2023,2h 18m,"Julia Roberts, Mahershala Ali, Ethan Hawke, My...",Sam Esmail
1,2,Wonka,7.4,24000.0,66.0,"Adventure, Comedy, Family",PG,2023,1h 56m,"Timothée Chalamet, Gustave Die, Murray McArthu...",Paul King
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
3,4,Killers of the Flower Moon,7.8,128000.0,89.0,"Crime, Drama, History",R,2023,3h 26m,"Leonardo DiCaprio, Robert De Niro, Lily Gladst...",Martin Scorsese
4,5,May December,7.0,21000.0,85.0,"Comedy, Drama",R,2023,1h 57m,"Natalie Portman, Chris Tenzis, Charles Melton,...",Todd Haynes
...,...,...,...,...,...,...,...,...,...,...,...
1945,1946,"Definitely, Maybe",7.1,172000.0,59.0,"Comedy, Drama, Romance",PG-13,2008,1h 52m,"Ryan Reynolds, Rachel Weisz, Abigail Breslin, ...",Adam Brooks
1946,1947,The Fly,7.6,198000.0,79.0,"Drama, Horror, Sci-Fi",R,1986,1h 36m,"Jeff Goldblum, Geena Davis, John Getz, Joy Bou...",David Cronenberg
1947,1948,The Mighty Ducks,6.5,71000.0,46.0,"Comedy, Drama, Family",PG,1992,1h 44m,"Emilio Estevez, Joss Ackland, Lane Smith, Heid...",Stephen Herek
1948,1949,Little Giants,6.4,30000.0,NaN,NaN,PG,1994,1h 47m,NaN,NaN
1949,1950,American Made,7.1,203000.0,65.0,"Action, Comedy, Crime",R,2017,1h 55m,"Tom Cruise, Domhnall Gleeson, Sarah Wright, Je...",Doug Liman

In [15]:
data[data['Moive Name'].duplicated()]['Moive Name'].values

array([' Miracle on 34th Street', ' The Color Purple', ' Dune',
       ' A Christmas Carol', ' The Lion King', ' Black Christmas',
       ' Godzilla', ' Scream', ' The Mummy', ' Vacation',
       ' A Christmas Carol', ' Legend', ' Little Women', ' Wrong Turn',
       ' Beauty and the Beast', ' Planet of the Apes', ' Black Christmas',
       ' Crash', ' West Side Story', ' Cinderella', ' Aladdin',
       ' RoboCop', ' Teenage Mutant Ninja Turtles', ' Lolita',
       ' Leave the World Behind', ' The Girl Next Door', ' Hercules',
       ' Frozen', ' Ben-Hur', ' Conan the Barbarian', ' Hellboy',
       ' Hellraiser', ' Carrie', ' The Little Mermaid', ' The Karate Kid',
       ' Memory'], dtype=object)

In [16]:
filt = (data['Moive Name'] ==' The Mummy' ) | (data['Moive Name'] == ' Hellboy')
data.loc[filt]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
499,500,The Mummy,7.1,453000.0,48.0,"Action, Adventure, Fantasy",PG-13,1999,2h 4m,"Brendan Fraser, Rachel Weisz, John Hannah, Arn...",Stephen Sommers
794,795,The Mummy,5.4,203000.0,34.0,"Action, Adventure, Fantasy",PG-13,2017,1h 50m,"Tom Cruise, Sofia Boutella, Annabelle Wallis, ...",Alex Kurtzman
1489,1490,Hellboy,5.2,96000.0,31.0,"Action, Adventure, Fantasy",R,2019,2h,"David Harbour, Milla Jovovich, Ian McShane, Sa...",Neil Marshall
1809,1810,Hellboy,6.8,345000.0,72.0,"Action, Adventure, Fantasy",PG-13,2004,2h 2m,"Ron Perlman, Doug Jones, Selma Blair, John Hurt",Guillermo del Toro

In [17]:
filt = (data['Rating'] >=8) & (data['Rating'] <= 9)
data.loc[filt]

,User_Id,Moive Name,Rating,Votes,Meta Score,Genre,PG Rating,Year,Duration,Cast,Director
2,3,Poor Things,8.5,6700.0,86.0,"Comedy, Drama, Romance",R,2023,2h 21m,"Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Y...",Yorgos Lanthimos
7,8,Oppenheimer,8.4,553000.0,89.0,"Biography, Drama, History",R,2023,3h,"Cillian Murphy, Emily Blunt, Matt Damon, Rober...",Christopher Nolan
15,16,The Holdovers,8.0,24000.0,82.0,"Comedy, Drama",R,2023,2h 13m,"Paul Giamatti, Da'Vine Joy Randolph, Dominic S...",Alexander Payne
28,29,Die Hard,8.2,924000.0,72.0,"Action, Thriller",R,1988,2h 12m,"Bruce Willis, Alan Rickman, Bonnie Bedelia, Re...",John McTiernan
37,38,It's a Wonderful Life,8.6,486000.0,89.0,"Drama, Family, Fantasy",PG,1946,2h 10m,"James Stewart, Donna Reed, Lionel Barrymore, T...",Frank Capra
...,...,...,...,...,...,...,...,...,...,...,...
1795,1796,The Great Escape,8.2,255000.0,86.0,"Adventure, Drama, History",Approved,1963,2h 52m,"Steve McQueen, James Garner, Richard Attenboro...",John Sturges
1852,1853,Witness for the Prosecution,8.4,134000.0,76.0,"Crime, Drama, Mystery",Approved,1957,1h 56m,"Tyrone Power, Marlene Dietrich, Charles Laught...",Billy Wilder
1859,1860,The Bourne Ultimatum,8.0,653000.0,85.0,"Action, Mystery, Thriller",PG-13,2007,1h 55m,"Matt Damon, Edgar Ramírez, Joan Allen, Julia S...",Paul Greengrass
1892,1893,The Elephant Man,8.2,254000.0,78.0,"Biography, Drama",PG,1980,2h 4m,"Anthony Hopkins, John Hurt, Anne Bancroft, Joh...",David Lynch
1896,1897,The Apartment,8.3,192000.0,94.0,"Comedy, Drama, Romance",Approved,1960,2h 5m,"Jack Lemmon, Shirley MacLaine, Fred MacMurray,...",Billy Wilder

# apply method

In [18]:
data['Moive Name'].apply(len)

0       23
1        6
2       12
3       27
4       13
        ..
1945    18
1946     8
1947    17
1948    14
1949    14
Name: Moive Name, Length: 1950, dtype: int64

# apply lambda

In [19]:
data['Moive Name'].apply(lambda x : x.upper())

0            LEAVE THE WORLD BEHIND
1                             WONKA
2                       POOR THINGS
3        KILLERS OF THE FLOWER MOON
4                      MAY DECEMBER
                   ...
1945              DEFINITELY, MAYBE
1946                        THE FLY
1947               THE MIGHTY DUCKS
1948                  LITTLE GIANTS
1949                  AMERICAN MADE
Name: Moive Name, Length: 1950, dtype: object

In [20]:
data['Moive Name'].apply(lambda x : x.lower())

0            leave the world behind
1                             wonka
2                       poor things
3        killers of the flower moon
4                      may december
                   ...
1945              definitely, maybe
1946                        the fly
1947               the mighty ducks
1948                  little giants
1949                  american made
Name: Moive Name, Length: 1950, dtype: object

# applymap with str

In [21]:
people1 = {
   "first": ["hardik", 'mohan', 'randhir'], 
    
    "last": ["kher", 'patel', 'rana'], 
    "email": ["Hardikkher@gmail.com", 'mohanpatel@email.com', 'randhirrana@email.com']
}

In [22]:
people = pd.DataFrame(people1)
people

     first   last                  email
0   hardik   kher   Hardikkher@gmail.com
1    mohan  patel   mohanpatel@email.com
2  randhir   rana  randhirrana@email.com

In [23]:
people.applymap(len)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16656\1752903538.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  people.applymap(len)

   first  last  email
0      6     4     20
1      5     5     20
2      7     4     21

In [24]:
people.applymap(lambda x : x.upper())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16656\542873420.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  people.applymap(lambda x : x.upper())

     first   last                  email
0   HARDIK   KHER   HARDIKKHER@GMAIL.COM
1    MOHAN  PATEL   MOHANPATEL@EMAIL.COM
2  RANDHIR   RANA  RANDHIRRANA@EMAIL.COM

In [25]:
people.applymap(lambda x : x.lower())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_16656\3224123453.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  people.applymap(lambda x : x.lower())

     first   last                  email
0   hardik   kher   hardikkher@gmail.com
1    mohan  patel   mohanpatel@email.com
2  randhir   rana  randhirrana@email.com

# map() function

In [26]:
people['first'] = people['first'].map({'hardik': 'Anupam', 'randhir': 'ranvir'},na_action=None)
people

    first   last                  email
0  Anupam   kher   Hardikkher@gmail.com
1     NaN  patel   mohanpatel@email.com
2  ranvir   rana  randhirrana@email.com

# Replace method

In [27]:
people = pd.DataFrame(people1)

In [28]:
people['first'] = people['first'].replace({'hardik': 'Anupam', 'randhir': 'ranvir'})
people

    first   last                  email
0  Anupam   kher   Hardikkher@gmail.com
1   mohan  patel   mohanpatel@email.com
2  ranvir   rana  randhirrana@email.com