In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Data/survey_results_public.csv")
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [3]:
df_schema = pd.read_csv("Data/survey_results_schema.csv")

In [4]:
pd.set_option('display.float_format', '{:.2f}'.format)

In [5]:
df.describe()

,Respondent,CompTotal,ConvertedComp,WorkWeekHrs,CodeRevHrs,Age
count,88883.00,55945.00,55823.00,64503.00,49790.00,79210.00
mean,44442.00,551901414118.76,127110.74,42.13,5.08,30.34
std,25658.46,73319262253434.70,284152.30,37.29,5.51,9.18
min,1.00,0.00,0.00,1.00,0.00,1.00
25%,22221.50,20000.00,25777.50,40.00,2.00,24.00
50%,44442.00,62000.00,57287.00,40.00,4.00,29.00
75%,66662.50,120000.00,100000.00,44.75,6.00,35.00
max,88883.00,10000000000000000.00,2000000.00,4850.00,99.00,99.00

In [6]:
df['ConvertedComp'].count()

55823

In [7]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: object

In [8]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64

In [9]:
df_schema[df_schema['Column'] == 'SocialMedia']['QuestionText']

61    What social media site do you use the most?
Name: QuestionText, dtype: object

In [10]:
df['SocialMedia'].value_counts()

SocialMedia
Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: count, dtype: int64

In [11]:
df['SocialMedia'].value_counts(normalize=True)

SocialMedia
Reddit                     0.17
YouTube                    0.16
WhatsApp                   0.16
Facebook                   0.16
Twitter                    0.13
Instagram                  0.07
I don't use social media   0.07
LinkedIn                   0.05
WeChat 微信                  0.01
Snapchat                   0.01
VK ВКонта́кте              0.01
Weibo 新浪微博                 0.00
Youku Tudou 优酷             0.00
Hello                      0.00
Name: proportion, dtype: float64

In [12]:
# split
# Apply function
# combine Results

In [13]:
df['Country'].value_counts()

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [14]:
Country_grp = df.groupby(['Country'])
Country_grp

In [15]:
Country_grp.get_group('United States')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_25992\640818647.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  Country_grp.get_group('United States')

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.00,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
21,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
22,23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,22.00,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
25,26,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,34.00,Man,No,Gay or Lesbian,NaN,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88818,78292,NaN,No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A health science (ex. nursing, pharmacy, radio...",...,Somewhat less welcome now than last year,NaN,60.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
88840,82717,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,"Secondary school (e.g. American high school, G...",NaN,...,NaN,Industry news about technologies you're intere...,44.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
88844,83397,NaN,Yes,Less than once per year,NaN,"Not employed, but looking for work",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,27.00,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
88859,85642,NaN,No,Less than once per year,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",United States,No,Associate degree,"Information systems, information technology, o...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.00,"Non-binary, genderqueer, or gender non-conforming",NaN,Bisexual;Gay or Lesbian,White or of European descent,No,Appropriate in length,Easy
88877,88282,NaN,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,NaN,No,Too short,Neither easy nor difficult

In [16]:
filt = df['Country'] == 'United States'
df.loc[filt]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.00,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
12,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
21,22,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,47.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
22,23,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,22.00,Man,No,Straight / Heterosexual,Black or of African descent,No,Appropriate in length,Easy
25,26,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,34.00,Man,No,Gay or Lesbian,NaN,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88818,78292,NaN,No,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",United States,No,"Other doctoral degree (Ph.D, Ed.D., etc.)","A health science (ex. nursing, pharmacy, radio...",...,Somewhat less welcome now than last year,NaN,60.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Neither easy nor difficult
88840,82717,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,"Secondary school (e.g. American high school, G...",NaN,...,NaN,Industry news about technologies you're intere...,44.00,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Neither easy nor difficult
88844,83397,NaN,Yes,Less than once per year,NaN,"Not employed, but looking for work",United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,27.00,Woman,No,Bisexual,White or of European descent,No,Appropriate in length,Easy
88859,85642,NaN,No,Less than once per year,"OSS is, on average, of LOWER quality than prop...","Independent contractor, freelancer, or self-em...",United States,No,Associate degree,"Information systems, information technology, o...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.00,"Non-binary, genderqueer, or gender non-conforming",NaN,Bisexual;Gay or Lesbian,White or of European descent,No,Appropriate in length,Easy
88877,88282,NaN,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Not employed, but looking for work",United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,NaN,Man,No,Straight / Heterosexual,NaN,No,Too short,Neither easy nor difficult

In [17]:
filt = df['Country'] == 'United States'
df.loc[filt]['SocialMedia'].value_counts()

SocialMedia
Reddit                      5700
Twitter                     3468
Facebook                    2844
YouTube                     2463
I don't use social media    1851
Instagram                   1652
LinkedIn                    1020
WhatsApp                     609
Snapchat                     326
WeChat 微信                     93
VK ВКонта́кте                  9
Weibo 新浪微博                     8
Hello                          2
Youku Tudou 优酷                 1
Name: count, dtype: int64

In [18]:
filt = df['Country'] == 'India'
df.loc[filt]['SocialMedia'].value_counts()

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: count, dtype: int64

In [19]:
Country_grp['SocialMedia'].value_counts().head(50)

Country              SocialMedia
Afghanistan          Facebook                     15
                     YouTube                       9
                     I don't use social media      6
                     WhatsApp                      4
                     Instagram                     1
                     LinkedIn                      1
                     Twitter                       1
Albania              WhatsApp                     18
                     Facebook                     16
                     Instagram                    13
                     YouTube                      10
                     Twitter                       8
                     LinkedIn                      7
                     Reddit                        6
                     I don't use social media      4
                     Snapchat                      1
                     WeChat 微信                     1
Algeria              YouTube                      42
                     Facebook                     41
                     Twitter                      14
                     LinkedIn                      9
                     I don't use social media      7
                     Instagram                     7
                     Reddit                        2
                     WhatsApp                      2
Andorra              Facebook                      2
                     I don't use social media      2
                     Reddit                        1
                     Snapchat                      1
                     YouTube                       1
Angola               Twitter                       2
                     Facebook                      1
                     YouTube                       1
Antigua and Barbuda  YouTube                       2
                     Facebook                      1
                     Instagram                     1
                     Twitter                       1
                     VK ВКонта́кте                 1
Argentina            WhatsApp                    202
                     Twitter                      80
                     YouTube                      62
                     Instagram                    53
                     Reddit                       50
                     Facebook                     45
                     I don't use social media     22
                     LinkedIn                     16
Armenia              Facebook                     38
                     YouTube                      23
                     LinkedIn                      5
                     Instagram                     3
Name: count, dtype: int64

In [20]:
Country_grp['SocialMedia'].value_counts().loc['India']

SocialMedia
WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: count, dtype: int64

In [21]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [22]:
Country_grp['ConvertedComp'].median()

Country
Afghanistan                              6222.00
Albania                                 10818.00
Algeria                                  7878.00
Andorra                                160931.00
Angola                                   7764.00
                                          ...
Venezuela, Bolivarian Republic of...     6384.00
Viet Nam                                11892.00
Yemen                                   11940.00
Zambia                                   5040.00
Zimbabwe                                19200.00
Name: ConvertedComp, Length: 179, dtype: float64

In [23]:
Country_grp['ConvertedComp'].median().loc['India']

10080.0

In [ ]:
# count , mean , median , std , sum

In [32]:
Country_grp['ConvertedComp'].agg(['median','mean'])

                                        median      mean
Country
Afghanistan                            6222.00 101953.33
Albania                               10818.00  21833.70
Algeria                                7878.00  34924.05
Andorra                              160931.00 160931.00
Angola                                 7764.00   7764.00
...                                        ...       ...
Venezuela, Bolivarian Republic of...   6384.00  14581.63
Viet Nam                              11892.00  17233.44
Yemen                                 11940.00  16909.17
Zambia                                 5040.00  10075.38
Zimbabwe                              19200.00  34046.67

[179 rows x 2 columns]

In [33]:
Country_grp['ConvertedComp'].agg(['median','mean']).loc['India']

median   10080.00
mean     28057.66
Name: India, dtype: float64

In [35]:
filt = df['Country'] == 'India'

df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

3105

In [36]:
Country_grp['LanguageWorkedWith'].str.contains('Python').sum()

AttributeError: 'SeriesGroupBy' object has no attribute 'str'

In [37]:
Country_grp['LanguageWorkedWith'].apply(lambda x:x.str.contains('Python').sum())

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [ ]:
# what % of people from each country know Python ?

In [63]:
filt = df['LanguageWorkedWith'].str.contains('Python',na=False)
df.loc[filt]['Country'].value_counts(normalize=True).head(50)

Country
United States        0.28
India                0.09
Germany              0.07
United Kingdom       0.07
Canada               0.04
France               0.03
Australia            0.02
Netherlands          0.02
Brazil               0.02
Poland               0.02
Russian Federation   0.02
Spain                0.02
Italy                0.02
Sweden               0.01
Switzerland          0.01
Israel               0.01
Turkey               0.01
Austria              0.01
China                0.01
Belgium              0.01
Czech Republic       0.01
Iran                 0.01
Finland              0.01
Romania              0.01
Pakistan             0.01
Ukraine              0.01
Denmark              0.01
Mexico               0.01
New Zealand          0.01
Norway               0.01
Greece               0.01
Ireland              0.01
Bangladesh           0.01
South Africa         0.01
Hungary              0.01
Argentina            0.01
Portugal             0.00
Japan                0.00
Bulgaria             0.00
Nigeria              0.00
Indonesia            0.00
Singapore            0.00
Sri Lanka            0.00
Kenya                0.00
Slovenia             0.00
Philippines          0.00
Serbia               0.00
Egypt                0.00
Colombia             0.00
Chile                0.00
Name: proportion, dtype: float64

In [64]:
country_respondents = df['Country'].value_counts()
country_respondents

Country
United States        20949
India                 9061
Germany               5866
United Kingdom        5737
Canada                3395
                     ...
Tonga                    1
Timor-Leste              1
North Korea              1
Brunei Darussalam        1
Chad                     1
Name: count, Length: 179, dtype: int64

In [65]:
country_uses_python = Country_grp['LanguageWorkedWith'].apply(lambda x:x.str.contains('Python').sum())

country_uses_python

Country
Afghanistan                              8
Albania                                 23
Algeria                                 40
Andorra                                  0
Angola                                   2
                                        ..
Venezuela, Bolivarian Republic of...    28
Viet Nam                                78
Yemen                                    3
Zambia                                   4
Zimbabwe                                14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [66]:
python_df = pd.concat([country_respondents,country_uses_python],axis='columns',sort=False)
python_df

                   count  LanguageWorkedWith
Country
United States      20949               10083
India               9061                3105
Germany             5866                2451
United Kingdom      5737                2384
Canada              3395                1558
...                  ...                 ...
Tonga                  1                   0
Timor-Leste            1                   1
North Korea            1                   0
Brunei Darussalam      1                   0
Chad                   1                   0

[179 rows x 2 columns]

In [68]:
python_df.columns = ["NumRespodents","NumKnowsPython"]

In [69]:
python_df

                   NumRespodents  NumKnowsPython
Country
United States              20949           10083
India                       9061            3105
Germany                     5866            2451
United Kingdom              5737            2384
Canada                      3395            1558
...                          ...             ...
Tonga                          1               0
Timor-Leste                    1               1
North Korea                    1               0
Brunei Darussalam              1               0
Chad                           1               0

[179 rows x 2 columns]

In [70]:
python_df['PctKnowsPython'] = python_df['NumKnowsPython']/python_df['NumRespodents'] * 100
python_df

                   NumRespodents  NumKnowsPython  PctKnowsPython
Country
United States              20949           10083           48.13
India                       9061            3105           34.27
Germany                     5866            2451           41.78
United Kingdom              5737            2384           41.55
Canada                      3395            1558           45.89
...                          ...             ...             ...
Tonga                          1               0            0.00
Timor-Leste                    1               1          100.00
North Korea                    1               0            0.00
Brunei Darussalam              1               0            0.00
Chad                           1               0            0.00

[179 rows x 3 columns]

In [71]:
python_df.sort_values(by='PctKnowsPython',ascending=False,inplace=True)

In [73]:
python_df.head(50)

,NumRespodents,NumKnowsPython,PctKnowsPython
Country,,,
Sao Tome and Principe,1,1,100.00
Timor-Leste,1,1,100.00
Dominica,1,1,100.00
Niger,1,1,100.00
Turkmenistan,7,6,85.71
Mauritania,7,5,71.43
Guinea,3,2,66.67
Bahamas,3,2,66.67
Guyana,3,2,66.67
Uganda,72,47,65.28
Iceland,49,30,61.22
Haiti,5,3,60.00
Benin,5,3,60.00
Namibia,5,3,60.00
"Congo, Republic of the...",7,4,57.14
Oman,11,6,54.55
Cuba,30,16,53.33
Republic of Korea,39,20,51.28
San Marino,2,1,50.00
Sierra Leone,2,1,50.00
Monaco,4,2,50.00
South Korea,160,80,50.00
Bhutan,2,1,50.00
Seychelles,2,1,50.00
Chile,206,102,49.51
Finland,546,266,48.72
Kenya,249,120,48.19
United States,20949,10083,48.13
Israel,952,457,48.00
Ecuador,82,39,47.56
Taiwan,187,88,47.06
Montenegro,17,8,47.06
Mongolia,17,8,47.06
Switzerland,978,460,47.03
United Republic of Tanzania,32,15,46.88
Hong Kong (S.A.R.),188,88,46.81
Japan,391,182,46.55
Maldives,13,6,46.15
Canada,3395,1558,45.89
Singapore,303,139,45.87
New Zealand,524,236,45.04
China,664,297,44.73
Honduras,27,12,44.44
France,2391,1054,44.08
Iraq,39,17,43.59
Thailand,214,92,42.99
Democratic Republic of the Congo,7,3,42.86
Nepal,237,101,42.62
Estonia,195,82,42.05
Russian Federation,1694,708,41.79

In [74]:
python_df.loc['India']

NumRespodents    9061.00
NumKnowsPython   3105.00
PctKnowsPython     34.27
Name: India, dtype: float64