In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"Data/Movieratingdata8.csv")
df

       Genre  Year  Budget(M$)  Rating %
0     Action  2008          28        48
1     Action  2009         200        63
2     Action  2008          32        57
3     Action  2010          20        52
4  Adventure  2009          18        84
5  Adventure  2010         105        44
6     Comedy  2010          20        70
7     Comedy  2008           8        81
8     Comedy  2009          30        71

In [3]:
df.pivot_table(index='Genre')

           Budget(M$)  Rating %     Year
Genre
Action      70.000000      55.0  2008.75
Adventure   61.500000      64.0  2009.50
Comedy      19.333333      74.0  2009.00

In [4]:
action1 = df['Genre'] == 'Action'
df.loc[action1]['Budget(M$)'].sum()

280

In [5]:
df.pivot_table(index='Genre',aggfunc='sum')

           Budget(M$)  Rating %  Year
Genre
Action            280       220  8035
Adventure         123       128  4019
Comedy             58       222  6027

In [6]:
df.pivot_table(index='Genre',columns='Year',aggfunc='sum')

          Budget(M$)               Rating %
Year            2008   2009   2010     2008  2009  2010
Genre
Action          60.0  200.0   20.0    105.0  63.0  52.0
Adventure        NaN   18.0  105.0      NaN  84.0  44.0
Comedy           8.0   30.0   20.0     81.0  71.0  70.0

In [7]:
df[(df['Year'] == 2008) & (df['Genre'] == 'Adventure')]

Empty DataFrame
Columns: [Genre, Year, Budget(M$), Rating %]
Index: []

In [8]:
# max,sum,count,min,mean


df.pivot_table(index='Genre',columns='Year',aggfunc='median',fill_value=61.5)

          Budget(M$)               Rating %
Year            2008   2009   2010     2008  2009  2010
Genre
Action          30.0  200.0   20.0     52.5  63.0  52.0
Adventure       61.5   18.0  105.0     61.5  84.0  44.0
Comedy           8.0   30.0   20.0     81.0  71.0  70.0

In [9]:
# df[df['Genre'] == 'Adventure']['Budget(M$)'].median()

In [10]:
df.pivot_table(index='Genre',columns='Year',aggfunc='mean',fill_value=61.5,margins=True)

          Budget(M$)                                    Rating %             \
Year            2008        2009        2010        All     2008       2009
Genre
Action     30.000000  200.000000   20.000000  70.000000     52.5  63.000000
Adventure  61.500000   18.000000  105.000000  61.500000     61.5  84.000000
Comedy      8.000000   30.000000   20.000000  19.333333     81.0  71.000000
All        22.666667   82.666667   48.333333  51.222222     62.0  72.666667


Year            2010        All
Genre
Action     52.000000  55.000000
Adventure  44.000000  64.000000
Comedy     70.000000  74.000000
All        55.333333  63.333333

In [11]:
df = pd.read_csv(r"Data/Movieratingdata8.csv")
df

       Genre  Year  Budget(M$)  Rating %
0     Action  2008          28        48
1     Action  2009         200        63
2     Action  2008          32        57
3     Action  2010          20        52
4  Adventure  2009          18        84
5  Adventure  2010         105        44
6     Comedy  2010          20        70
7     Comedy  2008           8        81
8     Comedy  2009          30        71

In [12]:
df.shape

(9, 4)

In [13]:
pd.melt(df)

      variable      value
0        Genre     Action
1        Genre     Action
2        Genre     Action
3        Genre     Action
4        Genre  Adventure
5        Genre  Adventure
6        Genre     Comedy
7        Genre     Comedy
8        Genre     Comedy
9         Year       2008
10        Year       2009
11        Year       2008
12        Year       2010
13        Year       2009
14        Year       2010
15        Year       2010
16        Year       2008
17        Year       2009
18  Budget(M$)         28
19  Budget(M$)        200
20  Budget(M$)         32
21  Budget(M$)         20
22  Budget(M$)         18
23  Budget(M$)        105
24  Budget(M$)         20
25  Budget(M$)          8
26  Budget(M$)         30
27    Rating %         48
28    Rating %         63
29    Rating %         57
30    Rating %         52
31    Rating %         84
32    Rating %         44
33    Rating %         70
34    Rating %         81
35    Rating %         71

In [14]:
pd.melt(df,id_vars='Year')

    Year    variable      value
0   2008       Genre     Action
1   2009       Genre     Action
2   2008       Genre     Action
3   2010       Genre     Action
4   2009       Genre  Adventure
5   2010       Genre  Adventure
6   2010       Genre     Comedy
7   2008       Genre     Comedy
8   2009       Genre     Comedy
9   2008  Budget(M$)         28
10  2009  Budget(M$)        200
11  2008  Budget(M$)         32
12  2010  Budget(M$)         20
13  2009  Budget(M$)         18
14  2010  Budget(M$)        105
15  2010  Budget(M$)         20
16  2008  Budget(M$)          8
17  2009  Budget(M$)         30
18  2008    Rating %         48
19  2009    Rating %         63
20  2008    Rating %         57
21  2010    Rating %         52
22  2009    Rating %         84
23  2010    Rating %         44
24  2010    Rating %         70
25  2008    Rating %         81
26  2009    Rating %         71

In [15]:
pd.melt(df,id_vars='Year',value_vars='Genre')

   Year variable      value
0  2008    Genre     Action
1  2009    Genre     Action
2  2008    Genre     Action
3  2010    Genre     Action
4  2009    Genre  Adventure
5  2010    Genre  Adventure
6  2010    Genre     Comedy
7  2008    Genre     Comedy
8  2009    Genre     Comedy

In [16]:
data = {'date1':['2020-12-01','2020-12-03','2020-12-05','2020-12-06','2020-12-08'],
        'date2':['201201','201203','201205','201206','201208',],
        'store':['A','B','C','D','E'],
        'sales':[2000,3000,4000,5000,6000]}

In [17]:
df = pd.DataFrame(data)
df

        date1   date2 store  sales
0  2020-12-01  201201     A   2000
1  2020-12-03  201203     B   3000
2  2020-12-05  201205     C   4000
3  2020-12-06  201206     D   5000
4  2020-12-08  201208     E   6000

In [18]:
df['date1'] = pd.to_datetime(df['date1'])

In [19]:
df.dtypes

date1    datetime64[ns]
date2            object
store            object
sales             int64
dtype: object

In [20]:
df['date1'] = df['date1'].astype('datetime64[ns]')

In [21]:
df.dtypes

date1    datetime64[ns]
date2            object
store            object
sales             int64
dtype: object

In [22]:
df['date1'].dt.day_name()

0     Tuesday
1    Thursday
2    Saturday
3      Sunday
4     Tuesday
Name: date1, dtype: object

In [23]:
df

       date1   date2 store  sales
0 2020-12-01  201201     A   2000
1 2020-12-03  201203     B   3000
2 2020-12-05  201205     C   4000
3 2020-12-06  201206     D   5000
4 2020-12-08  201208     E   6000

In [24]:
df['date1'].max()

Timestamp('2020-12-08 00:00:00')

In [25]:
df[(df['date1'] >= pd.to_datetime('2020-12-03')) & (df['date1'] <= pd.to_datetime('2020-12-06'))]

       date1   date2 store  sales
1 2020-12-03  201203     B   3000
2 2020-12-05  201205     C   4000
3 2020-12-06  201206     D   5000

In [26]:
# df['date2'] = df['date2'].astype('datetime64[ns]')

In [27]:
# df

In [28]:
df['date2'] = pd.to_datetime(df['date2']  , format="%y%m%d")

In [29]:
df

       date1      date2 store  sales
0 2020-12-01 2020-12-01     A   2000
1 2020-12-03 2020-12-03     B   3000
2 2020-12-05 2020-12-05     C   4000
3 2020-12-06 2020-12-06     D   5000
4 2020-12-08 2020-12-08     E   6000

In [30]:
import datetime as dt

data = {'date1':['2020-12-01','2020-12-03','2020-12-05','2020-12-06','2020-12-08'],
        'date2':['201201','201203','201205','201206','201208',],
        'store':['A','B','C','D','E'],
        'sales':[2000,3000,4000,5000,6000]}

df = pd.DataFrame(data)
df

        date1   date2 store  sales
0  2020-12-01  201201     A   2000
1  2020-12-03  201203     B   3000
2  2020-12-05  201205     C   4000
3  2020-12-06  201206     D   5000
4  2020-12-08  201208     E   6000

In [32]:
df['date2'] = df['date2'].astype('datetime64[ns]')

In [33]:
import datetime as dt

In [37]:
df['date2'].dt.strftime('%d-%m-%y')

0    20-12-01
1    20-12-03
2    20-12-05
3    20-12-06
4    20-12-08
Name: date2, dtype: object

In [38]:
df['date1'] = pd.to_datetime(df['date1'])
df

       date1      date2 store  sales
0 2020-12-01 2001-12-20     A   2000
1 2020-12-03 2003-12-20     B   3000
2 2020-12-05 2005-12-20     C   4000
3 2020-12-06 2006-12-20     D   5000
4 2020-12-08 2008-12-20     E   6000

In [39]:
df.dtypes

date1    datetime64[ns]
date2    datetime64[ns]
store            object
sales             int64
dtype: object

In [41]:
df.sort_values(by='date1',ascending=False)

       date1      date2 store  sales
4 2020-12-08 2008-12-20     E   6000
3 2020-12-06 2006-12-20     D   5000
2 2020-12-05 2005-12-20     C   4000
1 2020-12-03 2003-12-20     B   3000
0 2020-12-01 2001-12-20     A   2000

In [42]:
df['date2'].dt.strftime('%d-%m-%Y')

0    20-12-2001
1    20-12-2003
2    20-12-2005
3    20-12-2006
4    20-12-2008
Name: date2, dtype: object

In [44]:
df['date2'].dt.strftime('%d-%m-%Y')

0    20-12-2001
1    20-12-2003
2    20-12-2005
3    20-12-2006
4    20-12-2008
Name: date2, dtype: object