In [1]:
import pandas as pd
import numpy as np

In [2]:

student_dict = {
    "Iq":[100,90,120,80,0,0],
    "Marks":[80,70,100,50,0,0],
    "Package":[10,7,14,2,0,0],
    "Name": ['A','B','C','D','E','F']
}

df_dict  = pd.DataFrame(student_dict)
df_dict

    Iq  Marks  Package Name
0  100     80       10    A
1   90     70        7    B
2  120    100       14    C
3   80     50        2    D
4    0      0        0    E
5    0      0        0    F

In [3]:
movies = pd.read_csv('data/movies.csv')
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [4]:
ipl = pd.read_csv('data/ipl-matches.csv')
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

# rename( ) , isnull(),isna(),Maths Methods,filtering Data

## rename

In [5]:
df_dict

    Iq  Marks  Package Name
0  100     80       10    A
1   90     70        7    B
2  120    100       14    C
3   80     50        2    D
4    0      0        0    E
5    0      0        0    F

In [6]:
df_dict.rename({"Marks":"Score"},axis=1)

    Iq  Score  Package Name
0  100     80       10    A
1   90     70        7    B
2  120    100       14    C
3   80     50        2    D
4    0      0        0    E
5    0      0        0    F

In [7]:
df_dict.rename(columns={"Mark":"Score"},inplace=True)

In [8]:
df_dict

    Iq  Marks  Package Name
0  100     80       10    A
1   90     70        7    B
2  120    100       14    C
3   80     50        2    D
4    0      0        0    E
5    0      0        0    F

In [9]:
df_dict.columns

Index(['Iq', 'Marks', 'Package', 'Name'], dtype='object')

In [10]:
df_dict.columns = ['Iq', 'Marks', 'Package(lpa)', 'Name']

In [11]:
df_dict

    Iq  Marks  Package(lpa) Name
0  100     80            10    A
1   90     70             7    B
2  120    100            14    C
3   80     50             2    D
4    0      0             0    E
5    0      0             0    F

### isna() , isnull()

In [32]:
student_dict = {
    "Iq":[100,90,120,80,np.nan,0],
    "Marks":[80,70,100,50,0,0],
    "Package":[10,7,14,2,0,None],
    "Name": ['A','A','C','E','E',np.nan]
}

df_dict2  = pd.DataFrame(student_dict)
df_dict2

      Iq  Marks  Package Name
0  100.0     80     10.0    A
1   90.0     70      7.0    A
2  120.0    100     14.0    C
3   80.0     50      2.0    E
4    NaN      0      0.0    E
5    0.0      0      NaN  NaN

In [33]:
df_dict2.isna().sum()

Iq         1
Marks      0
Package    1
Name       1
dtype: int64

In [34]:
df_dict2.isnull().sum()

Iq         1
Marks      0
Package    1
Name       1
dtype: int64

### min , max , mean , median , mode , var , std

In [35]:
df_dict

    Iq  Marks  Package(lpa) Name
0  100     80            10    A
1   90     70             7    B
2  120    100            14    C
3   80     50             2    D
4    0      0             0    E
5    0      0             0    F

In [36]:
df_dict.min()

Iq              0
Marks           0
Package(lpa)    0
Name            A
dtype: object

In [37]:
df_dict.max()

Iq              120
Marks           100
Package(lpa)     14
Name              F
dtype: object

In [38]:
df_dict.sum()

Iq                 390
Marks              300
Package(lpa)        33
Name            ABCDEF
dtype: object

In [39]:
df_dict.columns

Index(['Iq', 'Marks', 'Package(lpa)', 'Name'], dtype='object')

In [40]:
df_dict.mean()

TypeError: Could not convert ['ABCDEF'] to numeric

In [41]:
df_dict[['Iq', 'Marks', 'Package(lpa)']].mean()

Iq              65.0
Marks           50.0
Package(lpa)     5.5
dtype: float64

In [42]:
df_dict[['Iq', 'Marks', 'Package(lpa)']].median()

Iq              85.0
Marks           60.0
Package(lpa)     4.5
dtype: float64

In [44]:
# mode --> categorical data (text)

df_dict2['Name'].mode()

0    A
1    E
Name: Name, dtype: object

In [45]:
df_dict[['Iq', 'Marks', 'Package(lpa)']].var()

Iq              2710.0
Marks           1760.0
Package(lpa)      33.5
dtype: float64

In [46]:
df_dict[['Iq', 'Marks', 'Package(lpa)']].std()

Iq              52.057660
Marks           41.952354
Package(lpa)     5.787918
dtype: float64

## filtering Data

#### 1. Find all the Final Winner

In [65]:
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [51]:
ipl[ipl['MatchNumber'] == "Final"][["Team1","Team2","WinningTeam"]]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
74,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
134,Delhi Capitals,Mumbai Indians,Mumbai Indians
194,Mumbai Indians,Chennai Super Kings,Mumbai Indians
254,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings
314,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians
373,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad
433,Mumbai Indians,Chennai Super Kings,Mumbai Indians
492,Kolkata Knight Riders,Kings XI Punjab,Kolkata Knight Riders
552,Chennai Super Kings,Mumbai Indians,Mumbai Indians
628,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders
702,Chennai Super Kings,Royal Challengers Bangalore,Chennai Super Kings
775,Chennai Super Kings,Mumbai Indians,Chennai Super Kings
835,Royal Challengers Bangalore,Deccan Chargers,Deccan Chargers
892,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals

#### 2. How many matches "Super over" finishes occured

In [53]:
ipl['SuperOver'].value_counts()

SuperOver
N    932
Y     14
Name: count, dtype: int64

In [57]:
ipl[ipl['SuperOver'] == "Y"][["Team1","Team2","WinningTeam"]]

,Team1,Team2,WinningTeam
114,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals
158,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders
159,Mumbai Indians,Kings XI Punjab,Kings XI Punjab
184,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore
192,Delhi Capitals,Kings XI Punjab,Delhi Capitals
203,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians
244,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals
339,Gujarat Lions,Mumbai Indians,Mumbai Indians
474,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab
533,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals
608,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
621,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
819,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab
883,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals

#### 3. How many matches has csk won in Kolkata

In [ ]:
# winning team --> Chennai Super Kings
# city --> Kolkata
# and

In [58]:
ipl['City'].value_counts()

City
Mumbai            159
Kolkata            79
Delhi              78
Chennai            67
Bangalore          65
Hyderabad          64
Chandigarh         56
Pune               51
Jaipur             47
Abu Dhabi          37
Ahmedabad          19
Bengaluru          15
Durban             15
Visakhapatnam      13
Dubai              13
Centurion          12
Sharjah            10
Rajkot             10
Navi Mumbai         9
Indore              9
Dharamsala          9
Johannesburg        8
Port Elizabeth      7
Cuttack             7
Ranchi              7
Cape Town           7
Raipur              6
Kochi               5
Kanpur              4
Nagpur              3
Kimberley           3
East London         3
Bloemfontein        2
Name: count, dtype: int64

In [59]:
ipl['WinningTeam'] == "Chennai Super Kings"

0      False
1      False
2      False
3      False
4      False
       ...
945    False
946    False
947    False
948     True
949    False
Name: WinningTeam, Length: 950, dtype: bool

In [68]:
ipl[(ipl['City'] == "Kolkata") & (ipl['WinningTeam'] == "Chennai Super Kings")][["Team1","Team2","City","WinningTeam"]].shape

(5, 4)

In [71]:
city = (ipl['City'] == "Kolkata")
win_team =  (ipl['WinningTeam'] == "Chennai Super Kings")

ipl[city & win_team][["Team1","Team2","City","WinningTeam"]]

                     Team1                Team2     City          WinningTeam
224  Kolkata Knight Riders  Chennai Super Kings  Kolkata  Chennai Super Kings
602  Kolkata Knight Riders  Chennai Super Kings  Kolkata  Chennai Super Kings
641  Kolkata Knight Riders  Chennai Super Kings  Kolkata  Chennai Super Kings
827  Kolkata Knight Riders  Chennai Super Kings  Kolkata  Chennai Super Kings
908  Kolkata Knight Riders  Chennai Super Kings  Kolkata  Chennai Super Kings

In [70]:
ipl[(ipl['City'] == "Ahmedabad") & (ipl['WinningTeam'] == "Chennai Super Kings")][["Team1","Team2","City","WinningTeam"]]

Empty DataFrame
Columns: [Team1, Team2, City, WinningTeam]
Index: []

##### Home Work
1. All city (how many times)--> winning team --> Chennai Super Kings

#### 4. Toss Winner is match Winner in percentage

In [73]:
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [77]:
ipl[ipl['TossWinner'] == ipl['WinningTeam']][["Team1","Team2","TossWinner","WinningTeam"]]

,Team1,Team2,TossWinner,WinningTeam
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,Rajasthan Royals
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans,Gujarat Titans
5,Delhi Capitals,Mumbai Indians,Mumbai Indians,Mumbai Indians
8,Lucknow Super Giants,Kolkata Knight Riders,Lucknow Super Giants,Lucknow Super Giants
11,Rajasthan Royals,Lucknow Super Giants,Rajasthan Royals,Rajasthan Royals
...,...,...,...,...
935,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,Chennai Super Kings
937,Mumbai Indians,Deccan Chargers,Deccan Chargers,Deccan Chargers
939,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,Rajasthan Royals
941,Deccan Chargers,Rajasthan Royals,Rajasthan Royals,Rajasthan Royals
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,Chennai Super Kings

In [80]:
ipl.shape[0]

950

In [81]:
(ipl[ipl['TossWinner'] == ipl['WinningTeam']][["Team1","Team2","TossWinner","WinningTeam"]].shape[0]/ipl.shape[0]) * 100

51.473684210526315

#### 5. Moives with rating higher than 8 and votes less 1000

In [82]:
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [84]:
rating = movies['imdb_rating'] > 8
votes = movies['imdb_votes'] < 1000

movies[rating & votes][['original_title','year_of_release','runtime','genres','imdb_rating','imdb_votes','actors']]

,original_title,year_of_release,runtime,genres,imdb_rating,imdb_votes,actors
41,Family of Thakurganj,2019,127,Action|Drama,9.4,895,Jimmy Sheirgill|Mahie Gill|Nandish Singh|Prana...
207,G Kutta Se,2017,104,Drama,8.3,45,Rajveer Ankur Singh|Neha Chauhan|Vibha Tyagi|
216,YADVI: The Dignified Princess,2017,107,Biography|Drama|History,8.2,28,Prisha Aneja|Vinti Aneja|Marianne Borgo|Rachel...
219,Raag Desh,2017,135,Action|Drama|History,8.3,341,Kunal Kapoor|Amit Sadh|Mohit Marwah|Kenneth De...
1060,Blood Brothers,2007,13,Drama|Short|Thriller,8.2,187,Jazzy Doe|Siddharth|Pavan Malhotra|Tuhina Vora...
1435,Final Solution,2004,218,Documentary,8.7,333,NaN
1540,Jang Aur Aman,2002,148,Documentary|War,8.3,113,NaN

In [85]:
movies[rating & votes][['original_title','year_of_release','runtime','genres','imdb_rating','imdb_votes','actors']].shape

(7, 7)