In [1]:
# astype
# between
# clip
# drop_duplicates
# isnull
# dropna
# fillna
# isin
# apply
# copy

In [2]:
import numpy as np
import pandas as pd

In [7]:
subs = pd.read_csv('Data/subs.csv').squeeze('columns')
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [8]:
vk = pd.read_csv('Data/kohli_ipl.csv',index_col='match_no').squeeze('columns')
vk.head()

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [9]:
movies = pd.read_csv('Data/bollywood.csv',index_col='movie').squeeze('columns')
movies.head()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [10]:
ser1 = pd.Series(np.arange(3,13,3.0))
print(ser1)

0     3.0
1     6.0
2     9.0
3    12.0
dtype: float64

In [11]:
ser1.astype('int64')

0     3
1     6
2     9
3    12
dtype: int64

In [12]:
ser1

0     3.0
1     6.0
2     9.0
3    12.0
dtype: float64

In [15]:
vk.between(20,51)

match_no
1      False
2       True
3      False
4      False
5      False
       ...
211    False
212     True
213    False
214     True
215    False
Name: runs, Length: 215, dtype: bool

In [18]:
vk[vk.between(20,51)]

match_no
2      23
7      34
9      21
12     38
15     50
       ..
200    41
203    48
210    30
212    20
214    25
Name: runs, Length: 77, dtype: int64

0     3.0
1     6.0
2     9.0
3    12.0
dtype: float64

In [26]:
ser2 = pd.Series(np.random.randint(1,100,20))

In [27]:
ser2

0      7
1     91
2     82
3     95
4     65
5     54
6     13
7     59
8     18
9     89
10    47
11     6
12    70
13    38
14    56
15    84
16    19
17    25
18    45
19    48
dtype: int32

In [28]:
ser2.clip(10,50)

0     10
1     50
2     50
3     50
4     50
5     50
6     13
7     50
8     18
9     50
10    47
11    10
12    50
13    38
14    50
15    50
16    19
17    25
18    45
19    48
dtype: int32

In [29]:
ser3 = pd.Series([1,2,3,4,4,5])
ser3

0    1
1    2
2    3
3    4
4    4
5    5
dtype: int64

In [30]:
ser3.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [31]:
ser3[ser3.duplicated()]

4    4
dtype: int64

In [35]:
ser3.drop_duplicates()

0    1
1    2
2    3
3    4
5    5
dtype: int64

In [38]:
ser3.drop_duplicates().reset_index()

   index  0
0      0  1
1      1  2
2      2  3
3      3  4
4      5  5

In [39]:
ser3.drop_duplicates().reset_index(drop=True)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [41]:
# Null values --> NaN , blank_space , None

Ser4 = pd.Series([1,2,3,None,np.nan,8])
Ser4

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    8.0
dtype: float64

In [43]:
# 'isna', 'isnull'

Ser4.isnull().sum()

np.int64(2)

In [50]:
Ser4.isna()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [47]:
Ser4.dropna()

0    1.0
1    2.0
2    3.0
5    8.0
dtype: float64

In [49]:
# print(dir(Ser4))

In [53]:
Ser4

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    8.0
dtype: float64

In [56]:
# for filling values i use "mean"
mean = Ser4.mean()
mean

np.float64(3.5)

In [57]:
Ser4.fillna(mean)

0    1.0
1    2.0
2    3.0
3    3.5
4    3.5
5    8.0
dtype: float64

In [58]:
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [60]:
movies.isin(["Anupam Kher"])

movie
Uri: The Surgical Strike                False
Battalion 609                           False
The Accidental Prime Minister (film)     True
Why Cheat India                         False
Evening Shadows                         False
                                        ...
Hum Tumhare Hain Sanam                  False
Aankhen (2002 film)                     False
Saathiya (film)                         False
Company (film)                          False
Awara Paagal Deewana                    False
Name: lead, Length: 1500, dtype: bool

In [61]:
movies[movies.isin(["Anupam Kher"])]

movie
The Accidental Prime Minister (film)    Anupam Kher
One Day: Justice Delivered              Anupam Kher
Dirty Politics (film)                   Anupam Kher
Singham Returns                         Anupam Kher
Ekkees Toppon Ki Salaami                Anupam Kher
Hum Hai Raahi Car Ke                    Anupam Kher
Mr. Bhatti on Chutti                    Anupam Kher
Sahi Dhandhe Galat Bande                Anupam Kher
Yeh Mera India                          Anupam Kher
Meerabai Not Out                        Anupam Kher
Khosla Ka Ghosla                        Anupam Kher
Maine Gandhi Ko Nahin Mara              Anupam Kher
Shukriya: Till Death Do Us Apart        Anupam Kher
Name: lead, dtype: object

### Functions and Lambda function on Pandas Series

`subs.apply(lambda x:'good day' if x > subs.mean() else 'bad day')`

In [62]:
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [63]:
subs.mean()

np.float64(135.64383561643837)

In [ ]:
# Mean > X-value --> "Good Day"
# Mean < X-value --> "Bad Day"

In [65]:
def day_check(x):
    
    if x > subs.mean():
        return "Good Day"
    else:
        return "Bad Day"

In [67]:
subs.apply(day_check)

0       Bad Day
1       Bad Day
2       Bad Day
3       Bad Day
4       Bad Day
         ...
360    Good Day
361    Good Day
362    Good Day
363    Good Day
364    Good Day
Name: Subscribers gained, Length: 365, dtype: object

In [70]:
subs.apply(day_check).value_counts()

Subscribers gained
Bad Day     202
Good Day    163
Name: count, dtype: int64

In [72]:
subs.apply(lambda x:"Good Day" if x > subs.mean() else "Bad Day")

0       Bad Day
1       Bad Day
2       Bad Day
3       Bad Day
4       Bad Day
         ...
360    Good Day
361    Good Day
362    Good Day
363    Good Day
364    Good Day
Name: Subscribers gained, Length: 365, dtype: object

In [73]:
subs.apply(lambda x:"Good Day" if x > subs.mean() else "Bad Day").value_counts()

Subscribers gained
Bad Day     202
Good Day    163
Name: count, dtype: int64

### Pandas DataFrame

In [74]:
# 2d --> row, columns

# create 
# 1. List

student_data = [
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
    ]

df = pd.DataFrame(student_data)
df

     0    1   2
0  100   80  10
1   90   70   7
2  120  100  14
3   80   50   2

In [75]:
df = pd.DataFrame(student_data,columns=['IQ','Marks','Package'])
df

    IQ  Marks  Package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [76]:
student_dict = {
    "Iq":[100,90,120,80,0,0],
    "Marks":[80,70,100,50,0,0],
    "Package":[10,7,14,2,0,0],
    "Name": ['A','B','C','D','E','F']
}

df_dict  = pd.DataFrame(student_dict)
df_dict

    Iq  Marks  Package Name
0  100     80       10    A
1   90     70        7    B
2  120    100       14    C
3   80     50        2    D
4    0      0        0    E
5    0      0        0    F

In [79]:
movies = pd.read_csv('../DataFrame/Data/movies.csv')
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [ ]:
# shape :- Return a tuple representing the dimensionality of the DataFrame (Rows,Columns).
# dtypes :- Return the data types of data in DataFrame.
# index :- The index (row lables) of the DataFrame.
# columns :- The column lables of the DataFrame.
# values :- Return a Numpy representation of the DataFrame.
# axes :- Return a list representing both the axes (axis 0 i.e, index and axis 1, i.e, columns).
# size :- Return an int representing the number of elements in this object.
# ndim :- Return an int representing the number of axes/array dimensions.
# empty :- Indicator whether DataFrame is empty.
# T :- Transpose index and columns.

In [81]:
# 4 rows , 3 columns
df.shape

(4, 3)

In [82]:
df

    IQ  Marks  Package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [83]:
df.dtypes

IQ         int64
Marks      int64
Package    int64
dtype: object

In [85]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [86]:
df.values

array([[100,  80,  10],
       [ 90,  70,   7],
       [120, 100,  14],
       [ 80,  50,   2]])

In [87]:
df.columns

Index(['IQ', 'Marks', 'Package'], dtype='object')

In [89]:
df.axes

[RangeIndex(start=0, stop=4, step=1),
 Index(['IQ', 'Marks', 'Package'], dtype='object')]

In [91]:
df.shape

(4, 3)

In [92]:
4 * 3

12

In [93]:
df.size

12

In [94]:
df.ndim

2

In [96]:
pd.DataFrame().empty

True

In [97]:
df.empty

False

In [98]:
df

    IQ  Marks  Package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [99]:
df.T

           0   1    2   3
IQ       100  90  120  80
Marks     80  70  100  50
Package   10   7   14   2

In [108]:
movies.head(5)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [110]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [ ]:
# --> categorical data --> text(object) --> 14
# ---> Numberical Data --> int,float --> 4

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   IQ       4 non-null      int64
 1   Marks    4 non-null      int64
 2   Package  4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes

In [114]:
df2 = df.astype(np.int32)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   IQ       4 non-null      int32
 1   Marks    4 non-null      int32
 2   Package  4 non-null      int32
dtypes: int32(3)
memory usage: 180.0 bytes

In [117]:
df.describe().T

         count   mean        std   min    25%   50%    75%    max
IQ         4.0  97.50  17.078251  80.0  87.50  95.0  105.0  120.0
Marks      4.0  75.00  20.816660  50.0  65.00  75.0   85.0  100.0
Package    4.0   8.25   5.057997   2.0   5.75   8.5   11.0   14.0

In [120]:
df.median()

IQ         95.0
Marks      75.0
Package     8.5
dtype: float64

In [118]:
df

    IQ  Marks  Package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2

In [119]:
# 100 - 25

75

In [ ]:
87.50

In [122]:
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [126]:
df_dict

    Iq  Marks  Package Name
0  100     80       10    A
1   90     70        7    B
2  120    100       14    C
3   80     50        2    D
4    0      0        0    E
5    0      0        0    F

In [128]:
df_dict.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [132]:
df_dict.drop('Name',axis=1)

    Iq  Marks  Package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     50        2
4    0      0        0
5    0      0        0

In [133]:
df_dict.drop('Name',axis=1).duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

### Markdown Language
1. cell convert into code --> esc y
2. cell convert into markdown --> esc m
3. Something `highlight`
4. Pandas **code**

> Python is Amzaing

Here’s some **random code** (Python) that makes a tiny “guess the number” game:

```python
import random

secret = random.randint(1, 20)
tries = 5

print("🎲 Guess the number (1 to 20). You have 5 tries!")

while tries > 0:
    guess = int(input("Your guess: "))

    if guess == secret:
        print("✅ Boom! Correct.")
        break
    elif guess < secret:
        print("📉 Too low.")
    else:
        print("📈 Too high.")

    tries -= 1
    print("Tries left:", tries)

if tries == 0:
    print("💀 Out of tries. The number was:", secret)
```

Want random code in **JavaScript**, **HTML/CSS**, or something more “data science vibe” (pandas/plots)?